### ISSUE TITLE
Seeker is working in Kali linux 2019.3

### ISSUE THREAD

**Issue by rraanaaa** [thewhiteh4t/seeker#101]
Hi,
When i run Seeker in Kali Linux i have this message error:

![20190908_171221-1](https://user-images.githubusercontent.com/55027225/64488775-dd1cff00-d25c-11e9-9b6c-dc881d4ab0c5.jpg)

Do you know what is the problem?

Thanks
Best regards

**Comment by thewhiteh4t** [comment]
https://github.com/thewhiteh4t/seeker/commit/c82d14db9a78c4f9554effa8f00f5e7bd44ba406#r34990244
