### ISSUE TITLE
User interaction is not working

### ISSUE THREAD

**Issue by rraanaaa** [thewhiteh4t/seeker#102]
Hi
I used manual tunnel ...and seeker started ....but i have another issue ...which url use to interact with user...i stuck at this point.
![20190908_182411-1](https://user-images.githubusercontent.com/55027225/64489642-8e746280-d266-11e9-9f20-7c4e888cb090.jpg)

Do u know what is exactly problem??

Best regards,
Thankx

**Comment by rraanaaa** [comment]
I used all Ngrok http/ https urls...but seeker is not working further

**Comment by thewhiteh4t** [comment]
Take a look in seeker screenshot above...
`append /nearyou/` to tunnel url`
Did you follow that?
Append means to add, so 
`https://ngrokUrl/nearyou/` will be your final url

**Comment by rraanaaa** [comment]
Sorry i don't get it....
Can u plz make final url...from above given snapshoot...so that i can properly understand ..

**Comment by rraanaaa** [comment]
Got it

**Comment by rraanaaa** [comment]
Thankx☺☺

**Comment by DragMix** [comment]
Hi dev, help me please, try to execute it on termux but it requires some tunnel
Which one, for example?

**Comment by neilkamulkar** [comment]
Can we have this utility working for the target without interaction ... Asking someone to click is very difficult
