### ISSUE TITLE
Termux requires -t arg

### ISSUE THREAD

**Issue by DragMix** [thewhiteh4t/seeker#103]
Hi dev, help me please, try to execute it on termux but it requires some tunnel
Which one, for example?

![Screenshot_2019-09-09-08-12-41-495_com termux](https://user-images.githubusercontent.com/53881141/64504715-a3d6a480-d2d9-11e9-806e-c0806e849c7f.png)

**Comment by DragMix** [comment]
As well I understand, script executes, but in your git isn't any word about it, help😅

**Comment by thewhiteh4t** [comment]
Sorry, I will update the Readme soon, till then this will clear your doubts : 
https://github.com/thewhiteh4t/seeker/commit/c82d14db9a78c4f9554effa8f00f5e7bd44ba406#r34990244

**Comment by DragMix** [comment]
ty man, really nice to get fast help:3

**Comment by thewhiteh4t** [comment]
Closing.

**Comment by DragMix** [comment]
Started it with default arg, it's waiting for user interaction :(

**Comment by thewhiteh4t** [comment]
@DragMix watch the demo video in Readme
