### ISSUE TITLE
I live in a country where Ngrok has blocked

### ISSUE THREAD

**Issue by nihilist718** [thewhiteh4t/seeker#105]
Hi, I live in a country where Ngrok is locked. Please help, since I tried to run Seeker on Kali Linux, but nothing worked out for me. What to do?

**Comment by thewhiteh4t** [comment]
@nihilist718 did you try default tunnel mode? 
`python3 seeker.py -t default`
Default mode uses serveo.

**Comment by nihilist718** [comment]
Yes, it helped. Thank you

**Comment by nihilist718** [comment]
[+] Checking Serveo Status...[ DOWN ]

**Comment by thewhiteh4t** [comment]
Which country?

**Comment by nihilist718** [comment]
Russia

**Comment by thewhiteh4t** [comment]
Serveo is also blocked in russia unfortunately :(

**Comment by nihilist718** [comment]
Okay thank you

**Comment by Snupedogs9345** [comment]
but there’s some sort of alternative to servio, I’m also from the Russian community and I also want to use this wonderful program

**Comment by nihilist718** [comment]
I don't know why, but Ngrok doesn't even work with vpn, but Serveo combined with vpn works fine
