### ISSUE TITLE
Can't operate latest 1.1.8

### ISSUE THREAD

**Issue by mahfuzt2** [thewhiteh4t/seeker#107]
i can't operate the latest version please help me. invalid tunnel mode. please help.
![Screenshot_2019-09-23-11-21-51-26_1](https://user-images.githubusercontent.com/50949356/65403181-939fe880-ddf4-11e9-82f6-e99dc8385003.png)

**Comment by thewhiteh4t** [comment]
@mahfuzt2 `python3 seeker.py -t default`

**Comment by mahfuzt2** [comment]
Got it.
Thanks a lot dear.
