### ISSUE TITLE
can't start seeker

### ISSUE THREAD

**Issue by lus1f3r** [thewhiteh4t/seeker#108]
Am I missing something here,but when I run it throws this
![Screenshot at 2019-09-23 23-30-16](https://user-images.githubusercontent.com/42700418/65444556-7998f100-de5a-11e9-98c2-385c7557aca2.png)

**Comment by thewhiteh4t** [comment]
@lus1f3r `python3 seeker.py -t default`

**Comment by lus1f3r** [comment]
Thanks
