### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by vishnux0** [thewhiteh4t/seeker#109]
Hii
When i run this tool it gives me this error: 
Traceback (most recent call last):                                  File "seeker.py", line 10, in <module>
    import requests                                               ModuleNotFoundError: No module named 'requests'
![Screenshot_2019-09-29-16-22-59-928_com termux](https://user-images.githubusercontent.com/55946846/65831637-85146e00-e2d9-11e9-8361-7cffc44b094e.png)

**Comment by thewhiteh4t** [comment]
`pip3 install requests`

**Comment by Raakazhugu** [comment]
How to install pip3

**Comment by thewhiteh4t** [comment]
@Raakazhugu if you google this exact same line `How to install pip3` you will get your answer, issues are not for these basic questions, google it

**Comment by Choudekarakash** [comment]
![Screenshot from 2020-07-13 18-15-56](https://user-images.githubusercontent.com/68231142/87306054-16856180-c535-11ea-8383-36e48dca3e14.png)

while i installing requests 
what do i do?
