### ISSUE TITLE
Subdomain error comes on terminal

### ISSUE THREAD

**Issue by bikash2424** [thewhiteh4t/seeker#111]
after enter the coomand python3 seeker.py -s rectum
![IMG_20190930_032357](https://user-images.githubusercontent.com/55961368/65897813-01a05e80-e365-11e9-927e-c79490a6ba2e.jpg)

usage: seeker.py [-h] [-s SUBDOMAIN] [-k KML] -t TUNNEL
seeker.py: error: the following arguments are required: -t/--tunnel

**Comment by Kayote23** [comment]
try to use it 
python3 seeker.py -t default
