### ISSUE TITLE
Can't start Seeker on usb persistance ubuntu 19.04

### ISSUE THREAD

**Issue by qfbalex** [thewhiteh4t/seeker#112]
Hello, i have'nt been able to run seeker properly, i've tried on kali linux and ubuntu and nothing, please help. I'm using a live usb persistance usb.
![Screenshot from 2019-10-03 04-22-38](https://user-images.githubusercontent.com/56135419/66159776-38ea6600-e618-11e9-860d-090552a57521.png)

**Comment by thewhiteh4t** [comment]
@qfbalex I am assuming you executed `install.sh` before executing `seeker`, inside seeker dir you will find a file named `install.log` please share it

**Comment by qfbalex** [comment]
I followed all instructions for instalation, here is the log
![Screenshot from 2019-10-04 14-40-36](https://user-images.githubusercontent.com/56135419/66217376-b19fff80-e6b6-11e9-998c-5d6720c5d370.png)

**Comment by thewhiteh4t** [comment]
@qfbalex error is right in front of you, you are not root, run install script as root and seeker too, 
try `sudo -s` and then follow instructions again

**Comment by qfbalex** [comment]
Problem solved thank you very much

**Comment by thewhiteh4t** [comment]
Closing.
