### ISSUE TITLE
guys what to do if it does not start

### ISSUE THREAD

**Issue by diadya** [thewhiteh4t/seeker#114]
![Screenshot_2019-10-05-10-37-04-056_com termux](https://user-images.githubusercontent.com/53941328/66251050-56284d00-e75c-11e9-9567-169e8028c44b.jpg)

**Comment by thewhiteh4t** [comment]
@diadya open your eyes and read the README

**Comment by diadya** [comment]
ok i did like readme says,just did not write a command - python seeker.py- again not working

**Comment by thewhiteh4t** [comment]
@diadya looks like you did not read this 
https://github.com/thewhiteh4t/seeker/blob/master/README.md#usage
