### ISSUE TITLE
Can't Run Install

### ISSUE THREAD

**Issue by mugi789** [thewhiteh4t/seeker#116]
![image](https://user-images.githubusercontent.com/32443765/67145034-b0222a00-f2a7-11e9-9c76-2fa4344dece9.png)
####################
_**Failed to execute process './install.sh'. Reason:
exec: Exec format error
The file './install.sh' is marked as an executable but could not be run by the operating system.**_

**Comment by mugi789** [comment]
Tested on Ubuntu 18.04

**Comment by thewhiteh4t** [comment]
@mugi789 you are using fish shell, things are a bit different for fish, try  `bash install.sh`
