### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Rizwan690** [thewhiteh4t/seeker#118]
When I try on iphone and huawei it not work .kindly solve the issue Thanks
Below is the error detail:

Traceback (most recent call last):
  File "seeker.py", line 313, in <module>
    wait()
  File "seeker.py", line 145, in wait
    main()
  File "seeker.py", line 182, in main
    print(G + '[+]' + C + ' CPU Cores  : ' + W + var_cores)
TypeError: can only concatenate str (not "NoneType") to str

**Comment by Rizwan690** [comment]
When I sent the genrated link to iphone user or huawei user it stops and give me the above error when they click on the link.
Kindly solve the issue. 
Thanks .
Great Tool (y)

**Comment by intelrj** [comment]
same error here

**Comment by thewhiteh4t** [comment]
@Rizwan690 @intelrj Fixed in new update `1.1.9` please try and report.
