### ISSUE TITLE
Php Server Failed

### ISSUE THREAD

**Issue by IllegalVibes** [thewhiteh4t/seeker#119]
Issue:
[+] Starting PHP Server......[ Failed ]

Console:
```

                        __
  ______  ____   ____  |  | __  ____ _______
 /  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/
/____  > \___  >\___  >|__|_ \ \___  >|__|
         \/      \/     \/      \/     \/

[>] Created By : thewhiteh4t
[>] Version    : 1.1.8

[+] Checking for Updates.....[ Up-To-Date ]

[+] Checking Serveo Status...[ UP ]

[+] Getting Serveo URL...

[+] URL : https://ipse.serveo.net/nearyou/

[+] Starting PHP Server......[ Failed ]
```

**Comment by thewhiteh4t** [comment]
@IllegalVibes inside `seeker/logs` you will find `php.log` please take a look and share

**Comment by IllegalVibes** [comment]
Aye so it was my fault.. I was editing the "NearYou" and had forgot to change a few things in seeker.py script I got it all good thank you sorry man Great work BTW keep it up. If you got discord feel free to drop it im curious on learning more and seeing how far I can go
