### ISSUE TITLE
Runnig seeker

### ISSUE THREAD

**Issue by benn1701** [thewhiteh4t/seeker#12]
Traceback (most recent call last):
  File "/usr/local/bin/seeker", line 209, in <module>
    ngrok()
  File "/usr/local/bin/seeker", line 103, in ngrok
    geturl()
  File "/usr/local/bin/seeker", line 88, in geturl
    r1 = requests.get('{}'.format(api))
  File "/usr/local/lib/python2.7/dist-packages/requests/api
py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api
py", line 58, in request
    return session.request(method=method, url=url, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/requests/ses
ions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/ses
ions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/ada
ters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(hos
='localhost', port=4040): Max retries exceeded with url: /a
i/tunnels (Caused by NewConnectionError('<urllib3.connectio
.HTTPConnection object at 0xb6709af0>: Failed to establish
 new connection: [Errno 111] Connection refused',))

**Comment by thewhiteh4t** [comment]
i need more details like what operating system you are using etc

**Comment by benn1701** [comment]
Ubuntu in "UserLAnd" app whit "ConnnectBot" app. These are in google play. And I have Andoid 6.

**Comment by thewhiteh4t** [comment]
Okay so i am also getting this same error and if you do this:
```
cd seeker/Ngrok
./ngrok http 80

Or

cd seeker/termux/Ngrok
./ngrok http 80
```
You get `illegal instruction` as output and ngrok fails,
Looks like ngrok is not compatible with userland i will give ubuntu on termux a try, lets see if it works

**Comment by thewhiteh4t** [comment]
Same problem in termux-ubuntu, you should run seeker in termux with the instructions i have provided in README, closing issue as this is a problem with ngrok
