### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by KaXXXIX** [thewhiteh4t/seeker#121]
Hello! I am from Russia and I have a question. You wrote that there will be no more application support in Russia. Namely, ngrok and serveo servers do not work in Russia. Is it possible to bypass this blocking in Russia? If so, write how. Sincerely, Mr. Kiryusha

**Comment by thewhiteh4t** [comment]
@KaXXXIX I don't know if it can be bypassed or not but you can always use a VPS and run seeker on it, no need of serveo or ngrok in that case

**Comment by KaXXXIX** [comment]
It seems .. I'm very dumb.
Do I need to order a VPS server? or how?
Sorry to take the time, but it happened. :(

**Comment by thewhiteh4t** [comment]
@KaXXXIX google Virtual Private Server

**Comment by KaXXXIX** [comment]
Thanks a lot! Good luck in the development! : 3
