### ISSUE TITLE
Seeker 1.1.8 issue with any iPhone interaction

### ISSUE THREAD

**Issue by EternalPunishment** [thewhiteh4t/seeker#122]
[seeker_issue_with_any_iphone.txt](https://github.com/thewhiteh4t/seeker/files/3806450/seeker_issue_with_any_iphone.txt)
There is a txt and link from Pastebin with terminal output with this issue.
https://pastebin.com/E4VpKeYM

**Comment by h4r7w3l1** [comment]
You can comment 182 string with "#" . Work correct.
https://github.com/thewhiteh4t/seeker/blob/4698a59d32a40be73e8fa5618ec3b4b5405b089f/seeker.py#L182
