### ISSUE TITLE
docker start problem

### ISSUE THREAD

**Issue by liuhailuo** [thewhiteh4t/seeker#124]
I start the project By using the docker , I have been downloaded the dockerFile .but  I start the project ,it  always asked me to add parameters 
usage: seeker.py [-h] [-s SUBDOMAIN] [-k KML] -t TUNNEL
seeker.py: error: the following arguments are required: -t/--tunnel
i add the  '-t manual ' ， it can start , but i don't know   the Access address

I hope to get a reply from the blogger 
 Thanks

**Comment by thewhiteh4t** [comment]
Duplicate issue, closing.
