### ISSUE TITLE
Hi there! I am from India and the serveo status seems to be down. So can u guide me how to use ngrok instead. I'm using termux latest version . Your seeker version is 1.1.8 which is currently installed. I read the manual mode and it says "append /near you/ to tunnel URL". Can you please guide me in this matter? Thanks in advance.

### ISSUE THREAD

**Issue by shasankp-create** [thewhiteh4t/seeker#129]
Please add ngrok support for both Linux arm and others . As serveo doesn't work in India.
Otherwise the script is good .

**Comment by shasankp-create** [comment]
Please reply when u r free asap!

**Comment by shasankp-create** [comment]
![Screenshot_20191119-030331](https://user-images.githubusercontent.com/56120366/69095905-4a2cec00-0a79-11ea-99db-6678b1f36d66.png)
This is the screenshot which says "append /nearyou/ to tunnel URL"

**Comment by shasankp-create** [comment]
Plus I read the readme thoroughly though but didn't understand the manual part especially of ngrok. Can u please guide me in that?

**Comment by thewhiteh4t** [comment]
@shasankp-create serveo works in india but it is down right now, instructions for manual mode are given in the readme, you have to download ngrok in termux on your own and execute it in another session and follow what seeker says in the screenshot, all this is very basic stuff and if you are not able to understand or follow these steps please stop using my tool and go for a basic linux courses, check meanings of words like append etc.

**Comment by shasankp-create** [comment]
Well I've already installed ngrok before u told me. I just want to know
exactly what I have to append in /nearyou/ . Plus it's a request that don't
be under the misconception that since I'm an Indian my English would be
poor . I am a 3 time international English Olympiad gold medalist. I know
that knowing this is literally of no use to you...but it's a request that
if u can be a bit decent next time.....
Just tell me what I have to append and how to..and I won't bother u next
time.
And I meant no indecency or disrespect . Seeker is a very good tool and
everybody should get to use it(i.e those who r interested)
Hope u understand that.
Regards
Shasankp-create


On 19 Nov 2019 3:21 am, "thewhiteh4t" <notifications@github.com> wrote:

Closed #129 <https://github.com/thewhiteh4t/seeker/issues/129>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/thewhiteh4t/seeker/issues/129?email_source=notifications&email_token=ANMFILSHCPO564B4VCDRR6LQUME5LA5CNFSM4JO2NKCKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOU5YWLRA#event-2809226692>,
or unsubscribe

**Comment by thewhiteh4t** [comment]
@shasankp-create I never commented anything about you being indian or your english, please read my previous reply again carefully and I am being decent here, seeker is not for newbies who cannot append a string after a url, and thankyou, everybody should get to use it that's why I have it here on GitHub but if you can't even append a string then I can't help you, when you run seeker in manual tunnel mode it clearly states append '/nearyou/' after tunnel url, so if you are a 3 time gold medalist you should not be having any confusions, I mean this is just simple english, I am not Shashi Tharoor. I want to help but i can't teach people how to append, this shows lack of basics and makes me wonder what you will do with this tool, i hope you are not trying to track your girlfriend etc.

**Comment by Root-star** [comment]
Lol shashi Tharoor 😆😆

**Comment by shasankp-create** [comment]
Well....I'm sorry since things r not going well for me and I took that u
were trying to insult me...can u just tell me exactly what I have to append
and where? I went to the nearyou folder and then I'm confused. What exactly
do I have to append? Moreover I did start ngrok in a separate session with
http 4025
And the seeker was running in another session. But everything seems to just
hang..... nothing happens. Ngrok status shows reconnecting and it's just
stuck there. Can u tell me that what kind of a mess I've landed in.
Moreover after I close the ngrok session ngrok says that it's home dir has
been mixed with $HOME of termux.
And something which is not implemented on linux arm yet....
What is going on exactly?.
Pls help me out.
And I'm sorry once again for misunderstanding......hope u didn't mind.....

**Comment by thewhiteh4t** [comment]
@shasankp-create there is a dns problem in ngrok which they haven't fixed till now, if you are connected to wifi try to use ngrok on 4G and if you are getting this on 4G try wifi, for me it works on 4G connection, if ngrok does not run then you can try some other similar tunnel service or wait for serveo

**Comment by shasankp-create** [comment]
Ok, I'll try on WiFi...I was getting this on 4G...
Thanks for the info...

**Comment by shasankp-create** [comment]
Btw.... Will localxpose work with seeker?

**Comment by thewhiteh4t** [comment]
I will test localxpose soon, meanwhile watch this https://www.youtube.com/watch?v=FEyAPjkJFrk

**Comment by shasankp-create** [comment]
Ok....thanks .

**Comment by sandsoncosta** [comment]
I tested LocalXpose and couldn't get it to work.
I managed to make it work with localhost.run.
However, he returns me the IP: 127.0.0.1 and not the victim's IP.
I don't know if it's because it's a free version, or if it's my fault.
If you can check it, thank you.
The ngrok is out.

**Comment by sandsoncosta** [comment]
I tested localtunnel to and it didn't work.

**Comment by thewhiteh4t** [comment]
@sandsoncosta yeah i tried `LocalXpose`, its tunnel links are not working for me, with or without seeker, both `localhost.run` and `localtunnel` worked but it is giving ip as `127.0.0.1`, it looks like they are using `akamai waf` to add security
