### ISSUE TITLE
why is prompted not linked to the Internet

### ISSUE THREAD

**Issue by secfree0yg** [thewhiteh4t/seeker#13]
Hi,
my system is kali linux 2018.03

`

> kali:~# docker run -t --rm seeker

`

 ______  ____   ____  |  | __  ____ _______
 /  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/
/____  > \___  >\___  >|__|_ \ \___  >|__|
	 \/      \/     \/      \/     \/        

[>] Created By : thewhiteh4t
[>] Version    : 1.0.4

[!] You are Not Connected to the Internet...Quiting..

**Comment by secfree0yg** [comment]
Yes, every time it takes place in the dock, if I am a Chinese on the mainland, do I have to use VPN?

**Comment by thewhiteh4t** [comment]
Yes because google is banned in china so you will have to use a vpn

**Comment by secfree0yg** [comment]
Thank you
