### ISSUE TITLE
how i use it with ngrok 

### ISSUE THREAD

**Issue by pretech86** [thewhiteh4t/seeker#130]
i try to use this commands but nothing happened

# In First Terminal Start seeker in Manual mode like this
python3 seeker.py -t manual

# In Second Terminal Start Ngrok or any other tunnel service on port 8080
./ngrok http 8080

**Comment by thewhiteh4t** [comment]
Wait for sometime, I am releasing a video for newbies, I will share the link with you here

**Comment by pretech86** [comment]
thanks alot for your interest

**Comment by thewhiteh4t** [comment]
https://www.youtube.com/watch?v=FEyAPjkJFrk

**Comment by pretech86** [comment]
THANKS it working now

**Comment by thewhiteh4t** [comment]
Closing.

**Comment by Rakavanlohee** [comment]
![IMG-20200404-WA0031](https://user-images.githubusercontent.com/63155423/78453191-b6695e80-76ad-11ea-87d9-dc4571b1b5dd.jpg)
I can't  get code in seeker

**Comment by Rakavanlohee** [comment]
How to solve this issue

**Comment by Rakavanlohee** [comment]
Please tell me

**Comment by Erneris** [comment]
> Please tell me

It's "ngrok http 8080", because ./ opens the programs in that directory.

**Comment by anonymouse-257** [comment]
The video has been deleted
