### ISSUE TITLE
Serveo Status Down

### ISSUE THREAD

**Issue by KevinTheAnonimous** [thewhiteh4t/seeker#131]
I need Help, why The Serveo is down?

**Comment by thewhiteh4t** [comment]
@KevinTheAnonimous I am not the developer of serveo, contact its developer and visit its website for more information and please take a look at my latest video for a solution : https://youtu.be/FEyAPjkJFrk

**Comment by Ednikors** [comment]
Thx for the solution. This video is really helpful

**Comment by thewhiteh4t** [comment]
closing.

**Comment by Orchard22** [comment]
Sir why this error occurs. Plz hlp me
![Uploading Screenshot_20210105-003228.jpg…]()

**Comment by thewhiteh4t** [comment]
@Orchard22 read usage instructions in README
