### ISSUE TITLE
Serveo down

### ISSUE THREAD

**Issue by ajirmdhn** [thewhiteh4t/seeker#135]
What's this?
![Screenshot_2019-12-08-06-09-44-234_com termux](https://user-images.githubusercontent.com/45916317/70381686-76090680-1981-11ea-8f3f-ba6fc6d49421.png)

**Comment by thewhiteh4t** [comment]
@ajirmdhn I think it's clear that serveo is down, check serveo website for reason and watch the demo video in readme for a solution
