### ISSUE TITLE
I can't install seeker on my parrot os

### ISSUE THREAD

**Issue by khophy12keyz** [thewhiteh4t/seeker#139]
It says (UNSTABE CLI) 
And if i execute (python3 seeker.py) , This is what pops up
                        __
  ______  ____   ____  |  | __  ____ _______
 /  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/
/____  > \___  >\___  >|__|_ \ \___  >|__|
	 \/      \/     \/      \/     \/        

[>] Created By : thewhiteh4t
[>] Version    : 1.2.1

[+] Checking for Updates.....[ Up-To-Date ]

[+] Checking Serveo Status...[ DOWN ]

**Comment by thewhiteh4t** [comment]
@khophy12keyz I will test it on parrot sec os and will revert soon, assuming you are using latest version of parrot

**Comment by thewhiteh4t** [comment]
@khophy12keyz done testing, `UNSTABLE CLI` message appears only in parrot os and not on other debian operating systems, but it's just a warning, also seeker is running fine on your parrot, serveo is down sometimes and I have provided a solution in `Demo` video in README.
