### ISSUE TITLE
 I have another problem.\ It's about user interaction.

### ISSUE THREAD

**Issue by secfree0yg** [thewhiteh4t/seeker#14]
Hi,
my system is kali linux 2018.03

> root@kali:~/seeker# docker run -t --rm seeker

                        __
  ______  ____   ____  |  | __  ____ _______
 /  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/
/____  > \___  >\___  >|__|_ \ \___  >|__|
	 \/      \/     \/      \/     \/        

[>] Created By : thewhiteh4t
[>] Version    : 1.0.4

[+] Checking Internet Connection... Working

[+] Checking For Seeker Updates... Up-to-date

[!] Starting Apache Server...

[+] Starting Ngrok...

[+] URL : https://61a13b59.ngrok.io/nearyou/

[+] Waiting for User Interaction...

 _I entered the web site with other terminals, but I still could not accept feedback messages._

**Comment by thewhiteh4t** [comment]
What do you mean you could not accept feedback messages?

**Comment by secfree0yg** [comment]
After I open the website, shouldn't I feedback the device information?

**Comment by thewhiteh4t** [comment]
Yeah after you open the website, click on Continue, at this point website will ask for your location, after you have granted the permission it will show an alert saying Thankyou and you should see device information and location in your terminal also wait for the website to load completely then click on Continue and please take a look at the demo (youtube) in Readme

**Comment by secfree0yg** [comment]
Well, thank you very much.

**Comment by secfree0yg** [comment]
Working normally.

**Comment by thewhiteh4t** [comment]
Thankyou, closing.
