### ISSUE TITLE
Found a fix for ngrok android...

### ISSUE THREAD

**Issue by shasankp-create** [thewhiteh4t/seeker#143]
Hey remember me? The guy from India.
Well after extensive research on the net I found a fix to ngrok...which is 100 percent working on my device...I tested on a few other devices too...and it works.
It's pretty simple: We have to keep on both the mobile data 3g/4g/5g and hotspot (WiFi hotspot not WiFi alone) and then ngrok status will start showing online

**Comment by shasankp-create** [comment]
Just try this...I bet this will work for users confused with ngrok_arm. :)

**Comment by thewhiteh4t** [comment]
Thanks for the input, I hope serveo is back online soon, closing

**Comment by shasankp-create** [comment]
Happy to help!
