### ISSUE TITLE
install on mac os 
404 not found

### ISSUE THREAD

**Issue by ch4iril** [thewhiteh4t/seeker#144]
install.sh (apt-get not found)
but dependenci 
php was installed
python3 was installed
ssh was installed
requests was installed

ngrok was installed

everything ok

but i will try on browser firefox and google even safari always result 404 not found

example

https://blabla.ngrok.io/nearyou/

404 not found

any advice........?

**Comment by ch4iril** [comment]
thanks for your replay  whitehat

but if i remove nearyou on my browser just display It's Work (that sign my apache is working)
nothing happen......on my mac

see my attach

<img width="696" alt="Screen Shot If i remove nearyou" src="https://user-images.githubusercontent.com/17878392/73011770-813bc700-3e47-11ea-9fbc-a9516b090fbc.png">

**Comment by ch4iril** [comment]
Get / favicon ico not found (on ngrok )

**Comment by thewhiteh4t** [comment]
@ch4iril it looks like your apache server is running on same port (8080), seeker attempts to start php server at port 8080 and ngrok forwards on that port, disable apache server and execute seeker again

**Comment by thewhiteh4t** [comment]
also take a look at `php.log` file in seeker dir

**Comment by ch4iril** [comment]
ok

**Comment by ch4iril** [comment]
i think my problem on localhost port 80

i try to test type localhost:80 unable to connect

if i not used apache Failed to complete tunnel connection

**Comment by thewhiteh4t** [comment]
@ch4iril watch my demo video in Readme, it will help

**Comment by ch4iril** [comment]
ok thanks

**Comment by ch4iril** [comment]
whitehat.... are you still there

finaly i found solution.....chardet not installing

now i fix show you create....
thanks for your kind

<img width="1135" alt="Screen Shot " src="https://user-images.githubusercontent.com/17878392/73018355-12189f80-3e54-11ea-816a-e4fb31488427.png">

**Comment by thewhiteh4t** [comment]
Great! closing.
