### ISSUE TITLE
Add whatsapp and telegram template,and other for QR

### ISSUE THREAD

**Issue by Dazmed707** [thewhiteh4t/seeker#145]
Add option that asks for location to show the QR code and after scanning the QR download a file or redirect a link

**Comment by thewhiteh4t** [comment]
Please suggest a scenario where we can ask for location before displaying the qr code, I am trying to go for legit scenarios such as the gdrive template

**Comment by Cyb3rG0D7** [comment]
whatsapp web?

**Comment by thewhiteh4t** [comment]
Yeah but the whatsapp web does not ask for location permission, a normal non techy person won't fall for this, what do you think @Cyb3rG0D7 ?

**Comment by Cyb3rG0D7** [comment]
the location would be requested if the person would like to enter a whatsapp group
after giving location permission you are redirected to the whatsapp group link

**Comment by thewhiteh4t** [comment]
@Cyb3rG0D7 check this out, there is a screenshot in this https://urlscan.io/result/6c06719f-682d-4eb5-b09e-740ac60302c7

**Comment by Cyb3rG0D7** [comment]
if that would be fine, telegram is something similar look, when you put an invitation link or to contact a user
![image](https://user-images.githubusercontent.com/35184132/73152324-8003d780-409d-11ea-9e76-86d73c7b9871.png)
seeker should have the ability to copy the name of the group or user of the photo for the fake page, or to ask for the address of the image in which directory it is and the name and create the fake page
For Facebook I used this tool that did something I did for a phishing with a fanpage, look at the tool
https://github.com/PowerScript/facebrok
----------------------------------------------------------------------------------
Watch this video of how you do it for Facebook, search engine wanted to do something similar
https://youtu.be/c2t_pco6JU4?t=307

**Comment by thewhiteh4t** [comment]
@Dazmed707 what's your twitter handle?

**Comment by Dazmed707** [comment]
twitter and telegram: @dazmed707 
fanpage: fb.com/hackerscristianos

**Comment by thewhiteh4t** [comment]
@Dazmed707 whatsapp template added, update and test

**Comment by thewhiteh4t** [comment]
@Dazmed707 credits added in readme :)

**Comment by Dazmed707** [comment]
oh¡ thanks :) <3

**Comment by bikash2424** [comment]
thewhiteh4t
Tell me what can i do , it asks for path to group image
Upload the process of whatsapp in seeker tool

**Comment by thewhiteh4t** [comment]
@bikash2424 it's simple, download the image and give its absolute path, if you don't know basics, then I can't help you

**Comment by bikash2424** [comment]
Sir i am a beginner pleas tell me throw a example how to add a path ,i use
termux in my android

**Comment by thewhiteh4t** [comment]
@bikash2424 you should pursue a basics of linux course, this tool is not for beginners, first learn basics then use this tool or any other tool

**Comment by thewhiteh4t** [comment]
@Dazmed707 telegram template added, please test, if you find any problem, create a new issue, closing.
