### ISSUE TITLE
Tunnel [ domain ].ngrok not found

### ISSUE THREAD

**Issue by moibraahim** [thewhiteh4t/seeker#146]
When i generate a URL from **ngrok** in terminal i can access to it easily from firefox on the same machine 
but when it comes to sharing the URL to my other phone or another phones it showing me **tunnel .ngrok not found** 

My OS : kali linux 
Phone i tried to access from : android 

https://imgur.com/a/B6IpNjk

**Comment by thewhiteh4t** [comment]
@moibraahim are you running virtualbox?

**Comment by thewhiteh4t** [comment]
Please take a look at this : 
https://github.com/inconshreveable/ngrok/issues/626#issuecomment-569462954

**Comment by moibraahim** [comment]
Yes , VirtualBox

**Comment by moibraahim** [comment]
so , i can not setup this tool on VirtualBox ?

**Comment by thewhiteh4t** [comment]
@moibraahim ngrok has some issues with vbox, try switching to *bridged* network mode and try again

**Comment by moibraahim** [comment]
Do you have Any idea or Tutorial on switching to bridged network mode ?

**Comment by moibraahim** [comment]
if I used VmWare the problem will be solved ?

**Comment by thewhiteh4t** [comment]
@moibraahim yeah you can try vmware workstation send me a dm on telegram if you need keys
