### ISSUE TITLE
Serveo status Down

### ISSUE THREAD

**Issue by MrDmitry1107** [thewhiteh4t/seeker#147]
![Screenshot from 2020-02-10 11-10-12](https://user-images.githubusercontent.com/54665743/74131680-ccdac880-4bdc-11ea-8108-15dd92552918.png)

**Comment by MrDmitry1107** [comment]
I have VPN

**Comment by MrDmitry1107** [comment]
there are aealogs of this utility?

**Comment by thewhiteh4t** [comment]
@MrDmitry1107 please watch the demo video, link is in the readme.

**Comment by MrDmitry1107** [comment]
@thewhiteh4t How to Install ngrok?

**Comment by thewhiteh4t** [comment]
@MrDmitry1107 visit the download section in ngrok official website, you will get a zip file with ngrok binary in it

**Comment by MrDmitry1107** [comment]
Спасибо
