### ISSUE TITLE
ngrok

### ISSUE THREAD

**Issue by IBOY66** [thewhiteh4t/seeker#148]
I'm using the Android version of termux. I've built it, but when I use ngrok, I can only give feedback when I visit it by myself. When others visit the link, they won't give feedback, sir. Ask for advice

**Comment by thewhiteh4t** [comment]
@IBOY66 please share error

**Comment by IBOY66** [comment]
I don't know how to describe it, that is, when other people visit the link, they will not get other people's information. When their terminal accesses the link, they will get their own information. Don't you say that they can get other people's location? I think it may be the problem of ngrok. I don't think I have much limitation in China. I saw that they all took Kail on youtube, but I took termux. He didn't give much feedback on the error information. Now I will send you the screenshot
![Screenshot_2020-02-19-11-35-14-684_com termux](https://user-images.githubusercontent.com/50222252/74799641-09f53800-530c-11ea-9104-5d2c5bbd79aa.jpg)

**Comment by thewhiteh4t** [comment]
@IBOY66 okay so there are no errors in seeker, if you open the ngrok link on your phone you get the information but if you send that link to someone else then you are not getting any data right?

can other people see the nearyou page? or they get some error in their browser?

**Comment by IBOY66** [comment]
Yes, can you solve the problem and help me? Thank you

**Comment by thewhiteh4t** [comment]
@IBOY66 you did not answer my questions, read my comment above and answer all questions

**Comment by IBOY66** [comment]
Other people can visit normally, just as I visited myself, that is, there is no feedback when others visit

**Comment by thewhiteh4t** [comment]
@IBOY66 if they will not click on the `continue` button there will be no feedback, are you sure they are clicking it? 
If they are clicking it do they get a `coming soon` message?

**Comment by IBOY66** [comment]
Yes, a window will pop up. Here are 2 screenshots of me to share
![Screenshot_2020-02-19-13-37-03-457_com miui notes](https://user-images.githubusercontent.com/50222252/74805368-d15e5a00-531d-11ea-8ed6-76ac6db313a3.jpg)
![Screenshot_2020-02-19-13-37-38-165_com miui notes](https://user-images.githubusercontent.com/50222252/74805373-d7ecd180-531d-11ea-803f-44c8a0108a3e.jpg)

**Comment by thewhiteh4t** [comment]
@IBOY66 inside seeker dir you will find a folder named `logs` inside you will find `php.log` please share the contents

**Comment by IBOY66** [comment]
I don't understand. Look at this picture
![Screenshot_2020-02-19-13-52-16-587_com termux](https://user-images.githubusercontent.com/50222252/74805800-35355280-531f-11ea-9a22-795200b48e83.jpg)

**Comment by thewhiteh4t** [comment]
@IBOY66 
`cd logs`
`cat php.log`
Send screenshot after executing these commands

**Comment by IBOY66** [comment]
OK!
![Screenshot_2020-02-19-14-06-15-058_com termux](https://user-images.githubusercontent.com/50222252/74806479-061fe080-5321-11ea-9fd3-f114b001e79d.jpg)

**Comment by IBOY66** [comment]
ok,can you help me?

**Comment by thewhiteh4t** [comment]
@IBOY66 send a screenshot of the browser with the link open, I am trying to help you

**Comment by IBOY66** [comment]
I know the reason. I belong to the mainland of China. You know that Google, youtube, etc. in China are blocked by GFW. I can receive feedback if I break through GFW, but I can't receive it if I don't break through GFW. Now how can I make normal feedback for devices that haven't broken through GFW?

**Comment by IBOY66** [comment]
If we don't break the GFW limit, the web page can't display comprehensively, but there are some windows, but sometimes it can display comprehensively, but still can't feed back information

**Comment by IBOY66** [comment]
I'm sorry. Delay your time!

**Comment by thewhiteh4t** [comment]
@IBOY66 if it's GFW then unfortunately ngrok may not work, I read similar issues on ngrok github issues but maybe this will work : https://github.com/inlets/inlets
its like ngrok and maybe it can work

**Comment by IBOY66** [comment]
Is there a solution

**Comment by thewhiteh4t** [comment]
try inlets

**Comment by IBOY66** [comment]
I need a detailed plan, thank you

**Comment by thewhiteh4t** [comment]
@IBOY66 i can only suggest ngrok alternative which I did above, I can't give you step by step instructions, you have to do that on your own and if you can't do that then please pursue linux basics courses and then use any tool

**Comment by IBOY66** [comment]
OK, what is the idea and what is the replacement

**Comment by thewhiteh4t** [comment]
@IBOY66 idea and replacement : https://github.com/inlets/inlets

**Comment by thewhiteh4t** [comment]
You can also use https://packetriot.com/

**Comment by IBOY66** [comment]
I have a look. It seems that all of them are supported Linux systems. They don't support termux, right?

**Comment by thewhiteh4t** [comment]
@IBOY66 both inlets and packetriot have arm64 releases which should work in termux

**Comment by IBOY66** [comment]
I have read some documents, but they all say that they want to map to the public IP network. Do you want to create your own domain name on VPS? Instead of automatically generating like ngrok?
