### ISSUE TITLE
Addition of keylogger

### ISSUE THREAD

**Issue by MrDmitry1107** [thewhiteh4t/seeker#151]
Хай а можно ли на seeker добавить кейлогер и возможность копирования сайта или добавление своего html кода.

**Comment by thewhiteh4t** [comment]
@MrDmitry1107 sorry can you please converse in english?

**Comment by MrDmitry1107** [comment]
@thewhiteh4t Hi, is it possible to add a keylogger and the ability to copy a site or add your own html code on seeker?

**Comment by thewhiteh4t** [comment]
@MrDmitry1107 I can look into keylogger implementation, automatic site cloning is not impossible but challenging and I have plans for it so it might get added in future, meanwhile you can add your own custom site, take a look at js and php files for reference

**Comment by MrDmitry1107** [comment]
in fact, you can use the site copy service(https://xdan.ru/copysite/) and  embed HTML code

**Comment by thewhiteh4t** [comment]
@MrDmitry1107 thanks for the reference but cloning is a simple process and if the target is to phish the credentials then you have to inject code in the form but for location things are different it will have to be an automatic pop up instead of a button like in `NearYou` , right now I am working on `FinalRecon` I will update seeker soon

**Comment by MrDmitry1107** [comment]
I will wait Thanks

**Comment by thewhiteh4t** [comment]
We will close the issue when keylogger is added :)

**Comment by MrDmitry1107** [comment]
@thewhiteh4t sory ¯\_(ツ)_/¯

**Comment by thewhiteh4t** [comment]
@MrDmitry1107 hahaha no problems

**Comment by MrDmitry1107** [comment]
@thewhiteh4t but what if you ask people who download seeker themselves to add these buttons to the html code that they copied?

**Comment by thewhiteh4t** [comment]
@MrDmitry1107 ideally they should, but many people don't have basic knowledge and they directly jump to tools

**Comment by MrDmitry1107** [comment]
@thewhiteh4t in fact, Lamer if he wants to do what he wanted he will do.

**Comment by alpeshmali** [comment]
hello when user open link in google chrome automatically deny location service and give error please refresh your page and try again even if user give permission (allow) plz give me solution

**Comment by thewhiteh4t** [comment]
@alpeshmali problem is with google chrome and not with seeker, if you test it on firefox it works also read me comment here regarding this problem https://github.com/thewhiteh4t/seeker/issues/173#issuecomment-613856711

**Comment by thewhiteh4t** [comment]
On second thoughts, there is no point of adding a keylogger as the we are after the GPS coordinates, and keylogging stops as soon as the tab or browser is closed or minimized, its not effective in seeker.
