### ISSUE TITLE
FAILED TO START PHP SERVER

### ISSUE THREAD

**Issue by DesuX-kun** [thewhiteh4t/seeker#157]
![Screenshot_2020-03-23-23-18-32-47_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/62561046/77338458-fc90fa80-6d5c-11ea-8cce-bda113720dfb.png)

Failed To Start PHP Server
I don't know what happen pls fix This

**Comment by thewhiteh4t** [comment]
@DesuX-kun Inside seeker dir, you will see a `logs` folder, inside there should be a php log file, please share

**Comment by DesuX-kun** [comment]
> @DesuX-kun Inside seeker dir, you will see a `logs` folder, inside there should be a php log file, please share


#
[php.log](https://github.com/thewhiteh4t/seeker/files/4370643/php.log)

**Comment by DesuX-kun** [comment]
I seeee maybe my php is not updated

**Comment by thewhiteh4t** [comment]
@DesuX-kun yes try to update it, or you can try that `libicu` method too

**Comment by DesuX-kun** [comment]
> @DesuX-kun yes try to update it, or you can try that `libicu` method too

LOL RIGHT WHY I JUST DONT READ THE LOG.Thanks for you help :)

**Comment by thewhiteh4t** [comment]
@DesuX-kun hahaha yes, working now?

**Comment by DesuX-kun** [comment]
> @DesuX-kun hahaha yes, working now?

Off course its working haha gonna start ngrok tunnel

**Comment by thewhiteh4t** [comment]
Great! , closing.

**Comment by Anonym962** [comment]
Hi i have the same problem but i dont know how to update php? im new in this hacking stuff

**Comment by Naresh-11** [comment]
![Screenshot_2022-08-09-21-47-33-256_com termux](https://user-images.githubusercontent.com/67682213/183701652-f8bb0510-34ad-4aed-95e5-6e7202709748.jpg)
Please help me i will update php but it is not working

**Comment by thewhiteh4t** [comment]
@Naresh-11 share php log

**Comment by Naresh-11** [comment]
How to share php logo am new

**Comment by Naresh-11** [comment]
> @Naresh-11 share php log

[Tue Aug  9 21:47:20 2022] PHP 8.1.6 Development Server (http://0.0.0.0:8080) started

**Comment by thewhiteh4t** [comment]
@Naresh-11 share the complete log

**Comment by Naresh-11** [comment]
> @Naresh-11 share the complete log

![Screenshot_2022-08-09-22-13-47-567_com termux](https://user-images.githubusercontent.com/67682213/183706763-17ccf78a-831c-4b6f-832a-a6373ce27f3f.jpg)

**Comment by Naresh-11** [comment]
Here was my complete logs. Reply please
  Today i will install this tool

**Comment by thewhiteh4t** [comment]
it looks like the server is crashing, completely close termux and then retry

**Comment by Naresh-11** [comment]
> it looks like the server is crashing, completely close termux and then retry

![Screenshot_2022-08-09-22-36-51-323_com termux](https://user-images.githubusercontent.com/67682213/183710980-076cd428-a540-46d5-b28f-f9f5fb9085c0.jpg)
Same issue

**Comment by Sumitbelkar** [comment]
I am getting traceback problem again and again
What I can do sir??
Please help me
![Screenshot_2023-01-22-19-44-59-11_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/105590152/213920414-c4b3c056-8be4-41db-85f8-9b2c35b46e53.jpg)

**Comment by thewhiteh4t** [comment]
@Sumitbelkar `pip3 install --upgrade urllib3`

**Comment by Sumitbelkar** [comment]
> 

Thanks a lot sir 😊👍👍
You are great

**Comment by baldwin-cyber** [comment]
![Image](https://github.com/user-attachments/assets/3694f019-c433-44c7-9f39-73e38a1288db)
Hocam bendede aynı sorun var yardımcı olun lütfen

**Comment by thewhiteh4t** [comment]
@baldwin-cyber inside the seeker directory look for `logs` directory, check `php.log` file for any errors

**Comment by baldwin-cyber** [comment]
@thewhiteh4t o diziyi nasıl çalıştıracağımı bilmiyorum

**Comment by baldwin-cyber** [comment]
@thewhiteh4t nasıl arayacağım o kodu bilmiyorum

**Comment by ihavenocluelol** [comment]
got the same problem
these are the php logs

Fri Jan  9 22:06:55 2026 (31823): Error Cannot create lock - Permission denied (13)

**Comment by thewhiteh4t** [comment]
@ihavenocluelol did you install termux from play store? if yes then try installing from fdroid, also make sure that you have enabled access to files for termux in android settings.

**Comment by ihavenocluelol** [comment]
@thewhiteh4t could you send me the fdroid link?Thanks a lot
