### ISSUE TITLE
Change the 8080 port

### ISSUE THREAD

**Issue by murad-alm** [thewhiteh4t/seeker#158]
Hello,
can i change the default 8080 port (in manual mode with ngrok)?

Thanks!

**Comment by thewhiteh4t** [comment]
@murad-alm no as of right now but that's a good suggestion, I will add this functionality soon

**Comment by murad-alm** [comment]
@thewhiteh4t Thanks for the response! I hope to see this feature soon! It would be really great to customize the connection-port!

Cheers!

**Comment by thewhiteh4t** [comment]
@murad-alm added in v1.2.2, please update, closing.

**Comment by murad-alm** [comment]
Great! Thanks!
