### ISSUE TITLE
Has independent IP, how to set up does not require a proxy

### ISSUE THREAD

**Issue by cx-reboot** [thewhiteh4t/seeker#159]
My server has an independent ip, how can I choose not to use ngrok. Or I want to use it in a local area network.

**Comment by thewhiteh4t** [comment]
@cx-reboot you need ssl, ngrok, serveo etc provide ssl, without ssl, as per html api site does not ask for location permission and if it doesn't ask we will not get it and that's not what we want

**Comment by cx-reboot** [comment]
okok，But our country has blocked the ngrok servo, so I need to find alternatives where I can provide SSL services.

**Comment by thewhiteh4t** [comment]
You can try packetriot, I guess your query is resolved now so I am closing now.
