### ISSUE TITLE
starting php server failed

### ISSUE THREAD

**Issue by gurugrover** [thewhiteh4t/seeker#162]
When i type command 
python3 seeker.py -t manual
Then chose near you
Then it says 
starting php server failed
![Screenshot_20200327_092409](https://user-images.githubusercontent.com/60204410/77720062-d6918180-700c-11ea-85ad-52b2bb4e1bab.jpg)

**Comment by thewhiteh4t** [comment]
Take a look at this https://github.com/thewhiteh4t/seeker/issues/157

**Comment by gurugrover** [comment]
Can't understand what to do 
Please explain in detail

**Comment by thewhiteh4t** [comment]
I have clearly mentioned what to do to find the problem in that issue above, if you are not able to understand such basic stuff then clearly you need to pursue a linux basics course from cybrary or coursera etc, no offense.

**Comment by gurugrover** [comment]
Please help
Give me code to fix it

**Comment by thewhiteh4t** [comment]
You need to study basics first, use tools after you are done with that, closing.

**Comment by gurugrover** [comment]
Give me code to fix this
