### ISSUE TITLE
Error while updating

### ISSUE THREAD

**Issue by ScryE778** [thewhiteh4t/seeker#166]
When i type:
sudo python3 ./seeker.py -t manual   OR
python3 ./seeker.py -t manual
I got this:
![изображение_viber_2020-04-03_16-50-01](https://user-images.githubusercontent.com/55192460/78373938-847fcb80-75cb-11ea-8461-25b031ccf71a.jpg)
![изображение_viber_2020-04-03_16-50-02](https://user-images.githubusercontent.com/55192460/78373946-877abc00-75cb-11ea-8659-e645d8311c67.jpg)

**Comment by thewhiteh4t** [comment]
@ScryE778 when you are typing `python` or `python3` you don't need to put `./` before seeker.py, command should be `python3 seeker.py` followed by arguments, when you use `./` script automatically chooses python in that case you dont put python3 and command will be `./seeker.py` followed by arguments, now let's talk about the error, when it checks for updates it contacts github, for some reason the certificate cannot be verified, can you open github in browser normally without any certificate errors?

**Comment by ScryE778** [comment]
But i got the same error if i set ./seeker.py -t manual or python3 -t manual

**Comment by Rakavanlohee** [comment]
![IMG-20200404-WA0031](https://user-images.githubusercontent.com/63155423/78453394-0bf23b00-76af-11ea-87c2-b49af78572ac.jpg)
**### How to fix this problem**

**Comment by Rakavanlohee** [comment]
Please tell  me

**Comment by Rakavanlohee** [comment]
Please help me

**Comment by Rakavanlohee** [comment]
![Screenshot_2020-04-04-20-03-14-1](https://user-images.githubusercontent.com/63155423/78453459-75724980-76af-11ea-86ad-b45b1daf2dde.png)

**Comment by Rakavanlohee** [comment]
That is can't working

**Comment by Rakavanlohee** [comment]
How to fix

**Comment by ScryE778** [comment]
Maybe that can help you
https://stackoverflow.com/questions/30188582/ngrok-command-not-found#36759493

**Comment by Rakavanlohee** [comment]
I use termux

**Comment by thewhiteh4t** [comment]
@ScryE778 check your dns settings please, if you are able to open github in browser then something is creating a problem in cli

**Comment by ScryE778** [comment]
I got the same problem for other tool. The owner said me that i need to disable all updates in the python file, something like "updating=False"

**Comment by thewhiteh4t** [comment]
@ScryE778 check your hosts file, did you perform anything like dnsspoof in the past? share the output of `nslookup github.com` something goes wrong if you access github from tools

**Comment by ScryE778** [comment]
But i can git clone from github, so problem is not here. How github is linked my problem?

**Comment by thewhiteh4t** [comment]
@ScryE778 the error you are getting is in the update function of seeker. update function sends request to github, that's why github is linked to your problem, I am not getting this error when I use seeker, so we have one difference, our network config, something is causing the SSL certificate verification to fail on your end

**Comment by ScryE778** [comment]
Thanks for the answer.
output of nslookup github.com:
Server: 109.88.203.3
Address: 109.88.203.3#53
Non-authoritative answer:
Name: github.com
Address: 140.82.118.3

**Comment by thewhiteh4t** [comment]
@ScryE778 try changing your dns server, I guess you are using your isp dns, here are my results : 
```
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
Name:	github.com
Address: 13.234.176.102
```

**Comment by thewhiteh4t** [comment]
@ScryE778 yes there it is, if i visit the IP address in your nslookup, there is a cert failure, this should not happen

**Comment by ScryE778** [comment]
What i need to put instead i have right now?

**Comment by thewhiteh4t** [comment]
@ScryE778 no wait there is some other issue, if I do nslookup and try to open that IP I am also getting ssl error, but if I perform nslookup on google.com then there are no ssl errors, its some issue on githubs part I guess, but I am not sure why you are getting ssl verification failure and not me when we both are getting this issue in nslookup

**Comment by thewhiteh4t** [comment]
@ScryE778 please share the output of `python3 -c "import requests; print(requests.__version__)"`

**Comment by ScryE778** [comment]
2.22.0

**Comment by thewhiteh4t** [comment]
@ScryE778 you are on an older version of requests, execute this command:
`pip3 install requests --upgrade`

**Comment by ScryE778** [comment]
I upgraded, but that dont work

**Comment by thewhiteh4t** [comment]
@ScryE778 try this then : 
open seeker.py in a text editor which can display line numbers, goto line 49
`ver_rqst = requests.get(ver_url)`
modify it like this
`	ver_rqst = requests.get(ver_url, verify=False)`
save the file and launch seeker

**Comment by ScryE778** [comment]
"Checking for Updates ..... [ Up-To-Date ]
Checking Serveo Status ... [ DOWN ]"
And then he exit the programm

**Comment by thewhiteh4t** [comment]
@ScryE778 watch the demo, link is in readme

**Comment by thewhiteh4t** [comment]
@ScryE778 please update I have added exception handling for version checking

**Comment by ScryE778** [comment]
Yes, all works. Thank you a lot for your help. Thanks for the fasts answers. You are a good person. Thank you very much

**Comment by thewhiteh4t** [comment]
@ScryE778 thank you for your kind words :) closing.
