### ISSUE TITLE
Fix the  ./ngrok http 8080 problem

### ISSUE THREAD

**Issue by Rakavanlohee** [thewhiteh4t/seeker#167]
![IMG-20200404-WA0031](https://user-images.githubusercontent.com/63155423/78453780-95a30800-76b1-11ea-9730-a7e288107ac8.jpg)

**Comment by Rakavanlohee** [comment]
How to fix it

**Comment by Rakavanlohee** [comment]
Please help me

**Comment by Rakavanlohee** [comment]
Please .......

**Comment by thewhiteh4t** [comment]
@Rakavanlohee first of all don't spam, I will reply when I can, second, you need to download ngrok for android and use it in termux, lot of tutorials are available for it, ngrok is a seperate tool and is not a part of seeker, closing.

**Comment by Rakavanlohee** [comment]
How to fix that problems
