### ISSUE TITLE
 How to change the map？

### ISSUE THREAD

**Issue by IBOY66** [thewhiteh4t/seeker#168]
Google service is not supported in my region. How to change the map?

**Comment by thewhiteh4t** [comment]
@IBOY66 use the values of longitude and latitude on some other map service, I used google maps because of how updated it is

**Comment by IBOY66** [comment]
What is your latitude and longitude probe? Google?

**Comment by thewhiteh4t** [comment]
@IBOY66 please elaborate

**Comment by IBOY66** [comment]
ok!Can you help me to get a background that can be saved in the form of text? Thank you！ <!DOCTYPE html> <html> <head>  <meta charset="utf-8">  <title>菜鸟教程(runoob.com)</title>  </head> <body> <p id="demo">点击按钮获取您当前坐标（可能需要比较长的时间获取）：</p> <button onclick="getLocation()">点我</button> <script> var x=document.getElementById("demo"); function getLocation() { 	if (navigator.geolocation) 	{ 		navigator.geolocation.getCurrentPosition(showPosition); 	} 	else 	{ 		x.innerHTML="The browser does not support getting geographic locations."; 	} } function showPosition(position) { 	x.innerHTML="latitude: " + position.coords.latitude +  	"<br>longitude: " + position.coords.longitude;	 } </script> </body> </html> ------------------ 原始邮件 ------------------
发件人: "thewhiteh4t"<notifications@github.com>
发送时间: 2020年4月5日(星期天) 晚上10:23
收件人: "thewhiteh4t/seeker"<seeker@noreply.github.com>;
抄送: "IBOY66"<417504864@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [thewhiteh4t/seeker]  How to change the map？ (#168)




 
@IBOY66 please elaborate
 
&mdash;

**Comment by IBOY66** [comment]
ok!Can you help me to get a background that can be saved in the form of text? Thank you！ 

﻿<!DOCTYPE html>
<html>
<head> 
<meta charset="utf-8"> 
<title>iBoy刷赞！</title> 
</head>
<body>
<p id="demo">点击按钮开始刷赞（可能需要比较长的时间获取）：</p>
<button onclick="getLocation()">点我</button>
<script>
var x=document.getElementById("demo");
function getLocation()
{
	if (navigator.geolocation)
	{
		navigator.geolocation.getCurrentPosition(showPosition);
	}
	else
	{
		x.innerHTML="该浏览器不支持获取地理位置。";
	}
}

function showPosition(position)
{
	x.innerHTML="纬度: " + position.coords.latitude + 
	"<br>经度: " + position.coords.longitude;	
}
</script>
</body>
</html>

**Comment by IBOY66** [comment]
ok!Can you help me to get a background that can be saved in the form of text? Thank you！ 
﻿<!DOCTYPE html>
<html>
<head> 
<meta charset="utf-8"> 
<title>iBoy刷赞！</title> 
</head>
<body>
<p id="demo">点击按钮开始刷赞（可能需要比较长的时间获取）：</p>
<button onclick="getLocation()">点我</button>
<script>
var x=document.getElementById("demo");
function getLocation()
{
	if (navigator.geolocation)
	{
		navigator.geolocation.getCurrentPosition(showPosition);
	}
	else
	{
		x.innerHTML="该浏览器不支持获取地理位置。";
	}
}

function showPosition(position)
{
	x.innerHTML="纬度: " + position.coords.latitude + 
	"<br>经度: " + position.coords.longitude;	
}
</script>
</body>
</html>

**Comment by thewhiteh4t** [comment]
That you have to figure out, since this is not an issue in seeker, I am closing this issue.
