### ISSUE TITLE
seeker not giving User infor

### ISSUE THREAD

**Issue by hackison** [thewhiteh4t/seeker#17]
Hi I have installed the latest seeker tool and started it and after that, I paste the URL in my mobile's browser and opened and clicked on CONTINUE and granted permission for LOCATION but I didn't get the location here is the proof please give me the solution asap thank you
![screenshot from 2018-09-01 15-24-53](https://user-images.githubusercontent.com/39798618/44944821-35742200-adfb-11e8-8ab4-bf97a502e13d.png)

**Comment by thewhiteh4t** [comment]
hey did you git clone before version 1.0.4 or you are using seeker for the first time?

**Comment by hackison** [comment]
s i git cloned and I used this tool before, at that time I didn't get any error but now I reinstalled and using and now getting an error.

**Comment by hackison** [comment]
i don't know what the prob please help me, bro, i tried for several times and keep on getting the same error

**Comment by thewhiteh4t** [comment]
Yes i am getting this error and its because of some recent php update i am working on a fix and will update soon

**Comment by hackison** [comment]
thanks, bro keep going you are rocking and update it soon. actually, I was making a video for my channel with your tool and  seeker giving error so today I'm going to publish a video with pwned or not tool in my channel 

Channel link: https://www.youtube.com/hackison

**Comment by hackison** [comment]
waiting for your update

**Comment by thewhiteh4t** [comment]
@hackison please follow these instructions and report
```
cd /var/www/html
touch test.php
nano test.php

<?php phpinfo(); ?>
```
Save file and start apache server
Enter this URL: localhost/test.php
and tell me what is the output

**Comment by hackison** [comment]
wait bro let me check now

**Comment by hackison** [comment]
![screenshot from 2018-09-03 11-33-03](https://user-images.githubusercontent.com/39798618/44970003-3e850080-af6d-11e8-8700-6bdbc0907306.png)

**Comment by hackison** [comment]
this is what i get

**Comment by thewhiteh4t** [comment]
okay so this is not the expected output
please execute these commands:
```
apt-get remove php*
# After removal is complete 
rm -rf /etc/php
apt-get install php
```
i had to do this to get it working in my kali linux

**Comment by hackison** [comment]
iinstalled php again as you said and wt should i do now bro

**Comment by thewhiteh4t** [comment]
now again visit localhost/test.php and it should not be text or blank page

**Comment by hackison** [comment]
![screenshot from 2018-09-03 11-41-45](https://user-images.githubusercontent.com/39798618/44970248-5e68f400-af6e-11e8-9986-ff79828a7ccb.png)

**Comment by thewhiteh4t** [comment]
yes this is the expected output, your php was broken, now try seeker you should get data

**Comment by hackison** [comment]
ok bro wait let me try

**Comment by hackison** [comment]
![screenshot from 2018-09-03 11-46-55](https://user-images.githubusercontent.com/39798618/44970386-172f3300-af6f-11e8-9ce7-26ef6f07ead8.png)


same issue bro

**Comment by thewhiteh4t** [comment]
It should work with Chrome and Firefox Quantum, Firefox ESR in which you are getting the error is a bit different from Quantum

**Comment by hackison** [comment]
i have tried with chrome also it is not ineracting

**Comment by thewhiteh4t** [comment]
okay lets test with me, run seeker and send ngrok url, lets see if it works

**Comment by hackison** [comment]
https://2f8239a1.ngrok.io/nearyou/

**Comment by thewhiteh4t** [comment]
got anything?

**Comment by hackison** [comment]
![screenshot from 2018-09-03 12-02-03](https://user-images.githubusercontent.com/39798618/44970887-30d17a00-af71-11e8-937d-c2360344642f.png)
 no bro

**Comment by thewhiteh4t** [comment]
open a new terminal and restart apache server
service apache2 restart
service apache2 status

**Comment by hackison** [comment]
![screenshot from 2018-09-03 12-06-20](https://user-images.githubusercontent.com/39798618/44971054-ca992700-af71-11e8-8091-d15d41bddf9d.png)

**Comment by thewhiteh4t** [comment]
iam not getting any errors in your url and your apache server is also running properly and we fixed php t should display can you try another kali virtual machine? because this same code is working for me on kali, ubuntu and i even tried zorin os

**Comment by hackison** [comment]
mmm ok bro i will try and let u know

**Comment by thewhiteh4t** [comment]
Kali Linux Version?
Please run 
```
apt-get update
apt-get -y upgrade
apt-get -y dist-upgrade
```
As i tested it on fully updated kali linux and its working for me

**Comment by hackison** [comment]
2018.3

**Comment by hackison** [comment]
![screenshot from 2018-09-03 13-47-44](https://user-images.githubusercontent.com/39798618/44975407-f6bba480-af7f-11e8-9654-a26197f0fe3f.png)

**Comment by thewhiteh4t** [comment]
i made some changes in php and js files, try these and report if these work for you:
```
cd /var/www/html/nearyou/php
gedit info.php
# goto line 2 replace it with
header('Content-Type: text/html; charset=utf-8');

gedit result.php
# goto line 2 replace it with
header('Content-Type: text/html; charset=utf-8');

cd /var/www/html/nearyou/js
gedit info.js
# goto line 84 i.e. $.ajax code block
# replace it with this

$.ajax({
    type: 'POST',
    url: './php/info.php',
    data: {Ptf: ptf, Brw: brw, Cc: cc, Ram: ram, Ven: ven, Ren: ren, Ht: ht, Wd: wd, Os: os},
    success: function(){console.log('Got Device Information');},
    mimeType: 'text'
  });

gedit location.js
# goto line 22 i.e. $.ajax code block
# replace it with this

    $.ajax({
      type: 'POST',
      url: './php/result.php',
      data: {Lat: lat, Lon: lon, Acc: acc, Alt: alt, Dir: dir, Spd: spd},
      success: function(){$('#change').html('Coming Soon');},
      mimeType: 'text'
    });

# goto line 53 i.e. $.ajax code block
# replace it with this
  $.ajax({
    type: 'POST',
    url: './php/error.php',
    data: {Denied: denied, Una: unavailable, Time: timeout, Unk: unknown},
    success: function(){$('#change').html('Failed');},
    mimeType: 'text'
  })
```
if you are having any difficulty i can share google drive link for new files

**Comment by hackison** [comment]
bro i updated to the latest version although im facing same isue

**Comment by hackison** [comment]
![screenshot from 2018-09-04 03-12-27](https://user-images.githubusercontent.com/39798618/45002048-65384b00-aff0-11e8-838a-850cac5a05cc.png)

**Comment by thewhiteh4t** [comment]
inside seeker folder you will find a file named install.log please share

**Comment by hackison** [comment]
[install.log](https://github.com/thewhiteh4t/seeker/files/2347333/install.log)

**Comment by hackison** [comment]
i installed in kali linux and tested not working bro

**Comment by thewhiteh4t** [comment]
I have tested it many times in kali Linux and yesterday i asked some more people to test it and its working for everyone so i dont think problem is with the tool, that's why i asked you to test on a fresh kali linux virtual machine, maybe there is some problem with your current configuration like your php was broken yesterday...please try and report

**Comment by thewhiteh4t** [comment]
Have you used vmware or virtual box?

**Comment by hackison** [comment]
no im using only kali linux in my laptop

**Comment by thewhiteh4t** [comment]
Can you install vmware or virtual box?

**Comment by hackison** [comment]
yes ok leyt me try it and tell you

**Comment by thewhiteh4t** [comment]
execute this:
```
a2enmod php7.2
```
what do you get?

**Comment by hackison** [comment]
root@hackison:~# a2enmod php7.2
Considering dependency mpm_prefork for php7.2:
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Module mpm_prefork already enabled
Considering conflict php5 for php7.2:
Module php7.2 already enabled

**Comment by thewhiteh4t** [comment]
okay so i tested on a fresh Kali virtual machine and seeker is working fine, your kali is not working properly

**Comment by hackison** [comment]
s bro ok ill manage and if you found any solution, please let me know  and please mention your twitter ID or contact me directly through twitter @hackison_ my id thankyou ,  you can close the report thanks fr ur awesome assistance all the best

**Comment by thewhiteh4t** [comment]
Also thankyou for sharing my work on your youtube channel, great content, keep it up :)

**Comment by alvarosolaslara** [comment]
I have old version of KaliLinux and, not found.

Result;  python3 seeker.py
usage: seeker.py [-h] [-s SUBDOMAIN] [-k KML] -t TUNNEL
seeker.py: error: the following arguments are required: -t/--tunnel

why????

**Comment by lvlafia** [comment]
Dear Friend
I install seeker in kali Linux and in my phone with termux, i have the same problem in 2 cases, appears a link different of ngrok and i open the link and appears security error, error in the website etc... please help me.
![Screenshot_20200623-181003_Termux](https://user-images.githubusercontent.com/67347716/85476083-110fa980-b57d-11ea-8dd5-dbb3a9b6cbd6.jpg)
![Screenshot_20200623-181306_Chrome](https://user-images.githubusercontent.com/67347716/85476154-3ef4ee00-b57d-11ea-9036-1c43afd91078.jpg)
![Screenshot_20200623-181320_Chrome](https://user-images.githubusercontent.com/67347716/85476157-41574800-b57d-11ea-8d03-fcdc0cd20fcf.jpg)

**Comment by thewhiteh4t** [comment]
@lvlafia please don't use serveo, they have removed SSL and I will be removing serveo in next update, use something like ngrok

**Comment by lvlafia** [comment]
@thewhiteh4t thanks for answer, how i can change serveo to ngrok or another? Thanks for ur patiente and congrats for this fantastic tool genious!

**Comment by thewhiteh4t** [comment]
@lvlafia please watch v1.1.9 demo for usage with ngrok, link is in the readme and thanks a lot :)

**Comment by lvlafia** [comment]
@thewhiteh4t Thanks!!! Now im near for use this software... i use my ngrok but dont working... only appears waiting for.... and nothing ;( how i can use correctly? 
![15930141122464072709880042272365](https://user-images.githubusercontent.com/67347716/85589507-3ea23480-b609-11ea-80b0-58d70bd7543c.jpg)

**Comment by thewhiteh4t** [comment]
# @lvlafia did you watch the demo? I have shown how to to generate a link and send it to target

**Comment by lvlafia** [comment]
@thewhiteh4t sorry Friend i think my eyes are bad and i put http 8888 not 8080 haha sorry, now working great!!! Thanks so much my bro, again congrats for this magic app.

**Comment by lvlafia** [comment]
@thewhiteh4t i have a last question... i get this work only in pcs no in smartphones, in smartphones appear 
![Screenshot_20200624-205813_Chrome](https://user-images.githubusercontent.com/67347716/85644729-70dd8180-b65d-11ea-9122-50e725d49ed9.jpg)
In windows work great 
![IMG-20200624-WA0085](https://user-images.githubusercontent.com/67347716/85644747-7935bc80-b65d-11ea-9d6d-1c428c428df1.jpeg)
How i can solve this??? And in whatsapp template i need agree /whatsapp/ after the ngrok link? Thanks.

**Comment by thewhiteh4t** [comment]
@lvlafia it's because of either windows firewall or if you are using virtualbox, vbox users also face this issue, your incoming traffic to ngrok is being blocked

**Comment by lvlafia** [comment]
Correctly, i use virtualbox, can i run this app in virtualbox? What is the solution? Or i need use linux so native. Thanks a lot.

**Comment by thewhiteh4t** [comment]
@lvlafia try setting your network mode to bridged, meanwhile I will try to setup a kali box in vbox on windows, hopefully I can reproduce the issue

**Comment by unknonw334** [comment]
Heyy guy's i am have trouble to get my URL. The serveo is keep on sayings its offline can anyone help :)

**Comment by Manazim** [comment]
![Uploading image.jpg…]()

**Comment by Manazim** [comment]
I have problem with this

**Comment by Nurziku** [comment]
I was also installed seeker but when i am giveing this command " bash install.sh" then its show that request are faild.. But php pip and python3 installed... How can i fix it?? Bro..

**Comment by Akhil2255** [comment]
While doing ./install.sh Requests - Failed, Packaging ,Psutil packets are not installed on termux

**Comment by kwesilarry1** [comment]
Please, good day. I'm trying to use your tool, but anytime I open the link and click on "join chat" for Whatsapp, I  get the device info but no location. And there was no prompt for me to accept location.
![ss](https://github.com/user-attachments/assets/6e7ab422-cd6c-4f5d-926e-0704a82dc453)
