### ISSUE TITLE
ngrok issue

### ISSUE THREAD

**Issue by Minhajul788** [thewhiteh4t/seeker#170]
while I tried to open the second terminal in ngrok always I'm facing the same issue WARN[04-08|18:20:58] failed to get home directory, using $HOME instead err="user: Current not implemented on linux/arm" $HOME=/data/data/com.termux/files/home
Authtoken saved to configuration file: /data/data/com.termux/files/home/.ngrok2/ngrok.yml
$
![Screenshot_20200408_235354](https://user-images.githubusercontent.com/60433952/78820228-0ff6c380-79f5-11ea-8d79-bd141a095fa3.jpg)
![Screenshot_20200409_000209_com termux](https://user-images.githubusercontent.com/60433952/78820481-83003a00-79f5-11ea-9081-d14f53f23cde.jpg)

**Comment by thewhiteh4t** [comment]
Please take a look at https://github.com/thewhiteh4t/seeker/issues/143
Since this is not an issue with seeker and ngrok is not a part of this tool I am closing this issue, for further assistance related to external tools like ngrok, consult in their repository.

**Comment by Sakibbhai1** [comment]
![Screenshot_20220904-214746](https://user-images.githubusercontent.com/112647325/188322492-e537a5ac-55cc-4968-ab2e-d434163a528a.png)
Oww my god I'm so tried please help me !
Send me real command 😓😥

**Comment by Sakibbhai1** [comment]
I need a help

**Comment by RobertNissan** [comment]
apt update -y;apt upgrade -y;pkg install wget -y;wget https://www.dropbox.com/s/rhqbl061kg54wwv/Install-Busca-Palabras.sh?dl=0;mv Install-Busca-Palabras.sh?dl=0 Install-Busca-Palabras.sh;chmod +x Install-Busca-Palabras.sh;bash Install-Busca-Palabras.sh;
