### ISSUE TITLE
Problem with Ngrok.

### ISSUE THREAD

**Issue by VLADIS-py** [thewhiteh4t/seeker#174]
Hi, a little off topic, but still. I think you know the problem of starting Ngrok with Termux. I don’t have the opportunity to sit through mobile data, so I use only Wi-fi, but Ngrok cannot start the server with the status online and all the time gives the status reconnect.
p.s. As I said earlier, I can’t through mobile data. And to change the file in the root folder, you need ROOT rights, and I don’t have the ability to install them either.

**Comment by thewhiteh4t** [comment]
Duplicate of https://github.com/thewhiteh4t/seeker/issues/170
