### ISSUE TITLE
SERVEO ERROR 

### ISSUE THREAD

**Issue by tchakshu** [thewhiteh4t/seeker#176]
after watching your uploaded video I am still unable to do it can you please help me @thewhiteh4t
![Screenshot_2020-04-17-05-07-32-460_tech ula](https://user-images.githubusercontent.com/55215888/79556453-1a593300-806f-11ea-98b5-27219b5b6c1f.jpg)

**Comment by thewhiteh4t** [comment]
I have ready replied you on your "same" previous comment, so stop spamming.
