### ISSUE TITLE
Does not request permission in the site that I added.

### ISSUE THREAD

**Issue by VLADIS-py** [thewhiteh4t/seeker#177]
Hi, I decided to add a site. I copied the js and php folders from NearYou. In the file "templates.json" added his site.
Everything is OK, it appears in the list of sites when you open Seeker and the status of PhP servers is sucess. If anything, run on Ngrok.
Then I go to my site (which was made by seeker), but there is a problem. When opened, the site does not request location permissions. Update as you want, there will be just a site.

**Comment by thewhiteh4t** [comment]
Closing since, this is not an issue in seeker or the templates I have provided, this issue is on your end.
