### ISSUE TITLE
Php server error

### ISSUE THREAD

**Issue by quant-ru** [thewhiteh4t/seeker#178]
![Screenshot_2020-04-18_07-17-49](https://user-images.githubusercontent.com/63838021/79637371-bb65ed80-8144-11ea-8cc9-5228e417ff75.png)
((

**Comment by thewhiteh4t** [comment]
@quant-ru did you follow the instructions in readme?

**Comment by quant-ru** [comment]
I followed the instructions from the video

**Comment by thewhiteh4t** [comment]
@quant-ru video is a demo, not an installation guide, install instructions are given in readme, read it first, follow its steps, then start using the tool, and you clearly lack basics

**Comment by quant-ru** [comment]
OK. Thanks
