### ISSUE TITLE
Google chrome automatically deny location permission 

### ISSUE THREAD

**Issue by alpeshmali** [thewhiteh4t/seeker#180]
when the user open the site and choice Location optional and give permission (allow) but chrome automatically deny permission and give Error "please refers the page and try again" can solve this problem because most of the user has default browser is chrome

**Comment by thewhiteh4t** [comment]
@alpeshmali yes I am aware of this issue bu it turns out that problem is with google chrome and not with seeker, read my comment on this issue here https://github.com/thewhiteh4t/seeker/issues/173#issuecomment-613856711

**Comment by thewhiteh4t** [comment]
working on latest version, tested against `81.0.4044.138` , closing.
