### ISSUE TITLE
Include access camera and audio permission

### ISSUE THREAD

**Issue by Maxisldp** [thewhiteh4t/seeker#181]
Hello thewhiteh4t, first of all thanks for the great program you've developed, i really love it!!
Besides location, perhaps you can include camera and audio as well in the coming upgrade. 

Thanks a lot thewhiteh4t!!

**Comment by thewhiteh4t** [comment]
@Maxisldp thanks! yes I have this in my todo list, will add them in near future

**Comment by Maxisldp** [comment]
thanks for replying! really looking forward to your next pentesting tools!
keep up the great work

**Comment by FabxBs** [comment]
Looks interesting, it's kinda getting on a RAT side tho, since this repo it's focused on geolocation. Would be useful to get a more accurate geolocation by accessing some important data that's stored in the system.

**Comment by thewhiteh4t** [comment]
@FabxBs yeah moreover I don't see many websites asking for audio and camera permissions these days, location is kind off common in comparison, and I don't want to turn seeker into a full fledged stalking tool xD
