### ISSUE TITLE
can't integrate with ngrok and not showing loaction on manual setup

### ISSUE THREAD

**Issue by gituu4567** [thewhiteh4t/seeker#182]
@thewhiteh4t i started it manually and then i got this there is no path to nearyou folder but i did it manually and after that it does not showed any location

[>] Created By : thewhiteh4t
[>] Version    : 1.2.4

[+] Checking for Updates.....[ Up-To-Date ]
                                                                                                                                                           
[+] Skipping Serveo, start your own tunnel service manually...                                                                                             

[+] Select a Template : 

[0] NearYou
[1] Google Drive
[2] WhatsApp
[3] Telegram
[>] 0

[+] Loading NearYou Template...

[+] Port : 8080

[+] Starting PHP Server......[ Success ]

[+] Waiting for User Interaction...

**Comment by thewhiteh4t** [comment]
@gituu4567  "i got this there is no path to nearyou folder but i did it manually" , what did you do manually ?

**Comment by gituu4567** [comment]
i've started the tunnel manually how can i make it work with script by
default

**Comment by Hentai-ODispai** [comment]
Hello, I have the same problem

**Comment by thewhiteh4t** [comment]
@Hentai-ODispai did you watch the demo video?

**Comment by Hentai-ODispai** [comment]
@thewhiteh4t  Yes i have, but doesnt work .The url dosnt shows

**Comment by thewhiteh4t** [comment]
@Hentai-ODispai looks like you saw the old video, check demo section in readme for new demo video

**Comment by Hentai-ODispai** [comment]
Is that video in your youtube channel?

**Comment by thewhiteh4t** [comment]
@Hentai-ODispai https://www.youtube.com/watch?v=FEyAPjkJFrk&t=56s

**Comment by Hentai-ODispai** [comment]
Yes i see that but the /nearyou/ dont appear like in your video .Or the url






[>] Created By : thewhiteh4t
[>] Version    : 1.2.4

[+] Checking for Updates.....[ Up-To-Date ]
                                                                           
[+] Skipping Serveo, start your own tunnel service manually...             

[+] Select a Template : 

[0] NearYou
[1] Google Drive
[2] WhatsApp
[3] Telegram
[>] 0

[+] Loading NearYou Template...


[+] Port : 8080

[+] Starting PHP Server......[ Success ]

[+] Waiting for User Interaction...

**Comment by thewhiteh4t** [comment]
@Hentai-ODispai I have shown in the video, you have to execute ngrok yourself

**Comment by gituu4567** [comment]
thanks buddy i did that manually and its working fine
thanks for Help

**Comment by Alpha19adi** [comment]
the video has been deleted can anybody help please!
