### ISSUE TITLE
Whatsapp Image Path

### ISSUE THREAD

**Issue by DonMo7** [thewhiteh4t/seeker#183]
Could please explain that for me ? I have tried so many times but it didn’t work

**Comment by thewhiteh4t** [comment]
@DonMo7 have you downloaded an image of size 300x300 ?

**Comment by DonMo7** [comment]
Hello,
Thanx for the fast reply. Yes I have , it’s on the desktop

**Comment by DonMo7** [comment]
Give me an example of the path structure please

**Comment by thewhiteh4t** [comment]
@DonMo7 what is the absolute path of the image file?

**Comment by DonMo7** [comment]
home/<myuser>/Desktop/<image name >

**Comment by thewhiteh4t** [comment]
@DonMo7 are you on windows?

**Comment by DonMo7** [comment]
home/mohmed/Desktop/image.jpg

**Comment by DonMo7** [comment]
No I am on Kali

**Comment by thewhiteh4t** [comment]
@DonMo7 use `/home/mohmed/Desktop/image.jpg` in seeker

**Comment by DonMo7** [comment]
Ok I will try it now

**Comment by DonMo7** [comment]
[+] Path to Group Img (Best Size : 300x300): home/mohmed/Desktop/imagee.jpg

[-] Exception : [Errno 2] No such file or directory: 'home/mohmed/Desktop/imagee.jpg'

**Comment by DonMo7** [comment]
the image name is imagee

**Comment by thewhiteh4t** [comment]
@DonMo7 you forgot / before home

**Comment by DonMo7** [comment]
Thanks bro. just saw your reply. Thank you

**Comment by thewhiteh4t** [comment]
Great, read about linux file paths a bit, closing.

**Comment by uvaisleo** [comment]
please explain that for me ? I have tried so many times but it didn’t work

**Comment by Sa69** [comment]
Because it is a server issues 👍

**Comment by thewhiteh4t** [comment]
@uvaisleo absolute path is the full path of a file, suppose there is a file xyz.png in Pictures directory, the absolute path for this file will be `/home/uvaisleo/Pictures/xyz.png` 
To get the full path you can `cd` into the directory where the file is present and execute `pwd` 
Another thing you can do is to copy the image file into seeker directory and just use the name of the image file in seeker

**Comment by uvaisleo** [comment]
@thewhiteh4t /storage/emulated/0/Download/pexels-sanaan-mazhar-3052361.png that's file path. But not access. 'Permission denied'?

**Comment by thewhiteh4t** [comment]
@uvaisleo if you are using termux, thats not the full path

**Comment by uvaisleo** [comment]
> @uvaisleo if you are using termux, thats not the full path

What is the full path.pls reply

**Comment by arthasa28** [comment]
> Hello,
> I just noticed that I forgot to put “/“ before home. It worked now thank you.

what software do you use?

**Comment by arthasa28** [comment]
> what software do you use?

pls answer
