### ISSUE TITLE
Please solution

### ISSUE THREAD

**Issue by Ambroise7** [thewhiteh4t/seeker#19]
![screenshot_2018-09-12-18-20-33](https://user-images.githubusercontent.com/38510587/45442298-89afb980-b6b9-11e8-9422-21ee23248dac.png)
How to resolve ???

**Comment by thewhiteh4t** [comment]
Termux?

**Comment by Ambroise7** [comment]
Yes it is termux
How I can do now

Le mer. 12 sept. 2018 18:35, thewhiteh4t <notifications@github.com> a
écrit :

**Comment by thewhiteh4t** [comment]
This error means something is running on your port 80
Try this command
```
apachectl start
```
What do you get ?

**Comment by Ambroise7** [comment]
Nothing is  running on my Port but i will try this cmd

**Comment by thewhiteh4t** [comment]
Are you getting default apache page if you visit http://localhost
?

**Comment by Ambroise7** [comment]
I resolve it. I just deleted this file. See on screen shot
![screenshot_2018-09-12-19-41-25](https://user-images.githubusercontent.com/38510587/45446426-c0d79800-b6c4-11e8-8a54-4cd040f335e8.png)

**Comment by thewhiteh4t** [comment]
Great, closing.

**Comment by Ambroise7** [comment]
See you next time
