### ISSUE TITLE
why doesn't it work?

### ISSUE THREAD

**Issue by MORKOVKA25** [thewhiteh4t/seeker#191]
I tried to install it on my Raspberry Pi 4B 4G, with kali linux 32bit OS, and here is what it gave me. I do not understand anything. I am so sad (((( 
![Screenshot_2020-05-13_22-24-38](https://user-images.githubusercontent.com/65350351/81941546-a1afad00-9601-11ea-8312-1a3726f3c056.png)

**Comment by thewhiteh4t** [comment]
@MORKOVKA25 share `install.log` file present in seeker directory

**Comment by MORKOVKA25** [comment]
[install.log](https://github.com/thewhiteh4t/seeker/files/4629148/install.log)
@thewhiteh4t

**Comment by thewhiteh4t** [comment]
@MORKOVKA25 `pip3 install requests`

**Comment by MORKOVKA25** [comment]
![image](https://user-images.githubusercontent.com/65350351/81950828-1d632700-960d-11ea-8e46-2dd93b95924e.png)
and here install.log
[install.log](https://github.com/thewhiteh4t/seeker/files/4629227/install.log)

**Comment by thewhiteh4t** [comment]
@MORKOVKA25 your pip3 installation is broken somehow, take a look at this https://stackoverflow.com/questions/59693549/modulenotfounderror-no-module-named-pip-vendor-urllib3-after-update-pip3

**Comment by thewhiteh4t** [comment]
install.log is also showing the same, there are dependency problems with python

**Comment by MORKOVKA25** [comment]
thank you ! I will write here if this helps or not)

**Comment by MORKOVKA25** [comment]
it helps me! many thanks!

**Comment by MORKOVKA25** [comment]
but why .......((((((

![image](https://user-images.githubusercontent.com/65350351/81960825-332b1900-961a-11ea-9332-5f6d4d181f26.png)

**Comment by thewhiteh4t** [comment]
@MORKOVKA25 watch the demo video, link is in README, closing.
