### ISSUE TITLE
why PHP does not start?

### ISSUE THREAD

**Issue by MORKOVKA25** [thewhiteh4t/seeker#192]
And what can I do with this?
![image](https://user-images.githubusercontent.com/65350351/81963790-46d87e80-961e-11ea-999b-0531c6ba8a57.png)

**Comment by thewhiteh4t** [comment]
@MORKOVKA25 php is not installed, install it, since there were dependency problems earlier it looks like it was skipped so install it manually

**Comment by MORKOVKA25** [comment]
apt-get install php?

**Comment by thewhiteh4t** [comment]
@MORKOVKA25 find out :p

**Comment by MORKOVKA25** [comment]
that's help! Thank you;)
 closing
