### ISSUE TITLE
New templates

### ISSUE THREAD

**Issue by Fabxx** [thewhiteh4t/seeker#195]
I've noted this difference between a PC and a Android phone. For the PC i got aproximately 2.5km distance from my position, while on android only 18 meters, why this happens? Also i wanted to ask, wich templates are planned to be added in the future? maybe social templates such as reddit? or shopping templates like Amazon, AliExpress ecc?

**Comment by thewhiteh4t** [comment]
@FabxBs that's because PC does not have gps hardware in it but on the other hand a phone does, which is why seeker targets smartphones, and hence the tagline `Locate Smartphones Accurately` , so a pc will not give an accurate location and in the worst case it will be **ip geolocation** which is almost useless

if a template is convincing and practical such as the google drive one, I will create and add it, right now I am working on something else in seeker, I have not planned a new template so if you have a convincing idea you can drop it here :)

**Comment by FabxBs** [comment]
Ok, thank you very much for the quick response. I was thinking about something like data cloud where people can download the stuff that actually request, and instead you give to them a fake link, but with the original template. Forums, cloud links/storage, to scam them easier. Also would be better if we could change the link name or hide it like a link shortener

**Comment by thewhiteh4t** [comment]
@FabxBs okay so do you have any real forum/cloud/storage service in mind for this? a link shortener can be used but it will ultimately redirect to serveo or ngrok link so is it really useful?

**Comment by thewhiteh4t** [comment]
@FabxBs hahaha thanks, do you use discord?

**Comment by FabxBs** [comment]
yes i do, add me Def∆łt_x#4870

**Comment by thewhiteh4t** [comment]
@FabxBs https://discord.gg/A2FUvkM

**Comment by djhashh** [comment]
> 
> if a template is convincing and practical such as the google drive one, I will create and add it, right now I am working on something else in seeker, I have not planned a new template so if you have a convincing idea you can drop it here :)
 food delivery ph _i _shing coupon

**Comment by thewhiteh4t** [comment]
@djhashh clever!

**Comment by djhashh** [comment]
![20200524_231307](https://user-images.githubusercontent.com/45685039/82780405-47d69080-9e14-11ea-89e4-4582dc7c0f73.jpg)

**Comment by pretech86** [comment]
Html page .. after open the link .. if you want to proceed press ok

**Comment by cool3477** [comment]
> @djhashh clever!

Dear can Telegram Bot replace serveo? if its possible then all victim data auto posted in telegram chat and telegram Bot server never goes down .
its my suggestion i hope so u will think about it

**Comment by Ushan12** [comment]
Please mobile contacts list hack new add plz

**Comment by azamet90** [comment]
this tool is no more working so much after serveo updated

**Comment by hemant0126** [comment]
> > if a template is convincing and practical such as the google drive one, I will create and add it, right now I am working on something else in seeker, I have not planned a new template so if you have a convincing idea you can drop it here :)
> > food delivery ph _i _shing coupon

i think movie link qith movie template,
girls r most attractive,  get rupees after installing this app,    redirecting link to instagramme and telegramme

**Comment by Coldsmokr77** [comment]
@thewhiteh4t Out of them all I think mega.nz would be the most suitable as the 5th template. Any plans for making a 5th template yet?

**Comment by thewhiteh4t** [comment]
@Coldsmokr77 yes right now i am trying to complete a major update for seeker, which is why there hasnt been an update in some time now. After that update I will be adding more templates and most probably a guide to make your own templates as well :D

**Comment by Khushal2711** [comment]
I was thinking of a template where we can access any cloud drive with a legitimate link which is mask with fake link . where you can see content of drive and able to download it, or template that we can access any browser saved password and bookmarks, or template that we can able to download any embed videos , , videos  on PC. is it possible to do all this or any of them?

**Comment by Resousse** [comment]
Hello all, there is now a guide to explain how to create a template : https://github.com/thewhiteh4t/seeker/blob/master/createTemplate.md
Only HTML knowledge is required (no JS, PHP knowledge; for python it can be adapted from existing templates or I can help)
