### ISSUE TITLE
serveo stops working after 30 min

### ISSUE THREAD

**Issue by willemkuijpers** [thewhiteh4t/seeker#196]
My versions 1.2.1 and 1.2.4 are stopping working after 30 minutes, if a vicitim goes to the weblink it's shows webpage can't be loaded.

Tested on:
Termux
Ubuntu
Debian

It's on all clients the same, hopefully it can be fixed.

**Comment by thewhiteh4t** [comment]
@willemkuijpers thanks for pointing out, looks like server times out when it's idle for long, I will test and fix soon

**Comment by willemkuijpers** [comment]
@thewhiteh4t no worries, i hope it can be fixed also i have found maybe a other bug on ios, if someone press join chat and his location is on, he gets a warning " Please refresh this page and Allow Location Permission" but location is enabled.

**Comment by thewhiteh4t** [comment]
@willemkuijpers serveo timeout fixed, please update to v1.2.5 and test it out, which browser and version on iOS ?

**Comment by willemkuijpers** [comment]
I will test it out, and last version from ios, and 12.4/13.4/13.5

**Comment by thewhiteh4t** [comment]
@willemkuijpers I don't have an iphone, what about this : https://appetize.io/

**Comment by willemkuijpers** [comment]
Mm no error very strange i have tried on 3 iphones and they gived me the same errors

**Comment by thewhiteh4t** [comment]
looks like safari changed something, can you try chrome or firefox?

**Comment by willemkuijpers** [comment]
This is working perfect.

**Comment by thewhiteh4t** [comment]
@willemkuijpers great!

**Comment by willemkuijpers** [comment]
I hope the safari thing will be fixed
