### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by ramueppala** [thewhiteh4t/seeker#198]
Traceback (most recent call last):
  File "seeker.py", line 32, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

[install.log](https://github.com/thewhiteh4t/seeker/files/4720818/install.log)
 - install log

**Comment by thewhiteh4t** [comment]
@ramueppala try this command : `python -c "import requests"` and share output

**Comment by ramueppala** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named requests

**Comment by thewhiteh4t** [comment]
@ramueppala `pip3 install requests`

**Comment by ramueppala** [comment]
root@Notebook:/home/ramu/seeker# pip3 install requests
Requirement already satisfied: requests in /usr/lib/python3/dist-packages

**Comment by ramueppala** [comment]
sudo pip3 install requests
[sudo] password for ramu:     
The directory '/home/ramu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ramu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: requests in /usr/lib/python3/dist-packages

**Comment by thewhiteh4t** [comment]
@ramueppala your pip is broken, try using chown command with the path it's showing, closing since this is not an issue in seeker
