### ISSUE TITLE
404 Not Found 

### ISSUE THREAD

**Issue by asciiterminal** [thewhiteh4t/seeker#2]
i really love your work but unfortunately when i start seeker it gives me the link but when i open it using either my phone or pc it says 
`Not Found

The requested URL /nearyou/ was not found on this server.
Apache/2.4.33 (Debian) Server at 93b4e39c.ngrok.io Port 80`

**Comment by thewhiteh4t** [comment]
Can you please check if a folder named 'nearyou' exists in default apache path '/var/www/html'
if it does not exist please execute 'install.sh' again and check if the folder is created.

**Comment by thewhiteh4t** [comment]
Great, closing issue :)
