### ISSUE TITLE
Try antiseeker

### ISSUE THREAD

**Issue by Aurum2008** [thewhiteh4t/seeker#200]
I used antiseeker on myself and this error popped up and when I restart the seeker this error pops up again

Traceback (most recent call last):
  File "./seeker.py", line 368, in <module>
    wait()
  File "./seeker.py", line 199, in wait
    main()
  File "./seeker.py", line 278, in main
    var_lat = value['lat'] + ' deg'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by thewhiteh4t** [comment]
@Aurum2008 thanks will take a look...

**Comment by Aurum2008** [comment]
After reinstall all is working
