### ISSUE TITLE
Sayhello error in termux plz help me🥺🥺🥺

### ISSUE THREAD

**Issue by Abdurrurrab-Ajmal** [thewhiteh4t/seeker#201]
v1.1 coded by github.com/thelinuxchoice/sayhello
 Twitter: @linux_choice
If anyone see this plz reply help me to solve
In ngrok I was hacking some ones microphone using termux and sayhello by v1.1 coded by github.com/thelinuxchoice/sayhello
 Twitter: @linux_choice
I was able to do but one error occurs in the url it says
Failed to complete tunnel connection
The connection to https://bfa59fb39ed4.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:3333.

Make sure that a web service is running on localhost:3333 and that it is a valid address.

The error encountered was: dial tcp 127.0.0.1:3333: connect: connection refused
See like this plz any one help me🙏🙏🙏

**Comment by thewhiteh4t** [comment]
You have opened issue in wrong repository, Closing.

**Comment by Abdurrurrab-Ajmal** [comment]
> You have opened issue in wrong repository, Closing.

Bro give me your telegram username i will come there my id is @AbdurrabAjmal come there i will explian you plz bro come once

**Comment by Abdurrurrab-Ajmal** [comment]
Plz give me your telegram username sir let us talk there

**Comment by thewhiteh4t** [comment]
@Abdurrurrab-Ajmal ask here : https://discord.com/invite/A2FUvkM

**Comment by Abdurrurrab-Ajmal** [comment]
> @Abdurrurrab-Ajmal ask here : https://discord.com/invite/A2FUvkM

Ok I will join and plz solve my problem

**Comment by Abdurrurrab-Ajmal** [comment]
> @Abdurrurrab-Ajmal ask here : https://discord.com/invite/A2FUvkM

Thanka for helping me thanks alot
