### ISSUE TITLE
error while running ngrok

### ISSUE THREAD

**Issue by venkatasd90** [thewhiteh4t/seeker#203]
when i gave the command **./ngrok authtoken <token in my terminal>**
its throwing this as an error 
can any one please help me with this
**./ngrok: 1: A���: not found
./ngrok: 1: �: not found
./ngrok: 1: ��: not found
./ngrok: 1: }: not found
./ngrok: 1: �: not found
./ngrok: 1: ��R: not found
./ngrok: 1: ELF: not found
./ngrok: 1: ����
                +�
                  +��,�l�l@���Q�t�e@��: not found
./ngrok: 2: X: not found
./ngrok: 2: : not found
./ngrok: 4: �g: not found
./ngrok: 5: Syntax error: "(" unexpected**

Thanks in advance
_svenkata_

**Comment by thewhiteh4t** [comment]
@venkatasd90 this is not an issue in seeker, open issue in ngrok repo

**Comment by venkatasd90** [comment]
ngrok repo???

**Comment by thewhiteh4t** [comment]
@venkatasd90 there is another tool which is extremely useful : **google search**

**Comment by venkatasd90** [comment]
pagekite telconsole serveo?
