### ISSUE TITLE
The url has an https response error

### ISSUE THREAD

**Issue by 7h3-5n1p3r** [thewhiteh4t/seeker#205]
Everything runs ok. I got the URL as http://cineris.serveousercontent.com when i click on it, it shows an http response error.
Here is the Termux window - 
![Screenshot_20200619-201744](https://user-images.githubusercontent.com/56918107/85145584-6771a500-b26a-11ea-8be3-dd172637890f.jpg)

Here is the error - 
![Screenshot_20200619-202135](https://user-images.githubusercontent.com/56918107/85145728-a6075f80-b26a-11ea-8cf2-92ece81b2b14.jpg)

**Comment by thewhiteh4t** [comment]
@willsonmarandi please switch to some other tunnel service, in the upcoming update I am removing serveo because it is down most of the time and now they have removed SSL, here is the result : 
```
ssh -R 80:localhost:8080 serveo.net
Warning: no TLS certificate available for profor.serveousercontent.com. You won't be able to use HTTPS, only HTTP.
Forwarding HTTP traffic from http://profor.serveousercontent.com
```

**Comment by 7h3-5n1p3r** [comment]
Which means I have to manually set the server to use seeker. Sounds no big deal. Anyways, thanks for a quick reply.

You might wanna add localhost.run as the default server that's more active than serveo.

**Comment by thewhiteh4t** [comment]
@7h3-5n1p3r yeah you have to use a tunnel service of your choice, which is why I am not planning to add any service in the script from next update, it gives the user all options and usage is simplified, -t argument will no longer be required :)
