### ISSUE TITLE
error at choosing domain

### ISSUE THREAD

**Issue by AlphaZex** [thewhiteh4t/seeker#206]
when i type in python seeker.py -s whatsapp it didn't load anything after getting serveo url...... came out.
i'm sorry if my english is quite bad

**Comment by thewhiteh4t** [comment]
@AlphaZex use ngrok or something similar, we can no longer use serveo as they removed ssl and changed other functionality, serveo will be removed in next update.

**Comment by AlphaZex** [comment]
thx for the quick reply
