### ISSUE TITLE
starting PHP server.. [Error: 404] Termux

### ISSUE THREAD

**Issue by ArtemCPU-cell** [thewhiteh4t/seeker#208]
I had started ngrok, php localhost server. But when I start seeker manually I get this problem:

[+] Starting PHP Server......[Status : 404]

![IMG_20200625_132354](https://user-images.githubusercontent.com/61630289/85702503-26a0e280-b6e7-11ea-927f-ef1e402e7b7c.jpg)

**Comment by thewhiteh4t** [comment]
@ArtemCPU-cell inside seeker directory there is a `logs` directory inside it you will find `php.log` file please check the contents of the file, if you are not sure about the contents share it here

**Comment by ArtemCPU-cell** [comment]
Here it is.
I don't know what uses it. I started ngrok, php localhost.
[Thu Jun 25 13:01:55 2020] Failed to listen on 0.0.0.0:8080 (reason: Address already in use)

**Comment by thewhiteh4t** [comment]
@ArtemCPU-cell wait are you starting php server manually?

**Comment by ArtemCPU-cell** [comment]
hmm.
yes, I do.
But if I don't start it manually this error happens 
![IMG_20200625_231555](https://user-images.githubusercontent.com/61630289/85791171-0f3f1500-b73a-11ea-9d86-aab83028672a.jpg)

**Comment by ArtemCPU-cell** [comment]
and this error in ngrok:
![IMG_20200625_231954](https://user-images.githubusercontent.com/61630289/85791387-67761700-b73a-11ea-9c16-13738c05a492.jpg)

**Comment by thewhiteh4t** [comment]
Let me guess, virtualbox?

**Comment by ArtemCPU-cell** [comment]
sorry. what is it? 
I use termux on my own phone
I start php server like this:
![IMG_20200626_013928](https://user-images.githubusercontent.com/61630289/85802614-fcced680-b74d-11ea-8bac-736dbe48547b.jpg)

**Comment by thewhiteh4t** [comment]
@ArtemCPU-cell don't start php server manually, launch seeker and then check php.log

**Comment by ArtemCPU-cell** [comment]
I don't know what to say. It hadn't work. But now it does. Thank you so much for help
