### ISSUE TITLE
i cant add a path to group img in seeker 

### ISSUE THREAD

**Issue by Qalandar-sh** [thewhiteh4t/seeker#213]

**Comment by thewhiteh4t** [comment]
Use absolute path, if you don't know what that is you should not be using tools, learn basics of linux first, watch my demo on youtube link is in README

**Comment by Qalandar-sh** [comment]
and display these       
[-] Exception : [Errno 2] No such file or directory: '"C:\\Users\\MQ media\\Pictures\\whatsapp.jpg"'

**Comment by Qalandar-sh** [comment]
please help me
