### ISSUE TITLE
i have a problem with seeker in ubuntu

### ISSUE THREAD

**Issue by Qalandar-sh** [thewhiteh4t/seeker#214]
i want to add a  Path in to Group Img and it dose not word this is my img path "C:\Users\MQ media\Pictures\whatsapp.jpg"
after that i am occur an  [-] Exception : [Errno 2] No such file or directory: '"C:\\Users\\MQ media\\Pictures\\whatsapp.jpg"'
root@Qalandar:~/seeker#   
like this and i dont no what to do 
please HELP me guys

**Comment by thewhiteh4t** [comment]
Are you using kali wsl ?

**Comment by Qalandar-sh** [comment]
no i used windows 10

**Comment by thewhiteh4t** [comment]
Seeker is not supported on windows, use linux
