### ISSUE TITLE
server issue

### ISSUE THREAD

**Issue by Rayan567** [thewhiteh4t/seeker#215]
i got a error that servo status is offline how i do servo status online

**Comment by thewhiteh4t** [comment]
@Rayan567 watch "Whats new in v1.1.9" demo, link is in readme

**Comment by Rayan567** [comment]
still i face issue serveo status offline

**Comment by thewhiteh4t** [comment]
@Rayan567 if you can't even read the title I mentioned above and watch the correct video then nobody can help you
