### ISSUE TITLE
http to https error

### ISSUE THREAD

**Issue by hissssst** [thewhiteh4t/seeker#220]
Setting `window.location` to `https` prevents modern desktop browsers from opening it (tested on `chrome 83`, `firefox 80, 79`). Also, http connection prevents browsers from sharing geolocation

**Comment by thewhiteh4t** [comment]
@hissssst dont use serveo, they have removed SSL so you will see that warning page, use some other tunnel service which supports SSL like ngrok, you can check my demos for reference.
