### ISSUE TITLE
near you produces 404 result

### ISSUE THREAD

**Issue by johnnysailor23** [thewhiteh4t/seeker#222]
I've tried google drive url's already and the other options. Google drive produces the same result

[>] Created By : thewhiteh4t
[>] Version    : 1.2.5

[+] Checking for Updates.....[ Up-To-Date ]

[+] Skipping Serveo, start your own tunnel service manually...

[+] Select a Template :

[0] NearYou
[1] Google Drive
[2] WhatsApp
[3] Telegram
[>] 0

[+] Loading NearYou Template...

[+] Port : 8080

[+] Starting PHP Server......[Status : 404]

[+] Waiting for User Interaction...

**Comment by thewhiteh4t** [comment]
@johnnysailor23 share contents of `seeker/logs/php.log`

**Comment by johnnysailor23** [comment]
> @johnnysailor23 share contents of `seeker/logs/php.log`

Permission denied. Starting to troubleshoot.

**Comment by thewhiteh4t** [comment]
@johnnysailor23 use `sudo python3 seeker.py -t manual`

**Comment by johnnysailor23** [comment]
root@JNEWTON-NCO:/home/johnnytdg/seeker# sudo python3 seeker.py -t manual
[+] Checking Dependencies...

                        __
  ______  ____   ____  |  | __  ____ _______
 /  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/
/____  > \___  >\___  >|__|_ \ \___  >|__|
         \/      \/     \/      \/     \/

[>] Created By : thewhiteh4t
[>] Version    : 1.2.5

[+] Checking for Updates.....[ Up-To-Date ]

[+] Skipping Serveo, start your own tunnel service manually...

[+] Select a Template :

[0] NearYou
[1] Google Drive
[2] WhatsApp
[3] Telegram
[>] 0

[+] Loading NearYou Template...

[+] Port : 8080

[+] Starting PHP Server......[Status : 404]

[+] Waiting for User Interaction...

**Comment by thewhiteh4t** [comment]
@johnnysailor23 now check `php.log`

**Comment by johnnysailor23** [comment]
root@JNEWTON-NCO:/home/johnnytdg/seeker# php.log
bash: php.log: command not found

**Comment by thewhiteh4t** [comment]
@johnnysailor23 `cat logs/php.log` copy output and paste here

**Comment by johnnysailor23** [comment]
root@JNEWTON-NCO:/home/johnnytdg/seeker# cat logs/php.log
[Tue Aug  4 09:51:29 2020] Failed to listen on 0.0.0.0:8080 (reason: Address already in use)

**Comment by thewhiteh4t** [comment]
@johnnysailor23 yeah here you go, which operating system are you using?

**Comment by johnnysailor23** [comment]
> @johnnysailor23 yeah here you go, which operating system are you using?

Windows 10, Kali linux app
I'm dabbling with wsl and power shell but I figured this would be easier

**Comment by thewhiteh4t** [comment]
@johnnysailor23 I see, try this command and share output : `pidof php`

**Comment by johnnysailor23** [comment]
No output

**Comment by thewhiteh4t** [comment]
@johnnysailor23 okay great, now this : `service apache2 status`

**Comment by johnnysailor23** [comment]
root@JNEWTON-NCO:/home/johnnytdg/seeker# service apache2 status
apache2 is not running ... failed!

**Comment by thewhiteh4t** [comment]
@johnnysailor23 please try `netstat -plnt` and share output

**Comment by johnnysailor23** [comment]
root@JNEWTON-NCO:/home/johnnytdg/seeker# netstat -plnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name

**Comment by johnnysailor23** [comment]
root@JNEWTON-NCO:/home/johnnytdg/seeker# service apache2 start
Starting Apache httpd web server: apache2[Tue Aug 04 11:23:56.669659 2020] [core:warn] [pid 667] (92)Protocol not available: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT

**Comment by johnnysailor23** [comment]
root@JNEWTON-NCO:/home/johnnytdg/seeker# service apache2 start
Starting Apache httpd web server: apache2.

**Comment by johnnysailor23** [comment]
root@JNEWTON-NCO:/home/johnnytdg/seeker# service apache2 status
apache2 is running.

root@JNEWTON-NCO:/home/johnnytdg/seeker# netstat -plnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name

**Comment by thewhiteh4t** [comment]
@johnnysailor23 this is weird you should get something like this : 
```
# netstat -plnt

Active Internet connections (only servers)

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::80                   :::*                    LISTEN      43/apache2
```

**Comment by johnnysailor23** [comment]
agreed. Not sure why it is not populating any information at all.

**Comment by thewhiteh4t** [comment]
anyways the problem is port 8080 is being used by some other service and since netstat is unable to display anything you can use some other port lets say 8090, so use : `python3 seeker.py -p 8090 -t manual`

**Comment by johnnysailor23** [comment]
______  ____   ____  |  | __  ____ _______
 /  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/
/____  > \___  >\___  >|__|_ \ \___  >|__|
         \/      \/     \/      \/     \/

[>] Created By : thewhiteh4t
[>] Version    : 1.2.5

[+] Checking for Updates.....[ Up-To-Date ]

[+] Skipping Serveo, start your own tunnel service manually...

[+] Select a Template :

[0] NearYou
[1] Google Drive
[2] WhatsApp
[3] Telegram
[>] 0

[+] Loading NearYou Template...

[+] Port : 8090

[+] Starting PHP Server......[ Success ]

[+] Waiting for User Interaction...


Shouldn't it populate a URL to capture the user interaction??

**Comment by thewhiteh4t** [comment]
@johnnysailor23 please watch my demo "What's new in seeker v1.1.9" it will help you further, links are in the readme

**Comment by johnnysailor23** [comment]
root@JNEWTON-NCO:/home/johnnytdg/seeker# python3 seeker.py -p 8090 -t manual
[+] Checking Dependencies...

                        __
  ______  ____   ____  |  | __  ____ _______
 /  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/
/____  > \___  >\___  >|__|_ \ \___  >|__|
         \/      \/     \/      \/     \/

[>] Created By : thewhiteh4t
[>] Version    : 1.2.5

[+] Checking for Updates.....[ Up-To-Date ]

[+] Skipping Serveo, start your own tunnel service manually...

[+] Select a Template :

[0] NearYou
[1] Google Drive
[2] WhatsApp
[3] Telegram
[>] ./ngrok http 8090
Traceback (most recent call last):
  File "seeker.py", line 366, in <module>
    template_select()
  File "seeker.py", line 105, in template_select
    selected = int(input(G + '[>] ' + W))
ValueError: invalid literal for int() with base 10: './ngrok http 8090'

This is where I'm stuck at, I have gotten ngrok tunnel to work but I can't for some reason get it to work on seeker. 

ngrok by @inconshreveable                                                                               (Ctrl+C to quit)                                                                                                                        Session Status                online                                                                                    Account                       Johnathon Newton (Plan: Free)                                                             Version                       2.3.35                                                                                    Region                        United States (us)                                                                        Web Interface                 http://127.0.0.1:4040                                                                     Forwarding                    http://f6adaf16a634.ngrok.io -> http://localhost:8090                                     Forwarding                    https://f6adaf16a634.ngrok.io -> http://localhost:8090                                                                                                                                                            Connections                   ttl     opn     rt1     rt5     p50     p90                                                                             0       0       0.00    0.00    0.00    0.00

**Comment by johnnysailor23** [comment]
I was able to get here using kali but I had to open the ngrok tunnel using the ngrok.exe on my desktop
./ngrok http 80 and ngrok http 80 both do not work from the seeker platform
I was able to open a tunnel from cmd,powershell,and kali if I was in the desktop directory but otherwise I am unable to use ngrok from any platform

______  ____   ____  |  | __  ____ _______
 /  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/
/____  > \___  >\___  >|__|_ \ \___  >|__|
         \/      \/     \/      \/     \/

[>] Created By : thewhiteh4t
[>] Version    : 1.2.5

[+] Checking for Updates.....[ Up-To-Date ]

[+] Skipping Serveo, start your own tunnel service manually...

[+] Select a Template :

[0] NearYou
[1] Google Drive
[2] WhatsApp
[3] Telegram
[>] 0

[+] Loading NearYou Template...

[+] Port : 80

[+] Starting PHP Server......[ Success ]

[+] Waiting for User Interaction...

ngrok by @inconshreveable                                                                               (Ctrl+C to quit)                                                                                                                        Session Status                online                                                                                    Session Expires               7 hours, 54 minutes                                                                       Version                       2.3.35                                                                                    Region                        United States (us)                                                                        Web Interface                 http://127.0.0.1:4040                                                                     Forwarding                    http://254a73bdf0b0.ngrok.io -> http://localhost:80                                       Forwarding                    https://254a73bdf0b0.ngrok.io -> http://localhost:80                                                                                                                                                              Connections                   ttl     opn     rt1     rt5     p50     p90                                                                             10      0       0.01    0.02    5.00    5.58                                                                                                                                                                      HTTP Requests                                                                                                           -------------                                                                                                                                                                                                                                   GET /favicon.ico               404 Not Found                                                                            GET /icons/openlogo-75.png     200 OK                                                                                   GET /                          200 OK

**Comment by johnnysailor23** [comment]
Is there a way to install ngrok inside seeker or kali linux that I am unaware of? I've tried unzipping it, didn't work. I tried moving the folder to the same folder that kali linux is located on inside the Local\Packages and unzipping it there. No luck
Could the problem simply be that I'm not running kali linux natively as my OS and it is causing these issues???

**Comment by johnnysailor23** [comment]
Disregard. I was able to get it working. I had to do python3 seeker.py -p 8090 -t manual then selecting the option 0
