### ISSUE TITLE
Serveo Status Offline

### ISSUE THREAD

**Issue by alkir202** [thewhiteh4t/seeker#223]
![1](https://user-images.githubusercontent.com/52386704/89520394-772b5580-d7e6-11ea-9cf0-9bdbe16bf367.png)

**Comment by thewhiteh4t** [comment]
@alkir202 watch my demo : what's new in seeker v1.1.9
Link is in readme

**Comment by faccboy** [comment]
@thewhiteh4t the youtube link with the demo is offline/removed by YouTube. 

@alkir202 , as the message says Serveo status is offline, use an alternative with the -t command, like Ngrok and it will work.

**Comment by Nischal-Acharya** [comment]
How can we fix this

**Comment by thewhiteh4t** [comment]
@Nischal-Acharya use latest version
