### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by MDKAS** [thewhiteh4t/seeker#224]
./termux_install.sh
[!] Updating...

[!] Installing Dependencies...
    Python3
    PHP
    ssh
    Requests

[!] Setting Permissions...

[!] Installed.
$ python3 seeker.py
[+] Checking Dependencies...
[-] php is not Installed!
[-] ssh is not Installed!
$

Installation takes place in a few seconds, chmod 777 was registered.

**Comment by thewhiteh4t** [comment]
@MDKAS check `install.log` for errors, if there are any google the errors and fix them

**Comment by MDKAS** [comment]
Errors?

Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Get:4 https://dl.bintray.com/termux/termux-packages-24 stable Release [8255 B]
Hit:4 https://dl.bintray.com/termux/termux-packages-24 stable Release
Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:5 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:7 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Hit:7 https://dl.bintray.com/grimler/science-packages-24 science Release
Reading package lists...
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. 
Requirement already satisfied: requests in /data/data/com.termux/files/usr/lib/python3.8/site-packages (2.24.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from requests) (1.25.10)
Requirement already satisfied: certifi>=2017.4.17 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from requests) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from requests) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from requests) (2.10)

**Comment by MDKAS** [comment]
Okay. I'm fix it. But:
$ python3 seeker.py
[+] Checking Dependencies...

                        __
  ______  ____   ____  |  | __  ____ _______
 /  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/
/____  > \___  >\___  >|__|_ \ \___  >|__|
         \/      \/     \/      \/     \/

[>] Created By : thewhiteh4t
[>] Version    : 1.2.5

[+] Checking for Updates.....[ Up-To-Date ]

[+] Checking Serveo Status...[ Offline ]

Only wait? Or use any proxy?

**Comment by thewhiteh4t** [comment]
@MDKAS watch my demo : what's new in seeker v1.1.9 for reference

**Comment by MUHAMMADZAKIHASIBUAN06** [comment]
![Screenshot_2022-07-09-00-23-22-019_com termux](https://user-images.githubusercontent.com/92998725/178041131-630bb296-a037-4619-8de8-e2279ff2f5ae.jpg)

Apa masalahnya ini?

**Comment by thewhiteh4t** [comment]
@MUHAMMADZAKIHASIBUAN06 i have updated `install.sh` please update and try again

**Comment by ARXPLOITREAL** [comment]
./install.sh
[!] Installing Dependencies...

python3 - Failed!
python3-pip - Failed!
python3-requests - Failed!
python3-packaging - Failed!
python3-psutil - Failed!
php - Failed! And i

**Comment by thewhiteh4t** [comment]
@ARXPLOITREAL check install.log under logs directory

**Comment by GHOST21186** [comment]
Installing Dependencies...                                                                                                                                python3 - Failed!                                                              python3-pip - Failed!                                                          python3-requests - Failed!                                                     python3-packaging - Failed!                                                    python3-psutil - Failed!                                                       php - Failed!                                                                                                                                                 [+] Log Saved : /data/data/com.termux/files/home/seeker/logs/install.log

**Comment by thewhiteh4t** [comment]
@GHOST21186 share output of `echo $OSTYPE`

**Comment by GHOST21186** [comment]
![Screenshot_20231226-193025.png](https://github.com/thewhiteh4t/seeker/assets/151578662/5526cfce-f600-49aa-a273-fbf7dce228ee)

**Comment by GHOST21186** [comment]
> @GHOST21186 share output of `echo $OSTYPE`

![Screenshot_20231226-193025.png](https://github.com/thewhiteh4t/seeker/assets/151578662/dfd9d1b5-d7d5-4237-ac94-0553c0c21dc6)

**Comment by GHOST21186** [comment]
> @GHOST21186 share output of `echo $OSTYPE`

Nothing to do about it ??!

**Comment by thewhiteh4t** [comment]
@GHOST21186 thanks for the output, i will push an update soon
