### ISSUE TITLE
Add php installation in install.sh

### ISSUE THREAD

**Issue by souvikhaldar** [thewhiteh4t/seeker#228]
Suggestion:  
You can check if php is installed or not then installed PHP in the install script:  
![image](https://user-images.githubusercontent.com/20991754/90337033-52608a80-dffd-11ea-98f3-820de82c12f0.png)

**Comment by thewhiteh4t** [comment]
@souvikhaldar you will have to remove lock files until then your apt wont install anything also I will be removing install script most probably, working on the next update

**Comment by thewhiteh4t** [comment]
@souvikhaldar what is your opinion, to keep install script and improve it or remove it?

**Comment by souvikhaldar** [comment]
Updated, upgraded then ran install script with sudo. Still missing PHP. I can install PHP manually too though.
![image](https://user-images.githubusercontent.com/20991754/90337796-7a9eb800-e002-11ea-8a75-40768ddb08da.png)

**Comment by thewhiteh4t** [comment]
@souvikhaldar this time you got lock issue, remove lock files or apt wont install anything, the path is already given just rm

**Comment by souvikhaldar** [comment]
I just fixed it.
Working fine now.
Thanks!
![image](https://user-images.githubusercontent.com/20991754/90340553-a3c94380-e016-11ea-8c5c-14e238b3df7c.png)
