### ISSUE TITLE
The request contained an unknown or invalid Host header. If you are trying to access GSA via its hostname or a proxy, make sure GSA is set up to allow it.

### ISSUE THREAD

**Issue by dcliss** [thewhiteh4t/seeker#23]
it runs when i try it on any devices chrome firefox mobile browser. it says this "The request contained an unknown or invalid Host header. If you are trying to access GSA via its hostname or a proxy, make sure GSA is set up to allow it."

**Comment by dcliss** [comment]
![screen shot 2018-09-21 at 2 10 42 pm](https://user-images.githubusercontent.com/32026802/45870301-2f44e600-bda8-11e8-8fb9-b6b00f104658.png)

**Comment by thewhiteh4t** [comment]
this is new, i will look into it, also Firefox ESR is a bit different from Firefox Quantum and it does not cooperate like other browsers, but i have seen this for the first time

**Comment by thewhiteh4t** [comment]
yeah its because openvas is running in your kali, execute openvas-stop and then launch seeker

**Comment by dcliss** [comment]
cool bro got it worked thanks alot !! you have a developed a great tool in between
