### ISSUE TITLE
nao esta subindo a url

### ISSUE THREAD

**Issue by rudival591** [thewhiteh4t/seeker#236]
mesmo executando igual no video modo manual etc ele nao gera a url para adicionar no final do tuner
[0] NearYou
[1] Google Drive
[2] WhatsApp
[3] Telegram
[>] 2

[+] Loading WhatsApp Template...
[+] Group Title : teste
[+] Path to Group Img (Best Size : 300x300): /home/.../Documentos/g1.jpg

[+] Port : 8080

[+] Starting PHP Server......[ Success ]

[+] Waiting for User Interaction...

**Comment by thewhiteh4t** [comment]
Next time, english please.

**Comment by rudival591** [comment]
same as in the video mode manual etc. it does not generate a url to add at the end of the tuner
[0] Close to you
[1] Google Drive
[2] WhatsApp
[3] Telegram
[>] 2

[+] Loading WhatsApp model ...
[+] Group title: teste
[+] Path for group image (best size: 300x300): /home/.../Documentos/g1.jpg

[+] Port: 8080

[+] Starting PHP Server ...... [Success]

[+] Awaiting user interaction ...

Thank you for your attention, but being able to understand the process, the business and that to run it is necessary to point port 8080 when starting tunnel or ngrok
ex:
./ngrok http8080
