### ISSUE TITLE
Module issue

### ISSUE THREAD

**Issue by rohitgaonkar** [thewhiteh4t/seeker#238]
Traceback (most recent call last):
  File "seeker.py", line 32, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

What to do?

**Comment by thewhiteh4t** [comment]
@rohitgaonkar `sudo pip3 install requests`

**Comment by rohitgaonkar** [comment]
Thank you for your response

**Comment by santoshdawre** [comment]
> @rohitgaonkar `sudo pip3 install requests`

i tried this but its not working for me . it shows "Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.24.0)"
