### ISSUE TITLE
server status [offline]

### ISSUE THREAD

**Issue by Mukeshkumar20-03** [thewhiteh4t/seeker#240]
Hi! its showing like server status offline and don't showing the options...

**Comment by danillucky1234** [comment]
First of all, you need to download ngrok. After downloading open 2 terminals, in the first of them write the command: python3 seeker.py -t manual -k testkml
In the second terminal write the command: ngrok http 8080. Copy address and add the following line "/nearyou/" ( or "/telegram/" and so on) to the end of the address. Its will be your "bad url"

**Comment by jigsaw678** [comment]
i have the same issue @danillucky1234

**Comment by Kevin-72** [comment]
> First of all, you need to download ngrok. After downloading open 2 terminals, in the first of them write the command: python3 seeker.py -t manual -k testkml
> In the second terminal write the command: ngrok http 8080. Copy address and add the following line "/nearyou/" ( or "/telegram/" and so on) to the end of the address. Its will be your "bad url"

where is "testkml"??

**Comment by thewhiteh4t** [comment]
@Kevin-72 read usage instructions in readme

**Comment by Mukeshkumar20-03** [comment]
Yeah now it's working Thanks :)

**Comment by Mukeshkumar20-03** [comment]
issue solved
