### ISSUE TITLE
Create a manual 

### ISSUE THREAD

**Issue by Pawansai74** [thewhiteh4t/seeker#243]
How can I create my own manual in seeker. Because when I want to share URL serveo it is continuously throwing that create own manual. How can I create? 
![Screenshot_20200927_042814](https://user-images.githubusercontent.com/68721224/94352300-af317500-0080-11eb-9f72-324b81197fc3.jpg)

**Comment by thewhiteh4t** [comment]
@Pawansai74 https://github.com/thewhiteh4t/seeker#demo 
watch v1.1.9 demo
