### ISSUE TITLE
Location accuracy

### ISSUE THREAD

**Issue by advaithpr1020** [thewhiteh4t/seeker#249]
Hi,I recently installed seeker on my Kali Linux(Vbox).All things work great but when I tried it on some of my friends,their location is not at all accurate.I tried it on myself too but the location is wrong.Pls help

**Comment by thewhiteh4t** [comment]
@advaithpr1020 which device was used as target? which browser was used?

**Comment by advaithpr1020** [comment]
I tested myself on a Samsung Galaxy A70 and browser was chrome.I tested in this phone and also my PC.Both are showing the same location but it's wrong.

**Comment by thewhiteh4t** [comment]
@advaithpr1020 great, so first thing here is that seeker is designed specifically for phones because they have actual gps hardware in them, it is not designed for PCs, location from a PC will always be incorrect, for phone, try to re-caliberate your gps and try again also check if high accuracy is turned on, normally it is on by default

**Comment by thewhiteh4t** [comment]
location accuracy largely depends on the phone and gps calibration, not much we can do here to be honest

**Comment by advaithpr1020** [comment]
Oh Ok I see
Thanks for the quick reply!😄😄

**Comment by thewhiteh4t** [comment]
@advaithpr1020 hopefully that helps :)

**Comment by advaithpr1020** [comment]
Turned on location accuracy but still no luck.Just noticed that my city is wrong too😕

**Comment by thewhiteh4t** [comment]
@advaithpr1020 try to calibrate your gps

**Comment by advaithpr1020** [comment]
Ok will try

**Comment by advaithpr1020** [comment]
Tried finding location in Google map,it's correct

**Comment by thewhiteh4t** [comment]
@advaithpr1020 of course it will be correct, it is google ;) they have much advanced mechanism for getting accurate location, I am not google XD

**Comment by advaithpr1020** [comment]
Hehe

**Comment by thewhiteh4t** [comment]
@advaithpr1020 try using firefox

**Comment by advaithpr1020** [comment]
Ok

**Comment by advaithpr1020** [comment]
Didn't work.Same condition.Thing is,I had an old laptop that I used and it had the Kali and seeker too and it worked perfectly fine.No error whatsoever.But the issue is in my new PC

**Comment by thewhiteh4t** [comment]
@advaithpr1020 ohh thats weird, this should not happen though

**Comment by thewhiteh4t** [comment]
okay lets do one thing, since the location is repeating, exit seeker using `ctrl+c` and then execute `pidof php` if you get an output that means php server is still active and that is not something we want, use `pkill php` to kill all active processes of php and then start seeker again

**Comment by advaithpr1020** [comment]
Did it,but it seems to do nothing.A thing I noticed now is that different browsers show different locations🥴.Tried it on Firefox ,chrome and Microsoft edge

**Comment by thewhiteh4t** [comment]
@advaithpr1020 minor differences are expected but nothing major also you have edge installed on your phone :O

**Comment by advaithpr1020** [comment]
Hehe..Just installed it for testing 😜
Ps: location difference is 8-10 Kms☹️

**Comment by thewhiteh4t** [comment]
@advaithpr1020 do you have any other device with you? different brand/model

**Comment by advaithpr1020** [comment]
Yes

**Comment by thewhiteh4t** [comment]
awesome try testing on that, chrome, firefox lets see, if it still shows same coordinates I will test it on my device later today

**Comment by advaithpr1020** [comment]
Just tries on an old Nokia 6 and it worked!!
Thanks so much.Btw have any idea why it doesn't work on my main phone?

**Comment by thewhiteh4t** [comment]
> location accuracy largely depends on the phone and gps calibration, not much we can do here to be honest

this is the reason, companies like samsung modify android in many ways which changes the overall experience, nokia, motorola and oneplus on the other hand offer stock android and thats why they perform better and dont have these type of issues because honestly the gps should work in the same way on a browser and in an app, but you can clearly see that is not the case with samsung

**Comment by advaithpr1020** [comment]
Oh that's right.:o
Huge thanks for your help
