### ISSUE TITLE
Not showing lat and longitude

### ISSUE THREAD

**Issue by mrhydra-np** [thewhiteh4t/seeker#251]
Is there certain range for this i tried with my friend and he allowed location access but here i got Location information is unavailable other things are all true

**Comment by thewhiteh4t** [comment]
@mrhydra-np no but it depends on multiple factors such as : 
1. it is designed for smartphones not for laptops as they dont have gps hardware
2. browser - works best on chrome, firefox
3. gps calibration 
4. gps high accuracy setting
5. device itself
so as you can see things can change from device to device

**Comment by mrhydra-np** [comment]
He opened the link in google chrome on Redmi Note 7 Phone. So yeah maybe it's due to other left behind factors 😅😀

**Comment by thewhiteh4t** [comment]
@mrhydra-np okay, did you test on your device?

**Comment by mrhydra-np** [comment]
Yah i tested on my iphone at first which was just near me. The city it provided was something 15km far away but when i opened it from google map it gave correct location😄

**Comment by thewhiteh4t** [comment]
@mrhydra-np i dont have an iphone for testing :(

**Comment by mrhydra-np** [comment]
No prob it's working fine on iPhone maybe i opened it from Safari or chrome I'm confused but if you wanna know i can test it again 😁

**Comment by thewhiteh4t** [comment]
@mrhydra-np yes please, test on both, lets see

**Comment by mrhydra-np** [comment]
Sure mr developer 😄😎

**Comment by mrhydra-np** [comment]
Ok i tested, the google location is very exact just city is incorrect. 
And why sometime it says user denied the request for Geolocation. In phone i accepted the location access 🤔 Yesterday for my friend it happened too

**Comment by thewhiteh4t** [comment]
hmmmmmmm @mrhydra-np thats weird, the problem is I have tested on all devices I have and it works fine, if i am unable to recreate the issue I cannot fix it XD
