### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'logs/php.log'

### ISSUE THREAD

**Issue by joshuasarmiento** [thewhiteh4t/seeker#254]
[+] Starting PHP Server......Traceback (most recent call last):
  File "./seeker.py", line 367, in <module>
    server()
  File "./seeker.py", line 176, in server
    with open('logs/php.log', 'w') as phplog:
PermissionError: [Errno 13] Permission denied: 'logs/php.log'

Can someone help me?

**Comment by thewhiteh4t** [comment]
@joshuasarmiento use `sudo`

**Comment by Suganlove** [comment]
[!] Installing Dependencies...

Python3 - Installed
PHP - Installed
Requests - Failed!
Packaging - Failed!

Log Saved : /home/sugan/Downloads/seeker/logs/install.log

**Comment by Suganlove** [comment]
help me bro

**Comment by Suganlove** [comment]
[sugan@suganhacker]-[~/Downloads/seeker]
>>> python3 seeker.py -h
Traceback (most recent call last):
  File "/home/sugan/Downloads/seeker/seeker.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Suganlove** [comment]
not working bro please help me bro

**Comment by thewhiteh4t** [comment]
@Suganlove read the install log file and check why requests and packaging failed to install
