### ISSUE TITLE
Webserver not working

### ISSUE THREAD

**Issue by 1ramkrishnan** [thewhiteh4t/seeker#255]

**Comment by thewhiteh4t** [comment]
@1ramkrishnan please share `seeker/logs/php.log`

**Comment by 1ramkrishnan** [comment]
[Thu Nov 19 17:49:20 2020] 127.0.0.1:47952 Closing
[Thu Nov 19 17:49:20 2020] 127.0.0.1:47956 Accepted
[Thu Nov 19 17:49:20 2020] 127.0.0.1:47956 Invalid reque
st (Unsupported SSL request)
[Thu Nov 19 17:49:20 2020] 127.0.0.1:47956 Closing
[Thu Nov 19 17:49:20 2020] 127.0.0.1:47960 Accepted
[Thu Nov 19 17:49:20 2020] 127.0.0.1:47960 Invalid reque
st (Unsupported SSL request)
[Thu Nov 19 17:49:20 2020] 127.0.0.1:47960 Closing
[Thu Nov 19 17:49:22 2020] 127.0.0.1:47966 Accepted

**Comment by codexprime** [comment]
the server is not working

**Comment by thewhiteh4t** [comment]
@codexprime 
what commands did you execute?
What errors are you getting?
Any screenshots?
Provide more information

**Comment by codexprime** [comment]
` ./seeker.py -t manual`
[>] Created By : thewhiteh4t
[>] Version    : 1.2.5

[+] Checking for Updates.....[ Up-To-Date ]

[+] Skipping Serveo, start your own tunnel service manually...

[+] Select a Template :

[0] NearYou
[1] Google Drive
[2] WhatsApp
[3] Telegram
[>] 0

[+] Loading NearYou Template...

[+] Port : 8080

[+] Starting PHP Server......[ Failed ]

~/seeker/logs# cat php.log
[Fri Jan  8 13:19:04 2021] Failed to listen on 0.0.0.0:8080 (reason: Address already in use)

also tried manually running ngrok

**Comment by codexprime** [comment]
Excuse for troubling
everything is working =)
