### ISSUE TITLE
Invalid file directory  for telegram image

### ISSUE THREAD

**Issue by jigsaw678** [thewhiteh4t/seeker#256]
`[>] Created By : thewhiteh4t
[>] Version    : 1.2.5

[+] Checking for Updates.....[ Up-To-Date ]

[+] Skipping Serveo, start your own tunnel service manually...

[+] Select a Template : 

[0] NearYou
[1] Google Drive
[2] WhatsApp
[3] Telegram
[>] 3

[+] Loading Telegram Template...
[+] Group Title : u
[+] Group Description : p
[+] Image Path (Best Size : 300x300) : /template/telegram/images/op.jpg 
[+] Number of Members : 7
[+] Number of Members Online : 5

[-] Exception : [Errno 2] No such file or directory: '/template/telegram/images/op.jpg '
`

**Comment by thewhiteh4t** [comment]
@jigsaw678 provide absolute path to image

**Comment by HariKrishna100** [comment]
hi how can i give a path to a image i don't understand can you make a video in youtube i didn't understand how you cave the path to the image

**Comment by HariKrishna100** [comment]
hello developer

**Comment by Wixi105** [comment]
Same issue here, doesn't seem to work even with absolute path. I have my image stored in my home folder, and it doesn't find the image.

**Comment by Wixi105** [comment]
But it works for Whatsapp tho

**Comment by thewhiteh4t** [comment]
@Wixi105 @HariKrishna100 please read this, it will help in understanding what absolute path is : https://www.geeksforgeeks.org/absolute-relative-pathnames-unix/

**Comment by Milodrag** [comment]
It needs sudo access. Run it in sudo.
Here: 
 sudo ./seeker.py -t manual
