### ISSUE TITLE
Clone not working on termux

### ISSUE THREAD

**Issue by Dark-blac** [thewhiteh4t/seeker#257]
Quote: 
"bash: git clone https://github.com/thewhiteh4t/seeker.git: No such file or directory"

**Comment by thewhiteh4t** [comment]
this is not an issue with seeker.

**Comment by ssougour** [comment]
> Quote: 
> "bash: git clone https://github.com/thewhiteh4t/seeker.git: No such file or directory"

I don't even know why it's saying the same thing. What is going on?

**Comment by thewhiteh4t** [comment]
@ssougour screenshot please

**Comment by ssougour** [comment]
> @ssougour screenshot please

![Screenshot_2021-04-29-08-57-35-122_com.termux.jpg](https://user-images.githubusercontent.com/47749593/116519095-f870ce00-a8c8-11eb-8843-fec764bbf9dc.jpg)

**Comment by ssougour** [comment]
This is Ok
https://github.com/thewhiteh4t/seeker.git
This is not
cd /seeker/termux && ls

**Comment by thewhiteh4t** [comment]
@ssougour https://thewhiteh4t.github.io/2020/06/09/How-to-Install-seeker-in-Termux-Android.html

**Comment by ssougour** [comment]
> @ssougour https://thewhiteh4t.github.io/2020/06/09/How-to-Install-seeker-in-Termux-Android.html

![Screenshot_2021-04-29-09-11-10-206_com.termux.jpg](https://user-images.githubusercontent.com/47749593/116520611-dd06c280-a8ca-11eb-95e6-010e7431e8c9.jpg)


Thank you so much💙

**Comment by ssougour** [comment]
> @ssougour https://thewhiteh4t.github.io/2020/06/09/How-to-Install-seeker-in-Termux-Android.html

![IMG_20210429_091416.jpg](https://user-images.githubusercontent.com/47749593/116520969-4edf0c00-a8cb-11eb-926b-e141b1b3c154.jpg)


Why it's offline how do I fix that?

**Comment by thewhiteh4t** [comment]
@ssougour an update is due but meanwhile I have provided usage instructions in README

**Comment by ssougour** [comment]
> @ssougour an update is due but meanwhile I have provided usage instructions in README

So I can't make up to date serveo status?

**Comment by thewhiteh4t** [comment]
@ssougour if you read usage instructions you will know what to do
