### ISSUE TITLE
Run docker image not working

### ISSUE THREAD

**Issue by migmam** [thewhiteh4t/seeker#259]
According to the instructions to run the docker image the command is:

docker run --rm -t --net ngroknet --name seeker thewhiteh4t/seeker python3 seeker.py -t manual

But it doesn't allow the select the options of the python script (whatsapp, telegram, etc...)
It should be
docker run --rm -**i**t --net ngroknet --name seeker thewhiteh4t/seeker python3 seeker.py -t manual

**Comment by thewhiteh4t** [comment]
@migmam thanks! good catch, i have updated the readme with correct command, closing.
