### ISSUE TITLE
Sir plz check it ......Thx in advance

### ISSUE THREAD

**Issue by Ghostpsycho** [thewhiteh4t/seeker#265]
**When i install pip3 it shows like :**

pip3 install requests
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.                                                                                      
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/requests/                                                                                     
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/requests/                                                                                     
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/requests/                                                                                     
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/requests/                                                                                     
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/requests/                                                                                     
Could not fetch URL https://pypi.org/simple/requests/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/requests/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement requests (from versions: none)
ERROR: No matching distribution found for requests
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.                                                                                      
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

**And if i Open seeker it shows like :**

python3 seeker.py -t manual                                                                 1 ⨯
[+] Checking Dependencies...
Traceback (most recent call last):
  File "seeker.py", line 32, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by thewhiteh4t** [comment]
@Ghostpsycho this is not a seeker issue, your pip3 isn't working properly, please search errors on google, closing issue.
