### ISSUE TITLE
[-] pip3 is not Installed!

### ISSUE THREAD

**Issue by iakashranjan** [thewhiteh4t/seeker#273]
Also
pip3 is not installing

**Comment by thewhiteh4t** [comment]
@iakashranjan pip3 is not a part of seeker, it is required to install dependencies used by seeker, please search on google on how to install pip3

**Comment by iakashranjan** [comment]
> @iakashranjan pip3 is not a part of seeker, it is required to install dependencies used by seeker, please search on google on how to install pip3

But pkg not locate

**Comment by thewhiteh4t** [comment]
@iakashranjan that is a pip issue not a seeker issue

**Comment by iakashranjan** [comment]
> @iakashranjan that is a pip issue not a seeker issue

But how can I handle this

**Comment by thewhiteh4t** [comment]
@iakashranjan google about it and find a fix
