### ISSUE TITLE
Whatsapp path image error

### ISSUE THREAD

**Issue by Meilo14** [thewhiteh4t/seeker#278]
I have this problem in termux (seeker 1.2.5)=
Path to Group Img (Best Size : 300x300): /Internal storage/Download/raika125.jpg

[-] Exception : [Errno 2] No such file or directory: '/Internal storage/Download/raika125.jpg'

**Comment by thewhiteh4t** [comment]
@Meilo14 use absolute path

**Comment by Meilo14** [comment]
@thewhiteh4t what is the absolute path? 
Can you wjite any example?

**Comment by thewhiteh4t** [comment]
@Meilo14 refer to https://www.linux.com/training-tutorials/absolute-path-vs-relative-path-linuxunix/#:~:text=An%20absolute%20path%20is%20defined,of%20actual%20filesystem%20from%20%2F%20directory.

**Comment by HumanInjection** [comment]
Maybe you can change the permittion
example chmod 777 ImageRandom.jpeg

**Comment by mr-red-cat** [comment]
> I have this problem in termux (seeker 1.2.5)= Path to Group Img (Best Size : 300x300): /Internal storage/Download/raika125.jpg
> 
> [-] Exception : [Errno 2] No such file or directory: '/Internal storage/Download/raika125.jpg'



> I have this problem in termux (seeker 1.2.5)= Path to Group Img (Best Size : 300x300): /Internal storage/Download/raika125.jpg
> 
> [-] Exception : [Errno 2] No such file or directory: '/Internal storage/Download/raika125.jpg'

How to slow

**Comment by Devalantin** [comment]
> I have this problem in termux (seeker 1.2.5)=
> Path to Group Img (Best Size : 300x300): /Internal storage/Download/raika125.jpg
> 
> [-] Exception : [Errno 2] No such file or directory: '/Internal storage/Download/raika125.jpg'

Use
/data/data/com.termux/files/home/storage/pictures/" name of image"
