### ISSUE TITLE
Traceback (most recent call last):   File "/root/seeker/./seeker.py", line 32, in <module>     import requests ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by Rajmsr** [thewhiteh4t/seeker#280]

**Comment by thewhiteh4t** [comment]
@Rajmsr check `install.log` file for errors

**Comment by Rajmsr** [comment]
here is my 
[install.log](https://github.com/thewhiteh4t/seeker/files/6418956/install.log)

**Comment by thewhiteh4t** [comment]
@Rajmsr error is in the last line of the log file, some packages are missing which you need to install first, this is not an issue with seeker but your configuration, closing this issue.

**Comment by blacklightning71** [comment]
Thanks
