### ISSUE TITLE
Seeker opening error 

### ISSUE THREAD

**Issue by sonofmna** [thewhiteh4t/seeker#282]
Sir when i run seeker it open but after he give me a error like that mention in screen shot.![Screenshot_20210506-133333.png](https://user-images.githubusercontent.com/83090671/117268377-a7d11600-ae70-11eb-8a2f-102a6c5df8f6.png)

**Comment by sonofmna** [comment]
Chwcking serveo stastus offline

**Comment by sonofmna** [comment]
Sir how to i fix it

**Comment by thewhiteh4t** [comment]
@sonofmna read instructions in README

**Comment by sonofmna** [comment]
Readme command not working sir please give me some instructions

**Comment by thewhiteh4t** [comment]
@sonofmna it is working fine
You need to learn some basics of linux first before using tools like this

**Comment by irfhan727** [comment]
![Screenshot_2021-08-16-08-02-44-76_f598e1360c96b5a5aa16536c303cff92](https://user-images.githubusercontent.com/69303192/129843738-626daa35-c20e-485c-abbe-57c32abf7ddd.jpg)
Sir showing this problem how to solve it

**Comment by irfhan727** [comment]
![IMG_20210817_115304](https://user-images.githubusercontent.com/69303192/129843799-51d7c3f8-45ac-476a-ba82-0d9058d0caf0.jpg)
Sir showing this problem how to solve it

**Comment by sovo-code** [comment]
![image](https://user-images.githubusercontent.com/79244453/132464916-57481e09-7154-41e5-90f0-f62d59e7ebea.png)
