### ISSUE TITLE
How to create a template. 

### ISSUE THREAD

**Issue by Zmotala36** [thewhiteh4t/seeker#283]
hey, i just wanted to start off with this is a great tool and I really enjoy using It. one thing however i would like to know is how to create your own template for this tool?

**Comment by Resousse** [comment]
Hello @Zmotala36 , there is now a guide to explain how to create a template : https://github.com/thewhiteh4t/seeker/blob/master/createTemplate.md
Only HTML knowledge is required (no JS, PHP knowledge; for python it can be adapted from existing templates or even I can help)
