### ISSUE TITLE
I cannot open Seeker in termux

### ISSUE THREAD

**Issue by Santahydra** [thewhiteh4t/seeker#288]
Can u plzz give all steps to install and open Seeker on android I just cannot use it. Neither is it getting installed. I am quite interested in using it but it's not working for some reasons.

**Comment by thewhiteh4t** [comment]
@Santahydra errors? screenshots?

**Comment by Santahydra** [comment]
![Screenshot_2021-05-17-14-59-37-142_com termux](https://user-images.githubusercontent.com/84016735/118466619-a4ffdc00-b720-11eb-8122-0dc0037fef7e.jpg)




Does this mean that installation is complete but I cannot upload a photov

**Comment by thewhiteh4t** [comment]
@Santahydra what do you mean you cannot upload a photo ?

**Comment by Santahydra** [comment]
![Screenshot_2021-05-17-15-03-19-885_com termux](https://user-images.githubusercontent.com/84016735/118467004-0a53cd00-b721-11eb-8357-e4af047b8cf1.jpg)



I dunno but is everything else correct plzz tell me

**Comment by thewhiteh4t** [comment]
@Santahydra this is a termux issue and not a seeker issue, your permissions for termux app are not configured correctly, google for a fix

**Comment by Santahydra** [comment]
Can you please confirm whether everything else that I have done is correct or not,?? Plzz

**Comment by Santahydra** [comment]
Or have I missed some things

**Comment by thewhiteh4t** [comment]
@Santahydra yes so far steps are fine, you can check usage instructions in README

**Comment by Santahydra** [comment]
But why can know templates be uploaded
