### ISSUE TITLE
locate only public IP

### ISSUE THREAD

**Issue by steevespapillon** [thewhiteh4t/seeker#29]
HI work but only geolocat my FAI not my device...it is possible to locate my device ???
phone on french FAI
thanks

**Comment by thewhiteh4t** [comment]
How much location accuracy are you getting?

**Comment by steevespapillon** [comment]
25 miles arroud ...

**Comment by steevespapillon** [comment]
25 miles arround

**Comment by thewhiteh4t** [comment]
You mean over 1500 metres?

**Comment by thewhiteh4t** [comment]
That's too high, which device are you using and in which browser did you open the fake page?

**Comment by steevespapillon** [comment]
Hi my device is a nexus 6 phone on lineageOS and the browser is duckduckGO ....yes duckduckGo don't track you is maybe the problem ????

**Comment by steevespapillon** [comment]
i'll try like a lambda user with firefox and internet explorer to see if that change something..

**Comment by thewhiteh4t** [comment]
yes maybe that is the problem because geolocation api support is required in the browser to get coordinates, i will try duckduckGo, you can try chrome or firefox it should work

**Comment by thewhiteh4t** [comment]
yeah api is not working properly with duckduckGo maybe due to lack of full support, try chrome or firefox which majority of people use

**Comment by steevespapillon** [comment]
Thanks you for the anwser

Enjoy

Le 11 oct. 2018 13:46, "thewhiteh4t" <notifications@github.com> a écrit :

yeah api is not working properly with duckduckGo maybe due to lack of full
support, try chrome or firefox which majority of people use

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/thewhiteh4t/seeker/issues/29#issuecomment-428925107>,
or mute the thread
