### ISSUE TITLE
ngrok not working

### ISSUE THREAD

**Issue by ANON-PH03N1X** [thewhiteh4t/seeker#291]
Hi, just a little problem.
I just recently installed seeker and tried to test it, but when i entered the ngrok command nothing happened. if i learned correctly, that was supposed to give the URL. Any way to help?

**Comment by thewhiteh4t** [comment]
@ANON-PH03N1X ngrok is not a part of seeker, I used it as an example, there are more services like ngrok, lot of content is available about such services. Please open issue if it is directly related to seeker.
