### ISSUE TITLE
i dk where is the link to send the victim plz help

### ISSUE THREAD

**Issue by frogtasty** [thewhiteh4t/seeker#292]
┌──(frog㉿tastyfrog)-[~]
└─$ cd seeker      
                                                                                                                                                                                 
┌──(frog㉿tastyfrog)-[~/seeker]
└─$ python3 seeker.py -t manual  
[+] Checking Dependencies...

                        __
  ______  ____   ____  |  | __  ____ _______
 /  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/
/____  > \___  >\___  >|__|_ \ \___  >|__|
         \/      \/     \/      \/     \/        

[>] Created By : thewhiteh4t
[>] Version    : 1.2.5

[+] Checking for Updates.....[ Up-To-Date ]

[+] Skipping Serveo, start your own tunnel service manually...

[+] Select a Template : 

[0] NearYou
[1] Google Drive
[2] WhatsApp
[3] Telegram
[>] 0

[+] Loading NearYou Template...

[+] Port : 8080

[+] Starting PHP Server......[ Success ]

[+] Waiting for User Interaction...

**Comment by thewhiteh4t** [comment]
@frogtasty you need to use some tunnel service such as ngrok, closing since this is not an issue with seeker
