### ISSUE TITLE
One Time Location / Real Time Location

### ISSUE THREAD

**Issue by bboyboomer** [thewhiteh4t/seeker#294]
Is it possible to obtain user location access for a certain period of time (like real time location in social apps)?

**Comment by thewhiteh4t** [comment]
@bboyboomer do you mean tracking?

**Comment by bboyboomer** [comment]
> @bboyboomer do you mean tracking?

I do

**Comment by thewhiteh4t** [comment]
@bboyboomer i have tried to implement tracking in the past but problem is the browser security, to keep getting updated coordinates the tab in which the webpage opens need to be in focus, as soon as we minimize the browser or switch apps the tab goes out of focus and the coordinates stop updating, only way to properly track through webpage is if we keep the tab open which we dont do normally

**Comment by bboyboomer** [comment]
What a pity...so I’m another one waitin for new features and templates as well!

**Comment by thewhiteh4t** [comment]
@bboyboomer yes I am working on the new update, I am redoing some of the stuff, optimizing rest of it and this serveo will be removed

**Comment by hZeeL0124** [comment]
> @bboyboomer i have tried to implement tracking in the past but problem is the browser security, to keep getting updated coordinates the tab in which the webpage opens need to be in focus, as soon as we minimize the browser or switch apps the tab goes out of focus and the coordinates stop updating, only way to properly track through webpage is if we keep the tab open which we dont do normally

Man, I really wish this was feasible. To get the location whenever we want. I can make them click the link when they are relaxing in their home. But would be hella difficult to make them click when they are with somebody and would'nt want to particularly reveal their location.
