### ISSUE TITLE
Seeker not run after installation 

### ISSUE THREAD

**Issue by BuSh1DO** [thewhiteh4t/seeker#298]
**To Reproduce**

Steps to reproduce the behavior, we cannot fix the issue if we can't reproduce it

seeker installed on kali version 2021.2 with python3.9

the error:
![image](https://user-images.githubusercontent.com/40305340/123860370-ba6e4580-d91d-11eb-84dd-ffe0eb6c2623.png)

**Comment by C4l1b3r** [comment]
I get a status 404

**Comment by thewhiteh4t** [comment]
@BuSh1DO @C4l1b3r its working fine, tested just now, take a look
![seeker_wsl](https://user-images.githubusercontent.com/36354846/123889187-9852e280-d972-11eb-8b89-b774485285b8.PNG)

**Comment by thewhiteh4t** [comment]
make sure your `git clone` it properly

**Comment by C4l1b3r** [comment]
Yeah I was getting a tunnel issue with ngrok. It's my bad
