### ISSUE TITLE
Stuck at "Starting php server"

### ISSUE THREAD

**Issue by Sarthak2003** [thewhiteh4t/seeker#302]
**Describe the Error / Feature Request**

A clear description of what the bug or feature request is

---

**To Reproduce**

Steps to reproduce the behavior, we cannot fix the issue if we can't reproduce it

---

**Expected behavior**

A clear description of what you expected to happen.

---

**Screenshots**

Add screenshots to help explain your problem.

---

**Please complete the following information :**
 
 - OS:Android
 - OS version Android 11
 - Browser [chrome]
 - Full Browser Version [90.04430.91]

**Comment by thewhiteh4t** [comment]
plz check for errors in `seeker/logs/php.log`

**Comment by Sarthak2003** [comment]
Ah I got it thanks!!
