### ISSUE TITLE
Seeker URL Getting detected as a threat

### ISSUE THREAD

**Issue by inshalayaz** [thewhiteh4t/seeker#303]
The URL is getting compromised any solution to this?
![seeker](https://user-images.githubusercontent.com/52293580/127482490-c43f3c28-0f4f-4d2e-968a-8fcd74e4d06b.jpg)

**Comment by thewhiteh4t** [comment]
This is not an issue with seeker but the service you use for generating links, closing.

**Comment by inshalayaz** [comment]
Can you suggest what service should we use??

**Comment by Mrgadget23** [comment]
is it ngrok?

**Comment by Mrgadget23** [comment]
> This is not an issue with seeker but the service you use for generating links, closing.

is it ngrok?

**Comment by thewhiteh4t** [comment]
> > This is not an issue with seeker but the service you use for generating links, closing.
> 
> is it ngrok?
> 

yes its possible, for example ngrok was/is actually banned in russia

**Comment by Mrgadget23** [comment]
> > > This is not an issue with seeker but the service you use for generating links, closing.
> > 
> > 
> > is it ngrok?
> 
> yes its possible, for example ngrok was/is actually banned in russia

what do you alternative do you recommend to use?

**Comment by inshalayaz** [comment]
Yes I'm using ngrok

**Comment by AnolChakraborty** [comment]
@inshalayaz Use localhost.run(as Serveo is down) combined with a SSL over SSH instead of ngrok, it works better :).
