### ISSUE TITLE
pip3 not found

### ISSUE THREAD

**Issue by rohanahmed69** [thewhiteh4t/seeker#304]
when ever I start my seeker it shows the following error.

cd seeker
./seeker.py
[+] Checking Dependencies...
[-] pip3 is not Installed!
please help me out how can i solve this problem. thank you
---
![Screenshot_20210808-203840](https://user-images.githubusercontent.com/87943481/128637759-e28d40d6-5d60-44e4-b77f-7e83f61ce305.png)

 
 - Android
 - Android 10
 - chrome
 - 92.0.4515.131
 - Log files

**Comment by thewhiteh4t** [comment]
install pip3
