### ISSUE TITLE
seeker serveo offline error in kali linux

### ISSUE THREAD

**Issue by TR-BARZO-AZ** [thewhiteh4t/seeker#316]
seeker is opening but serveo is ''offline'' how can ı fix this problem 

by the way ı tried this command: python seeker.py -t manual
and ı get a syntax error with this command: File "seeker.py", line 65
    print(G + '[+]' + C + ' Checking for Updates.....', end='')
                                                           ^
SyntaxError: invalid syntax

please help me to solve this problem

**Comment by thewhiteh4t** [comment]
@TR-BARZO-AZ use `python3`

**Comment by TR-BARZO-AZ** [comment]
> @TR-BARZO-AZ use `python3`

Example code please?

My python3 version is 3.8.3

**Comment by thewhiteh4t** [comment]
@TR-BARZO-AZ step by step commands are given in readme

**Comment by TR-BARZO-AZ** [comment]
@thewhiteh4t

Tried all commands still serveo is offline please check the picture


https://ibb.co/ftQyyJt

**Comment by thewhiteh4t** [comment]
@TR-BARZO-AZ the first command in usage example is `python3 seeker.py -t manual` and I dont see that in your screenshot.
Closing because there is no issue with the tool.

**Comment by TR-BARZO-AZ** [comment]
That command is not working too you dont need to close the issue @thewhiteh4t

**Comment by thewhiteh4t** [comment]
@TR-BARZO-AZ show me by executing the exact command i have typed in the previous comment

**Comment by TR-BARZO-AZ** [comment]
> @TR-BARZO-AZ show me by executing the exact command i have typed in the previous comment

@thewhiteh4t

İt worked thanks 👍🏻👍🏻

**Comment by sick-debug** [comment]
hi it does not show exact location from ngrok now and link doesnot work on chrome some times
 can u tell me how can i fix and when i type pytho3 ./seeker.py -t manual it says seeker.py: error: unrecognized arguments: -t manual

**Comment by thewhiteh4t** [comment]
@sick-debug watch the demo video in README

**Comment by punitmahich** [comment]
{+] Checking Serveo Status...[ Offline ]
seeker [](url
![Screenshot_2022-05-03_05-38-20](https://user-images.githubusercontent.com/104825759/166432767-f654d37a-e0f9-42cd-b3ae-7afe69a79b49.png)

- )
