### ISSUE TITLE
Couldn't go farther.

### ISSUE THREAD

**Issue by Abhishek460099** [thewhiteh4t/seeker#322]
**Describe the Error / Feature Request**

A clear description of what the bug or feature request is

--- just did, "python seeker.py" in terminal. And I don't know what to do next. 

**To Reproduce**

Steps to reproduce the behavior, we cannot fix the issue if we can't reproduce it

---

**Expected behavior**

A clear description of what you expected to happen.

---

**Screenshots**

Add screenshots to help explain your problem.
![Screenshot_2021-10-17-13-44-53-71.jpg](https://user-images.githubusercontent.com/79910960/137618220-9b12dd45-dee3-4846-a859-6ae4deda06a8.jpg)

---

**Please complete the following information :**
 
 - OS: [e.g. Android or iOS]
 - OS Version [e.g. Android 11]
 - Full Browser Version [e.g. 90.04430.91]
 - Log files

**Comment by thewhiteh4t** [comment]
@Abhishek460099 follow usage instructions in readme
