### ISSUE TITLE
Error showing ssh not install

### ISSUE THREAD

**Issue by Jogesh95** [thewhiteh4t/seeker#325]
After also command 
$ pip3 install ssh 
After successful installation still not work
Showing error ssh not install
![Screenshot_2021-11-04-12-07-45-707_com termux](https://user-images.githubusercontent.com/93700319/140268822-56285f06-128c-4897-bc6a-dc1cec990bea.jpg)

**Comment by thewhiteh4t** [comment]
@Jogesh95 google how to install ssh in termux
