### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by AlphaByte-RedTeam** [thewhiteh4t/seeker#330]
Running `python3 seeker.py` receive Module Not Found Error named `requests`
```
$ python3 seeker.py -t manual -p 1337
[+] Checking Dependencies...
Traceback (most recent call last):
  File "path/to/seeker/seeker.py", line 32, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

EDIT: I have install the `requests` module using `pip install requests` and I also try `pip3 install requests`

Both method are satisfied.

EDIT: I used python version 3.10.0

**Comment by totensee** [comment]
You need to Install requests with 
pip install requests

**Comment by AlphaByte-RedTeam** [comment]
> You need to Install requests with 
> pip install requests

Hi, I have try it, but the requirement already satisfied.

NB: I forget to write detail information in my issues, I'll edit the original issues. Thank you.

**Comment by thewhiteh4t** [comment]
@AlphaByte-RedTeam can you try this : `python3 -c 'import requests'`

**Comment by AlphaByte-RedTeam** [comment]
> @AlphaByte-RedTeam can you try this : `python3 -c 'import requests'`

@thewhiteh4t I try python3 and still throw the same error, using `python -c 'import requests'` and successful
```
$ python3 -c 'import requests'                                                                                1 ⨯
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'
```

**Comment by thewhiteh4t** [comment]
@AlphaByte-RedTeam there is some issue with your python3 and modules setup which you will have to fix on your own, there is a difference in `python` and `python3` , for example in kali linux `python` is actually `python2` but that is deprecated so you need to fix your python3

**Comment by AlphaByte-RedTeam** [comment]
Oh, after fixing my python in kali, everything is going okay. Thank you :D
