### ISSUE TITLE
Port Forwarding way

### ISSUE THREAD

**Issue by koezyrs** [thewhiteh4t/seeker#332]
How do I use this tool with port forwarding instead of ngrok. I tried to port forward port 8080 but still couldn't load the site, even on my localhost! Can someone make a guide please ^^

**Comment by thewhiteh4t** [comment]
@koezyrs it will not work on localhost, it needs SSL certificate and a proper HTTPS connection

**Comment by koezyrs** [comment]
@thewhiteh4t Do you have some key words or topic that I can search for to set up SSL certificate and HTTPS connection on my pc? I tried to use cloudflare SSL point to my IP address but not work? The ngrok free domain is kind of suspicious ehh...

**Comment by thewhiteh4t** [comment]
sorry that you will have to figure out. closing since this is not an issue in seeker.
