### ISSUE TITLE
I added zoom as an option

### ISSUE THREAD

**Issue by a7maadf** [thewhiteh4t/seeker#335]
I've seen a few people asking for adding zoom option to the list of templates and I **added** it, how do I contact the owner for updating it publicly?

---

**Screenshots**

![image](https://user-images.githubusercontent.com/89315818/146722294-77c99983-fc6a-4f01-b0d5-8d95625ee512.png)

![image](https://user-images.githubusercontent.com/89315818/146722375-a9d138b9-f79e-4233-b186-36f864453f1b.png)

![image](https://user-images.githubusercontent.com/89315818/146722445-e28b1b42-3787-4229-89fa-de1d9fd28535.png)

![image](https://user-images.githubusercontent.com/89315818/146722529-9d505bd4-83fd-4a02-9a4b-7b56006644bf.png)

![image](https://user-images.githubusercontent.com/89315818/146722759-f62d3a9a-97c4-4d90-8280-a3f0257c23b1.png)

---

**Comment by pretech86** [comment]
Take the repo as fork , update it and publish it to your github account

**Comment by a7maadf** [comment]
[It's up now
](https://github.com/a7maadf/seeker)

**Comment by Dazmed707** [comment]
bump versión to 1.2.6 or 1.3.0

**Comment by a7maadf** [comment]
Done..

**Comment by Dazmed707** [comment]
could you change the final message for something better?
![image](https://user-images.githubusercontent.com/35184132/146982570-83c3c882-0665-4aa3-aab9-296799fba1b7.png)


or a message that after giving the location "wait for the host to add you to the room"

**Comment by a7maadf** [comment]
Okay sure I will

**Comment by thewhiteh4t** [comment]
@a7maadf awesome work, ping when you are done updating the final message I will push it :D
