### ISSUE TITLE
it worked fine,but recently i found that issue

### ISSUE THREAD

**Issue by Mamallann** [thewhiteh4t/seeker#34]
Traceback (most recent call last):
  File "seeker.py", line 205, in <module>
    ngrok()
  File "seeker.py", line 77, in ngrok
    subp.Popen(['./Ngrok/ngrok', 'http', '80'], stdin=subp.PIPE, stderr=subp.PIPE, stdout=subp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by thewhiteh4t** [comment]
In the recent update i removed the ngrok binary, simply run install.sh again and it will download ngrok for you and then run seeker

**Comment by thewhiteh4t** [comment]
Inside seeker directory you will see a file name install.log , please share this file

**Comment by Mamallann** [comment]
here the file
[install.log](https://github.com/thewhiteh4t/seeker/files/2618489/install.log)

**Comment by thewhiteh4t** [comment]
there are no errors but for some reason its not completing update, what are you getting if you manually run
`apt-get update`

**Comment by Mamallann** [comment]
thank you sir,now its updated and working fine  :)
