### ISSUE TITLE
" Waiting for user interaction" taking forever

### ISSUE THREAD

**Issue by Medicophoenix** [thewhiteh4t/seeker#342]
What should I do here?
![IMG_20220202_040644](https://user-images.githubusercontent.com/98555603/152063226-c90f8a1e-535a-4827-ad33-15f036d345a0.jpg)

**Comment by Medicophoenix** [comment]
Plz say what to do now.....it is not showing any url

**Comment by thewhiteh4t** [comment]
@Medicophoenix in a second terminal run ngrok as shown in usage instructions

**Comment by Medicophoenix** [comment]
Got it! Thank you
