### ISSUE TITLE
安装程序无法访问 'template/nearyou/php/info.txt'

### ISSUE THREAD

**Issue by starnotes-xj** [thewhiteh4t/seeker#343]
![问题](https://user-images.githubusercontent.com/61319276/152089603-cc6d77ba-3070-4d51-a8b0-4ee669a35d0b.png)

**Comment by thewhiteh4t** [comment]
sorry I dont understand this foreign language, what is the issue?

**Comment by starnotes-xj** [comment]
Setup cannot access' template / nearyou / PHP / info Txt 'and' template / nearyou / PHP / result Txt ': file

**Comment by thewhiteh4t** [comment]
that should not be an issue, I will update the install sript soon

**Comment by starnotes-xj** [comment]
Thanks

**Comment by starnotes-xj** [comment]
I use the link clicked by Kali, but the region and city in the IP information obtained by seeker are completely incorrect. I am in Zunyi, Guizhou, and seeker locates in Shenzhen, Guangdong

**Comment by thewhiteh4t** [comment]
@starnotes-xj the IP information section in the result is information about your internet service provider and not you, the city etc it shows is related to what the ISP has registered
