### ISSUE TITLE
No madule named packaging error

### ISSUE THREAD

**Issue by gauravmundhare** [thewhiteh4t/seeker#344]
![Screenshot_2022-02-03-21-17-06-25_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/98968603/152377269-4ef2066a-fe9d-42f1-a2aa-cdcaa5aeb7d8.jpg)

**Comment by thewhiteh4t** [comment]
@gauravmundhare `pip install packaging`
