### ISSUE TITLE
no response

### ISSUE THREAD

**Issue by OutlinedArc217** [thewhiteh4t/seeker#345]
I clicked continue，but the session interface does not respond

![Screenshot_20220208-131949484](https://user-images.githubusercontent.com/67988913/152923843-d20b0369-6ae9-433e-ad1e-703c38a7bb5d.jpg)

![Screenshot_20220208-131924538](https://user-images.githubusercontent.com/67988913/152923691-4cfad46f-17db-4192-bde0-35b760ad43af.jpg)

 
 - OS: Android 
 - OS Version Android 10
 - Browser kiwi browser
 -  90.04430.91

**Comment by NajibNour** [comment]
Im having the same issue here, tried both manual port forwarding and ngrok.
ngrok error: 
``/php/result.php                           500 Internal Server Error``

logs/php.log
```
Sat Feb 12 15:11:21 2022] 172.21.0.2:34862 Accepted
[Sat Feb 12 15:11:21 2022] PHP Fatal error:  Uncaught Error: Call to undefined function json_encode() in /root/seeker/template/gdrive/php/result.php:21
Stack trace:
#0 {main}
  thrown in /root/seeker/template/gdrive/php/result.php on line 21
[Sat Feb 12 15:11:21 2022] 172.21.0.2:34862 [500]: POST /php/result.php - Uncaught Error: Call to undefined function json_encode() in /root/seeker/template/gdrive/php/result.php:21
Stack trace:
#0 {main}
  thrown in /root/seeker/template/gdrive/php/result.php on line 21
[Sat Feb 12 15:11:21 2022] 172.21.0.2:34862 Closing
```


- Running on docker
- Tried multiple browsers/devices

**Comment by thewhiteh4t** [comment]
@NajibNour according to the log it looks like php json package is missing, try installing it for your OS, for reference check this page : https://stackoverflow.com/questions/45931208/in-php-7-0-fatal-error-uncaught-error-call-to-undefined-function-json-encode

**Comment by thewhiteh4t** [comment]
let me know if it solves the issue, I will update the install script accordingly

**Comment by NajibNour** [comment]
As i am using a docker container and it is using alpine i used: 
```apk add php7 php7-fpm php7-opcache```

No luck after installing php7

**Comment by thewhiteh4t** [comment]
@NajibNour install `php-json`

**Comment by NajibNour** [comment]
@thewhiteh4t Thank you, Installing `php-json` has fixed the issue. 
@OutlinedArc217  Does installing `php-json` also resolve this for you?

**Comment by thewhiteh4t** [comment]
nice!

**Comment by OutlinedArc217** [comment]
> @thewhiteh4t Thank you, Installing `php-json` has fixed the issue. @OutlinedArc217 Does installing `php-json` also resolve this for you?

Yes,i resolved it.Thanks.
