### ISSUE TITLE
image path for seeker  

### ISSUE THREAD

**Issue by pmrksof** [thewhiteh4t/seeker#349]
Could please some one explain that for me ? I have tried so many times but it didn’t work i'm using window

[+] Path to Group Img (Best Size : 300x300): Users/Prmksof/Desktop/image.png

[-] Exception : [Errno 2] No such file or directory: 'Users/Prmksof/Desktop/image.png'

help me someone please

**Comment by thewhiteh4t** [comment]
@pmrksof use absolute path, if you dont know what that is then learn basics first

**Comment by pmrksof** [comment]
okay got it
