### ISSUE TITLE
Failed to complete tunnel connection 

### ISSUE THREAD

**Issue by darkhacknet** [thewhiteh4t/seeker#35]
Whe I try to open the link to track the location an error message is displayed ::: please check it bro 

Failed to complete tunnel connection
The connection to https://2dac984b.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:80.

Make sure that a web service is running on localhost:80 and that it is a valid address.

The error encountered was: dial tcp [::1]:80: getsockopt: connection refused

Hope you can help us with this ! 

Thanks in advance, 
regards.

**Comment by thewhiteh4t** [comment]
Php server was not able to start, in seeker directory you will find a file `php.log` , please share this file.

**Comment by darkhacknet** [comment]
This is the content of the file bro: 

[Sun Dec  9 09:37:30 2018] Failed to listen on localhost:80 (reason: Permission denied)

**Comment by thewhiteh4t** [comment]
Execute seeker again as root

**Comment by darkhacknet** [comment]
Ok will do. It bro.

**Comment by darkhacknet** [comment]
Thanks bro now its working correctly ! uuuf =) Really this is the most precise program for obtain the location ... omg ! thanks again !

**Comment by thewhiteh4t** [comment]
Thankyou!!

**Comment by GODUGOLLAKARTHIK** [comment]
"Execute seeker again as root"
hat does it mean bro? how to do this?

**Comment by thewhiteh4t** [comment]
@GODUGOLLAKARTHIK you should pursue some Linux Basics courses on Cybrary and Udemy

**Comment by angelos567** [comment]
my ngrok link not working(tunnel  XXXXX not found).I don't what is the problem .I need your help

**Comment by angelos567** [comment]
It is phishing link
