### ISSUE TITLE
unrecognized arguments

### ISSUE THREAD

**Issue by Blueberryyt3** [thewhiteh4t/seeker#353]
Anytime i attempt to use the python3 seeker.py -t manual
it gives me this error seeker.py: error: unrecognized arguments: -t manual

Expected it to pop up with the seeker logo with the version and the creators name 
![image_2022-03-15_125722](https://user-images.githubusercontent.com/91761445/158460784-d605353b-f36b-4a16-aa17-4a05d2598ed4.png)

**Comment by sshiyab** [comment]
Hi

**Comment by Blueberryyt3** [comment]
> @Blueberryyt3 read README
![image_2022-03-16_093359](https://user-images.githubusercontent.com/91761445/158640515-01206208-63af-44aa-acb7-17f345e25864.png)

all i get is permission denied searched up a way to fic it nothing came up that helped.
