### ISSUE TITLE
after typing python3 seeker.py -help command i cannot see tunnel also after uploading image getting [-] Exception : [Errno 2] No such file or directory: "'/home/name/Downloads/image.jpg' "

### ISSUE THREAD

**Issue by satwik2305** [thewhiteh4t/seeker#358]
After running python3 seeker.py it runs successfully but while uploading image i am getting the following error
-] Exception : [Errno 2] No such file or directory: "'/home/name/Downloads/image.jpg' "

**Comment by thewhiteh4t** [comment]
@satwik2305 confirm if image exists at this path

**Comment by satwik2305** [comment]
> @satwik2305 confirm if image exists at this path

Even i have drag and dropped the image..

**Comment by thewhiteh4t** [comment]
@satwik2305 what is the version of seeker you are using? 
operating system?
which template did you use in seeker?

I will try to replicate the issue on my end

**Comment by satwik2305** [comment]
> @satwik2305 what is the version of seeker you are using? operating system? which template did you use in seeker?
> 
> I will try to replicate the issue on my end

Seeker version -1.2.6
Operating system-Ubuntu
Template - WhatsApp

**Comment by thewhiteh4t** [comment]
also remove single quotes from the path

**Comment by satwik2305** [comment]
> @satwik2305 you dont need to run seeker as root

i am getting a permission if i don't run seeker as root
![VirtualBox_Ubuntu_13_04_2022_08_09_37](https://user-images.githubusercontent.com/102942684/163089306-59908dfb-393d-4c41-81e9-01238d021cc7.png)

**Comment by satwik2305** [comment]
> also remove single quotes from the path

I tried it's not working

**Comment by thewhiteh4t** [comment]
@satwik2305 you are getting permission denied because you used it as root on first run which was not needed, delete whole seeker directory and clone fresh as normal user and run it as a normal user

and also check file permissions of the image, check owner and group of the file it should be your normal user and not root

**Comment by satwik2305** [comment]
> @satwik2305 you are getting permission denied because you used it as root on first run which was not needed, delete whole seeker directory and clone fresh as normal user and run it as a normal user
> 
> and also check file permissions of the image, check owner and group of the file it should be your normal user and not root

When i tried to remove it's giving "failed to remove seeker : Directory not empty"

**Comment by satwik2305** [comment]
Can someone share the code to install seeker successfully and manual tunneling should work.

**Comment by thewhiteh4t** [comment]
@satwik2305 everything is given in the README all you need is some linux basics, please learn basics and then begin with tools

**Comment by Sumitbelkar** [comment]
Iam downloaded seeker but I cannot get tunnel command in help
What I can do for use of tunnel command in seeker
Please help me sir
![Uploading Screenshot_2023-01-22-20-39-53-19_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by Sumitbelkar** [comment]
![Screenshot_2023-01-22-20-39-53-19_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/105590152/213923443-74621301-a20a-4410-95a9-44794d9549f1.jpg)
Iam downloaded seeker but I cannot get tunnel command in help
What I can do for use of tunnel command in seeker
Please help me sir

**Comment by thewhiteh4t** [comment]
@Sumitbelkar watch demo in README

**Comment by Sumitbelkar** [comment]
What is README

**Comment by Sumitbelkar** [comment]
Where is README ??

**Comment by Sumitbelkar** [comment]
> @Sumitbelkar watch demo in README

What is README sir??
