### ISSUE TITLE
my ngrok doest work

### ISSUE THREAD

**Issue by roypaul21** [thewhiteh4t/seeker#360]
why do I only have 1 forwarding?

![image](https://user-images.githubusercontent.com/79889856/164604670-a20c6990-ac14-471e-8731-0e6424d5cb4d.png)
please help beginner here

**Comment by thewhiteh4t** [comment]
@roypaul21 I have only shown ngrok as an example because it is popular, I am not the creator of ngrok, your query is regarding ngrok and not seeker, please ask in respective places, closing.
