### ISSUE TITLE
Line 13

### ISSUE THREAD

**Issue by WheatCorn** [thewhiteh4t/seeker#365]
Hey I need some help 
When im trying to open the seeker.py is telling my something about line 13

Here is exactly what it says

Traceback (most recent call last):
  File "/home/bathack/Desktop/Hacking_etico/seeker/./seeker.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

please help i dunno what to do and theres no videos on youtube that could help me

**Comment by thewhiteh4t** [comment]
@WheatCorn did you follow instructions given in README ?

**Comment by WheatCorn** [comment]
I did and I alredy install everything i need to but it keep saying this
Traceback (most recent call last):
  File "/home/bathack/Desktop/Hacking_etico/seeker/./seeker.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by thewhiteh4t** [comment]
@WheatCorn try `python3 -c 'import requests'`
do you get any output ?

**Comment by WheatCorn** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'

**Comment by thewhiteh4t** [comment]
@WheatCorn `pip3 install requests`

**Comment by thewhiteh4t** [comment]
@WheatCorn also share install.log file present in logs directory

**Comment by WheatCorn** [comment]
Its giving me an ERROR

ERROR: Could not find a version that satisfies the requirement requests (from versions: none)                                       
ERROR: No matching distribution found for requests  
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.                  
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

BTW sorry if im sending too much text its just i dont know what to do xd

**Comment by thewhiteh4t** [comment]
@WheatCorn yeah your pip is having issues, read the error, google for solution and figure it out

**Comment by WheatCorn** [comment]
Im trying to find for a solution but i dont know very well what i have to do, how can i solve this issue
Do you know any video or something that can help me

**Comment by thewhiteh4t** [comment]
@WheatCorn hint : `Can't connect to HTTPS URL because the SSL module is not available`
