### ISSUE TITLE
Incorrect Location

### ISSUE THREAD

**Issue by xoxo112** [thewhiteh4t/seeker#366]
i follwed the README file and tested url on me by opening in a browser of my laptop but it gives me wrong location(wrong city name).Also i checked the latitude and longitude on Google Mpas it also gives me another city name. i am one city google map is showing another city and terminal is showing another city of my country...Please help

**Comment by thewhiteh4t** [comment]
@xoxo112 you read the README but you skipped the part where it states that it is meant for smartphones and not laptops, try reading the README again

**Comment by xoxo112** [comment]
Ohh , thanku so much

**Comment by xoxo112** [comment]
i checked it on smartphone and it worked for google map but the city name in the terminal is still incorrect

**Comment by thewhiteh4t** [comment]
@xoxo112 yes that is because that data comes from `IP geolocation` which returns location of the ISP, the real location is returned by GPS which you see in the map, I have added both type of information in the result
