### ISSUE TITLE
Starting PHP server ......[failed]  

### ISSUE THREAD

**Issue by AgbokeRidwan** [thewhiteh4t/seeker#370]
![Screenshot 2022-05-18 17:59:43](https://user-images.githubusercontent.com/82034358/169195597-325a5f5a-8fa1-4320-9c56-98d0de46d837.png)
**please help me with a solution please**

A clear description of what the bug or feature request is

---

**To Reproduce**

Steps to reproduce the behavior, we cannot fix the issue if we can't reproduce it

---

**Expected behavior**

A clear description of what you expected to happen.

---

**Screenshots**

Add screenshots to help explain your problem.

---

**Please complete the following information :**
 
 - OS: [e.g. Android or iOS]
 - OS Version [e.g. Android 11]
 - Full Browser Version [e.g. 90.04430.91]
 - Log files

**Comment by thewhiteh4t** [comment]
@AgbokeRidwan share php.log inside `logs` directory

**Comment by AgbokeRidwan** [comment]
Thanks for the assistant............................... its now working

**Comment by sshiyab** [comment]
hi
bro
