### ISSUE TITLE
Seeker On VPS

### ISSUE THREAD

**Issue by willemkuijpers** [thewhiteh4t/seeker#371]
Hi,

I am trying to running seeker on a vps/website/domain but when seeker has been launched and i go the domain/ip the connection get refused so what i am doing wrong? 

Apache and Nginx are not running btw.

**Comment by thewhiteh4t** [comment]
@willemkuijpers after launching seeker try : `netstat -plnt`

**Comment by willemkuijpers** [comment]
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      103/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      316/sshd: /usr/sbin 
tcp        0      0 127.0.0.1:33060         0.0.0.0:*               LISTEN      317/mysqld          
tcp        0      0 127.0.0.1:42887         0.0.0.0:*               LISTEN      135/containerd      
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      317/mysqld          
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      17000/php           
tcp6       0      0 :::22                   :::*                    LISTEN      316/sshd: /usr/sbin 


Its running but nothing (./seeker.py -p 80)

**Comment by thewhiteh4t** [comment]
@willemkuijpers yes so we can see that port 80 is open and PHP server is working, next you need to check your firewall and add HTTPS, seeker doesn't work with HTTP which is why I use tunnels for demo

**Comment by willemkuijpers** [comment]
How to @ HTTPS ? Because when running on port 443 i get errors because not cert.

**Comment by thewhiteh4t** [comment]
@willemkuijpers that you will have to figure out
