### ISSUE TITLE
requested failed for pip and python when it installed

### ISSUE THREAD

**Issue by surajkumarpanchal** [thewhiteh4t/seeker#373]
[!] Installing Dependencies...

Python3 - Installed
PHP - Installed
Requests - Failed!
Packaging - Failed!

Log Saved : /home/weye/seeker/logs/install.log

when i tried sudo then show same error and when i go to super user it show same error

**Comment by thewhiteh4t** [comment]
@surajkumarpanchal share install.log file

**Comment by surajkumarpanchal** [comment]
![Screenshot from 2022-05-31 10-41-23](https://user-images.githubusercontent.com/104673831/171097460-6957d639-4adb-4cb3-82c2-fe8f11f110cb.png)

**Comment by thewhiteh4t** [comment]
@surajkumarpanchal yeah share the file content of install.log

**Comment by surajkumarpanchal** [comment]
![Uploading Screenshot from 2022-05-31 11-09-50.png…]()

**Comment by thewhiteh4t** [comment]
@surajkumarpanchal image is not loading

**Comment by surajkumarpanchal** [comment]
![Screenshot from 2022-05-31 11-09-50](https://user-images.githubusercontent.com/104673831/171130097-0ae5f923-358a-42a2-af94-34e046f6b11b.png)

**Comment by thewhiteh4t** [comment]
@surajkumarpanchal I am asking for content of install.log and you are sending screenshots of directories ?
