### ISSUE TITLE
Starting PHP server is failing can you please help

### ISSUE THREAD

**Issue by kadarlasathwik** [thewhiteh4t/seeker#376]
Can you please help me this issue... I had attached screenshot of error and php log file....

![image](https://user-images.githubusercontent.com/80673949/172658815-a6b586ff-4bc9-4d74-8f98-6a860411b037.png)
[php.log](https://github.com/thewhiteh4t/seeker/files/8863129/php.log)

**Comment by kadarlasathwik** [comment]
@thewhiteh4t  Can you please help?

**Comment by thewhiteh4t** [comment]
@kadarlasathwik python version?

**Comment by kadarlasathwik** [comment]
@thewhiteh4t  Python 3.8.8

**Comment by kadarlasathwik** [comment]
@thewhiteh4t  Can you please help me on this Issue.... I am unable to find what's going wrong!

**Comment by thewhiteh4t** [comment]
@kadarlasathwik upgrade your python version

**Comment by kadarlasathwik** [comment]
@thewhiteh4t  upgraded to python 3.10.5 but facing still this issue! Not able to understand where it is going wrong! Can you please help!

**Comment by kadarlasathwik** [comment]
Closed!
