### ISSUE TITLE
Traceback (most recent call last):   File "/home/usr/seeker/seeker.py", line 332, in <module>     clear()   File "/home/usr/seeker/seeker.py", line 312, in clear     with open(RESULT, 'w+'): FileNotFoundError: [Errno 2] No such file or directory: '/home/usr/seeker/logs/result.txt'

### ISSUE THREAD

**Issue by UltimatePussyDestroyer69** [thewhiteh4t/seeker#383]
I tried ti fix it by myself looking in some forums about it, but I couldn't, I have 0 idea of how to fix this lol.

**Comment by thewhiteh4t** [comment]
@UltimatePussyDestroyer69 
```
cd seeker
mkdir logs
python3 seeker.py
```

**Comment by Antpap07** [comment]
Don't work for me

**Comment by thewhiteh4t** [comment]
@Antpap07 share screenshot of command `ls` inside seeker directory

**Comment by thewhiteh4t** [comment]
fixed in https://github.com/thewhiteh4t/seeker/commit/9ceac3f0219f26c3d060bb18288c33fff117e48f

**Comment by Antpap07** [comment]
> @Antpap07 share screenshot of command `ls` inside seeker directory 

![Screenshot_2022-07-10-09-25-34-677_com.termux.jpg](https://user-images.githubusercontent.com/86918172/178133923-fcc88d35-db1f-439f-89a4-ce7a4405660d.jpg)
