### ISSUE TITLE
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/seeker/seeker.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by Irvi3ngg** [thewhiteh4t/seeker#385]
I got this message after trying to launch seeker on termux. 

My termux version: 

Linux localhost 4.19.188+ #1 SMP PREEMPT Thu Jun 16 19:01:04 CST 2022 aarch64 Android

My Python version: 
Python 3.10.5 (main, Jun  7 2022, 03:52:12) [Clang 12.0.8 (https://android.googlesource.com/toolchain/llvm-project c935d99d7 on linux

---

I used same instructions of this post.

---
 
 - OS: Android
 - OS Version 12
 - Browser Chrome

**Comment by thewhiteh4t** [comment]
@Irvi3ngg did you run `install.sh` ? if yes then share install.log file present under logs directory

**Comment by Irvi3ngg** [comment]
@thewhiteh4t sorry, I tried uninstalling and reinstalling again, running correctly, thank you!

**Comment by thewhiteh4t** [comment]
that's great! closing.
