### ISSUE TITLE
Terminal transcript

### ISSUE THREAD

**Issue by Nixo123YT** [thewhiteh4t/seeker#388]
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on freenode

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * Unstable: pkg install unstable-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

$ git clone https://github.com/thewhiteh4t/seeker.git   The program git is not installed. Install it by executing:
 pkg install git
$ installe git
No command installe found, did you mean:
 Command install in package coreutils
$
$

**Comment by thewhiteh4t** [comment]
learn linux basics and common commands before using tools
