### ISSUE TITLE
About editing/creating your own templates.

### ISSUE THREAD

**Issue by jssdnsdkjfnds** [thewhiteh4t/seeker#391]
I honestly liked the google drive template the most. It will be really nice if there was a way to make something like it that will redirect the user to the link of your choice, but without him clicking "get access" I just want a simple blank page that where the window pops up automatically and says "allow location to continue" then it will redirect the user the url you chose. If there is a possible way to make it like I want it will be really appreciated.

**Comment by thewhiteh4t** [comment]
@jssdnsdkjfnds from social engineering point of view how is it convincing? i.e. a blank page or do you have a different application in mind? please elaborate

**Comment by jssdnsdkjfnds** [comment]
> @jssdnsdkjfnds from social engineering point of view how is it convincing? i.e. a blank page or do you have a different application in mind? please elaborate

A black page would actually work. There was a website called Linklocator that generate links and works the same way as seeker, it gives exact location. First it takes to a black page with the pop up saying "please allow location to continue" and then when the user clicks it takes him to the url of your choice. Tried it and worked with many people and got their exact location, the only problem now is that Linklocator became paid sadly. 
You can make the victim thinks that the page will take him for example to see an image or a certain thing, usually they deny location or click the x button to close the pop up which takes them to the url of your choice, if you put a url of something else and tells them they need to click 'allow' on the pop up when it asks them so it can redirect them to the page they want, usually they go ahead and do it believing it will take them to the url they want, you can say it's just a random glitch that happen or something, it worked that way with me. Usually you'll wait for them they either deny or close the pop up, then it'll redirect them to a completely different link they'll ask you that the link is not working or something, I tell them it's just glitch or I just say try again but click allow on the pop up so it takes you to the link l told you about. This worked with me so many times using Linklocator in the past. You can pretend that it was just a glitch and send another link to whatever website they want just to blend in and they believe it was a random error.

**Comment by jssdnsdkjfnds** [comment]
> I honestly liked the google drive template the most. It will be really nice if there was a way to make something like it that will redirect the user to the link of your choice, but without him clicking "get access" I just want a simple blank page that where the window pops up automatically and says "allow location to continue" then it will redirect the user the url you chose. If there is a possible way to make it like I want it will be really appreciated.

It can actually work with anyone. You can add it as a new template it is very simple and a cooo idea that generally anyone can use in any situation. Unlike the google drive idea, not so many people familiar or even use google drive you get me? The blank page idea however it is simple and would work with anyone in any situation, you don't need to know if the victim uses google drive or whatever. The blank page however is really simple and powerful too and convincing, and can be used in any situation. 
I wish I know how to add templates but I'm not good at coding. 
I hope you add it as a new template, it'll be so cool and useful.

**Comment by Resousse** [comment]
Hello @jssdnsdkjfnds, there is now a guide to explain how to create a template : https://github.com/thewhiteh4t/seeker/blob/master/createTemplate.md
Only HTML knowledge is required (no JS, PHP knowledge; for python it can be adapted or I can help)
