### ISSUE TITLE
seeker without ngrok

### ISSUE THREAD

**Issue by yusuf2019** [thewhiteh4t/seeker#392]
thanks for this tool, can you explain how to run seeker on a VPS?

**Comment by thewhiteh4t** [comment]
@yusuf2019 php inbuilt server doesnt support ssl - on its own so you will have to use something like nginx server as reverse proxy to php server and you need to place ssl cert in nginx, I have not tried this but in theory it should work, I have plans on changing php server to something else but not right now

**Comment by thewhiteh4t** [comment]
if you are able to make whole thing work please share the steps briefly so I can add them in README as this is a common request

**Comment by yusuf2019** [comment]
Thank you for the answer, I will try it and give you feedback
