### ISSUE TITLE
Fetching Error

### ISSUE THREAD

**Issue by smrutiranjanbihari** [thewhiteh4t/seeker#393]
Unable to fetch information from any selections.

Stuck on loading....

Please view the `screenshot.`
![Screenshot_20220721-134259_Termux](https://user-images.githubusercontent.com/49835049/180166688-fba53710-c03e-402c-abe8-0f6ef12df323.jpg)
``

**Comment by thewhiteh4t** [comment]
@smrutiranjanbihari watch demo video in README
