### ISSUE TITLE
attribute errors

### ISSUE THREAD

**Issue by zaz19** [thewhiteh4t/seeker#397]
i got some attribute errors whenever i try to launch any of seeker's templets

![Screenshot_2022-07-29_14-00-04](https://user-images.githubusercontent.com/105560811/181715777-58c0a2c8-ec35-470a-a43d-e9e3f8c3d1c8.png)

 
 - OS : linux 
 - 5.15.0-kali3-amd64
 - mozila firefox
 - Version 91.5.0esr
 - Log files: 
 - 
alternatives.log    boot.log.1     btmp.1           dpkg.log        kern.log.2.gz        messages       README             sysstat         Xorg.1.log.old
alternatives.log.1  boot.log.2     daemon.log       dpkg.log.1      kern.log.3.gz        messages.1     runit              user.log        Xorg.2.log
apache2             boot.log.3     daemon.log.1     dpkg.log.2.gz   lastlog              messages.2.gz  samba              user.log.1      Xorg.2.log.old
apt                 boot.log.4     daemon.log.2.gz  faillog         lightdm              messages.3.gz  speech-dispatcher  user.log.2.gz   xrdp.log
auth.log            boot.log.5     daemon.log.3.gz  fontconfig.log  live                 mysql          stunnel4           user.log.3.gz   xrdp-sesman.log
auth.log.1          boot.log.6     debug            inetsim         macchanger.log       nginx          syslog             wtmp
auth.log.2.gz       boot.log.7     debug.1          journal         macchanger.log.1.gz  openvpn        syslog.1           Xorg.0.log
auth.log.3.gz       bootstrap.log  debug.2.gz       kern.log        macchanger.log.2.gz  postgresql     syslog.2.gz        Xorg.0.log.old
boot.log            btmp           debug.3.gz       kern.log.1      macchanger.log.3.gz  private        syslog.3.gz        Xorg.1.log

**Comment by thewhiteh4t** [comment]
@zaz19 what is your python version?

**Comment by zaz19** [comment]
> @zaz19 what is your python version?

its python 3.10.4

**Comment by thewhiteh4t** [comment]
@zaz19 what is the version of requests module?

**Comment by zaz19** [comment]
> @zaz19 what is the version of requests module?

request module version 2.25.1

**Comment by thewhiteh4t** [comment]
@zaz19 latest version is 2.28.1 try to update

**Comment by zaz19** [comment]
> @zaz19 latest version is 2.28.1 try to update

thank you so much sir.
its solved.
