### ISSUE TITLE
seeker doesnt work on Parrot OS

### ISSUE THREAD

**Issue by kaksatelite** [thewhiteh4t/seeker#40]
Hi, i hope you can help me, im trying to run seeker executing:
Python seeker.py 
but show me this errors

[+] Starting Ngrok...

Traceback (most recent call last):
  File "./seeker.py", line 205, in <module>
    ngrok()
  File "./seeker.py", line 77, in ngrok
    subp.Popen(['./Ngrok/ngrok', 'http', '80'], stdin=subp.PIPE, stderr=subp.PIPE, stdout=subp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

I follow all the steps, im trying to run in Parrot OS i386, 32 bits.

when im installing show the next message.

[!] Updating...

[!] Installing Dependencies...
    Python
    PHP
    wget
    unzip
    Requests

[!] Downloading Ngrok...
--2019-01-27 07:30:23--  https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
Resolving bin.equinox.io (bin.equinox.io)... 52.2.175.150, 52.55.191.55, 52.3.53.115, ...
Connecting to bin.equinox.io (bin.equinox.io)|52.2.175.150|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5084312 (4.8M) [application/octet-stream]
Saving to: ‘ngrok-stable-linux-arm.zip’

ngrok-stable-linux- 100%[===================>]   4.85M  1.37MB/s    in 3.7s    

2019-01-27 07:30:27 (1.33 MB/s) - ‘ngrok-stable-linux-arm.zip’ saved [5084312/5084312]

Archive:  ngrok-stable-linux-arm.zip
  inflating: ngrok                   

[!] Setting Permissions...

[!] Installed.

**Comment by thewhiteh4t** [comment]
Alright, so install script detected i386 as arm which is incorrect and it downloaded the wrong binary can you share the output of this command : `uname -m`

**Comment by kaksatelite** [comment]
#uname -m
i686

**Comment by kaksatelite** [comment]
─[root@parrot]─[~/Desktop/seeker]
└──╼ #uname -m
i686

**Comment by kaksatelite** [comment]
Hey bro!! Now its working, I changed this:

elif [ $arch != "aarch64" ]; then
  wget https://bin.equinox.io/a/bAxP1reZDmJ/ngrok-2.2.8-linux-386.tar.gz
  tar xf ngrok-2.2.8-linux-386.tar.gz
  mkdir Ngrok
  mv ngrok Ngrok/
  rm ngrok-2.2.8-linux-386.tar.gz

Then i run it ......

[>] Created By : thewhiteh4t
[>] Version    : 1.1.0

[+] Checking Internet Connection... Working

[+] Checking For Seeker Updates... Up-to-date

[+] Starting PHP Server...

[+] Starting Ngrok...

[+] URL : https://96a459f4.ngrok.io/nearyou/

[+] Waiting for User Interaction...


THANK YOU SO MUCH BRO!!!!

**Comment by thewhiteh4t** [comment]
I will add a case for i686.
