### ISSUE TITLE
Doesn't work when opened a ngrok link "ERR_NGROK_6022"

### ISSUE THREAD

**Issue by BehicKlncky** [thewhiteh4t/seeker#407]
I executed the python script and i copy pasted a google drive link. Also i have created a ngrok link as the youtube tutorial said.
And here is the result:

![WhatsApp Image 2022-10-26 at 18 28 14](https://user-images.githubusercontent.com/96238627/198071779-3cefd29b-6871-4a3f-a81e-d401510a5491.jpeg)

What should i do now?

**Comment by thewhiteh4t** [comment]
closing as this is not an issue with seeker, ngrok is a separate tool which I used in demo.
