### ISSUE TITLE
upon running the error message as shown pops up

### ISSUE THREAD

**Issue by DOKKAEBIx** [thewhiteh4t/seeker#410]
![eerrior](https://user-images.githubusercontent.com/65497939/200154682-c1cfba2e-8828-4421-a2b4-1541a3494f68.JPG)

**Comment by thewhiteh4t** [comment]
@DOKKAEBIx please share output of `sudo netstat -plnt`

**Comment by DOKKAEBIx** [comment]
![Capture](https://user-images.githubusercontent.com/65497939/200194864-7d25b0e4-1471-43ed-a9c9-8efccb5d65a9.JPG)

**Comment by thewhiteh4t** [comment]
@DOKKAEBIx try `pip install --upgrade urllib3`
and run seeker again
