### ISSUE TITLE
this error is coming up after entering seeker.py

### ISSUE THREAD

**Issue by Vireshwar313** [thewhiteh4t/seeker#412]
after entering seeker.py i am getting this error :-

ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by thewhiteh4t** [comment]
@Vireshwar313 add screenshots

**Comment by Vireshwar313** [comment]
![2022-11-07 17_38_27-kali-linux-2022 3-virtualbox-amd64  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/91110661/200307114-9cdb08bf-f849-4e0b-a245-40c72192c479.png)

**Comment by thewhiteh4t** [comment]
@Vireshwar313 try `pip3 install --upgrade urllib3` and run seeker again

**Comment by Vireshwar313** [comment]
![2022-11-07 17_48_21-kali-linux-2022 3-virtualbox-amd64  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/91110661/200308626-09c342f7-6cc0-425c-8872-055257c9c08f.png)

still same error

**Comment by thewhiteh4t** [comment]
@Vireshwar313 send output of :
`python3 -V`
`python3 -c "import requests"`

**Comment by Vireshwar313** [comment]
![2022-11-07 17_57_17-kali-linux-2022 3-virtualbox-amd64  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/91110661/200310250-141109f2-474b-41a1-a66a-732a447ad4d2.png)

**Comment by thewhiteh4t** [comment]
@Vireshwar313 `pip show requests`

**Comment by Vireshwar313** [comment]
![2022-11-07 18_07_04-kali-linux-2022 3-virtualbox-amd64  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/91110661/200312226-8ff96391-7d65-4d75-884c-7f6a11cf84a4.png)

**Comment by thewhiteh4t** [comment]
@Vireshwar313 `pip3 show requests`

**Comment by Vireshwar313** [comment]
![2022-11-07 18_11_40-kali-linux-2022 3-virtualbox-amd64  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/91110661/200313058-7796d086-5850-4684-bf4e-bffc71fa40e7.png)

**Comment by thewhiteh4t** [comment]
@Vireshwar313 latest requests version is 2.28.1 try updating it
`pip3 install --upgrade requests`

**Comment by thewhiteh4t** [comment]
![Uploading Screenshot_2022-11-07_18-18-34.png…]()

**Comment by Vireshwar313** [comment]
![2022-11-07 18_19_04-kali-linux-2022 3-virtualbox-amd64  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/91110661/200314569-961c864e-e875-44fa-9852-1bba12240330.png)

do i have to update these incompatible software too?

**Comment by Vireshwar313** [comment]
it worked

**Comment by thewhiteh4t** [comment]
great! closing.
