### ISSUE TITLE
unable to install it on Kali Linux; Python3, Pip, requests, packaging - Failed!

### ISSUE THREAD

**Issue by PetunyaNymos** [thewhiteh4t/seeker#417]
[!] Installing Dependencies...

Python3 - Failed!
Pip - Failed!
PHP - Installed
Requests - Failed!
Packaging - Failed!

 
 - OS: Kali Linux
 - Log files
[install.log](https://github.com/thewhiteh4t/seeker/files/10315653/install.log)

**Comment by thewhiteh4t** [comment]
@PetunyaNymos i read the log file and your apt is having issues, dependency problems along with multiple 404 not found errors, this is not related to the install script, first try to resolve apt errors and then run install script again and it should work

**Comment by papacorrect** [comment]
sudo pip install --upgrade psutil
