### ISSUE TITLE
Issue while installing seeker - python3 - failed!

### ISSUE THREAD

**Issue by VintageArmour** [thewhiteh4t/seeker#418]
Hi,

Please help me resolve the issue as I am not able to install seeker.

Below is the error log file attached.

Thanks and regards.
[install.log](https://github.com/thewhiteh4t/seeker/files/10332153/install.log)

**Comment by thewhiteh4t** [comment]
@VintageArmour how did you execute the install script?

**Comment by VintageArmour** [comment]
Yes I did all the steps as suggested and updated the apt as well but ended up with python 3 error

**Comment by thewhiteh4t** [comment]
@VintageArmour run `python3` and share screenshot

**Comment by VintageArmour** [comment]
![image](https://user-images.githubusercontent.com/121811327/210247684-bd14487d-ec84-4e66-9ac1-62f06ae09f45.png)

**Comment by thewhiteh4t** [comment]
@VintageArmour run seeker, it will work, the script is showing failed due to the apt error most probably

**Comment by VintageArmour** [comment]
![image](https://user-images.githubusercontent.com/121811327/210248811-6de80905-e86f-454a-93a1-c24cc9293cec.png)
This is what i get when I run a install script

**Comment by thewhiteh4t** [comment]
@VintageArmour that is not possible due to how browser security works

**Comment by VintageArmour** [comment]
Okay, thank you @thewhiteh4t.
