### ISSUE TITLE
Run error (Kali Linux)

### ISSUE THREAD

**Issue by NikMaster777** [thewhiteh4t/seeker#42]
I get this error upon execution:

[+] Starting Ngrok...

Traceback (most recent call last):
File "seeker.py", line 205, in 
ngrok()
File "seeker.py", line 77, in ngrok
subp.Popen(['./Ngrok/ngrok', 'http', '80'], stdin=subp.PIPE, stderr=subp.PIPE, stdout=subp.PIPE)
File "/usr/lib/python2.7/subprocess.py", line 394, in **init**
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by LimerBoy** [comment]
chmod +x install.sh
sudo install.sh

**Comment by NikMaster777** [comment]
> chmod + x install.sh 
> sudo install.sh

help
![error](https://user-images.githubusercontent.com/45216423/52441810-1c566680-2b3b-11e9-8dbe-7a8cf569c295.png)

**Comment by thewhiteh4t** [comment]
@NikMaster777 please execute `uname -m` and share output, it looks like install script downloaded ngrok for incorrect arch

**Comment by NikMaster777** [comment]
![error1](https://user-images.githubusercontent.com/45216423/52518160-cc24f480-2c5f-11e9-95fc-cab2ab6bf84f.png)

**Comment by thewhiteh4t** [comment]
i see, please share `install.log` present in seeker directory

**Comment by NikMaster777** [comment]
And how to get it? Sorry I'm new to Linux.

**Comment by thewhiteh4t** [comment]
open nautilus, it's a file manager present in kali linux, go inside seeker folder, you will see a file names install.log, drag drop it here on github

**Comment by NikMaster777** [comment]
There is no such file. What to do?

**Comment by thewhiteh4t** [comment]
try these commands : 
`cd seeker`
`chmod 777 install.sh`
`sh install.sh`
after installation completes, you will see a new file `install.log` in seeker folder

**Comment by NikMaster777** [comment]
[install.log](https://github.com/thewhiteh4t/seeker/files/2847878/install.log)

**Comment by itsmehacker** [comment]
@NikMaster777 I am also having the same arch (x86_64) kali linux and seeker is running totally fine 
![screenshot_20190210_173714](https://user-images.githubusercontent.com/37771102/52533497-a16b9680-2d5a-11e9-8e83-559e71b8fe8e.png)
![screenshot_20190210_173823](https://user-images.githubusercontent.com/37771102/52533503-af211c00-2d5a-11e9-876b-afd9c3d1e841.png)

**Comment by itsmehacker** [comment]
@NikMaster777 i would say that please repair your kali linux

**Comment by thewhiteh4t** [comment]
@NikMaster777 your install.log contains only `apt-get update` it looks like you sent it before completion of installation

**Comment by NikMaster777** [comment]
Got it. I will watch. Thank you for your help.

**Comment by thewhiteh4t** [comment]
@NikMaster777 sure, resend install.log after it completes, then we can see which version of ngrok is being downloaded

**Comment by NikMaster777** [comment]
[install.log](https://github.com/thewhiteh4t/seeker/files/2849442/install.log)

**Comment by NikMaster777** [comment]
Traceback (most recent call last):
  File "seeker/seeker.py", line 205, in <module>
    ngrok()
  File "seeker/seeker.py", line 77, in ngrok
    subp.Popen(['./Ngrok/ngrok', 'http', '80'], stdin=subp.PIPE, stderr=subp.PIPE, stdout=subp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by NikMaster777** [comment]
Thanks, it works now. But in Termux does not start. Writes something about ngrok. Ngrok in Termux need to be installed separately? Or do you need to specify a link?

**Comment by star360** [comment]
Traceback (most recent call last):
  File "./seeker.py", line 205, in <module>
    ngrok()
  File "./seeker.py", line 77, in ngrok
    subp.Popen(['./Ngrok/ngrok', 'http', '80'], stdin=subp.PIPE, stderr=subp.PIPE, stdout=subp.PIPE)
  File "/data/data/com.termux/files/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/data/data/com.termux/files/usr/lib/python3.7/subprocess.py", line 1520, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './Ngrok/ngrok': './Ngrok/ngrok'
[install.log](https://github.com/thewhiteh4t/seeker/files/2849635/install.log)

**Comment by thewhiteh4t** [comment]
@NikMaster777 please share a screenshot
@star360 in your install.log, script did not download ngrok please let the install script reach completion and then send the log, in your php log i see permission denied, because seeker needs root, execute seeker as root

**Comment by NikMaster777** [comment]
![screenshot_2019-02-11-10-52-55-010_com termux](https://user-images.githubusercontent.com/45216423/52549541-20111400-2ded-11e9-84d8-5d09078c2b9e.png)

**Comment by NikMaster777** [comment]
Another question: The link from the phone does not open, is this normal or do I have problems again?

**Comment by thewhiteh4t** [comment]
@NikMaster777 did you read instructions for Termux in README? because for termux install script and seeker are different and you have to 
`cd seeker/termux`
i have created a separate folder for it, also this does not look like default termux other than the solarized colors

**Comment by NikMaster777** [comment]
What link do I need to specify: git clone (link)?

**Comment by thewhiteh4t** [comment]
@NikMaster777 
`git clone https://github.com/thewhiteh4t/seeker.git`
`cd seeker/termux`
`chmod 777 install.sh`
`bash install.sh`

**Comment by thewhiteh4t** [comment]
![screenshot_20190211-132218_termux](https://user-images.githubusercontent.com/36354846/52550934-41c7c680-2e00-11e9-8ca4-701b91dce0ee.png)

**Comment by NikMaster777** [comment]
Thank you so much for the help !!! Everything is established. But why doesn't the link work?
Unable to access the site. The response time from c9898044.ngrok.io has been exceeded.

**Comment by thewhiteh4t** [comment]
@NikMaster777 
ctrl+c
execute seeker again if you get the same ngrok address
`pkill ngrok`
and then execute again

**Comment by NikMaster777** [comment]
And why does he open a link in google chrome, and in other browsers such an error?

**Comment by thewhiteh4t** [comment]
@NikMaster777 you are getting this error in all browsers except google chrome? this is new please share a screenshot, this should not happen

**Comment by NikMaster777** [comment]
Thank you so much for your help! I forgot to read the cache in browsers. Everything is working. THANK!!!
Only from a mobile phone does not open the link.

**Comment by NikMaster777** [comment]
Does not determine the location of the position. My location is well defined. I threw off the link to my friends, did not even identify where they are now. Only ip address is accurate.

**Comment by thewhiteh4t** [comment]
@NikMaster777 please watch demo video in README

**Comment by NikMaster777** [comment]
I saw this video. And my location is determined correctly. But when I gave the link to a friend the location is not very correctly determined. (Not at all correct.)

**Comment by thewhiteh4t** [comment]
@NikMaster777 i created seeker to target smartphones, because majority of people use smartphones more than their pcs and smartphones have gps hardware module in them, that's why if you open the link on a smartphone and give location permission you can get accuracy in a radius of 35-40m but if we talk about laptops and desktops they don't have gps hardware in them and so they fallback to ip geolocation which is not at all correct, also in case of phones if the gps is not working properly for example it takes too long to get location in apps like Google Maps then in such phones seeker may fallback to ip geolocation

**Comment by NikMaster777** [comment]
Thank you very much!!!

**Comment by apollodxb** [comment]
git clone https://github.com/thewhiteh4t/seeker.git
cd seeker/
chmod 777 install.sh
./install.sh
![Screenshot 2019-07-20 12 03 06](https://user-images.githubusercontent.com/53110531/61575932-ef43b200-aae3-11e9-8397-6e0956c2ffea.png)

**Comment by joelvenkatesh09** [comment]
I have one problem please solve it.
![Screenshot_2019-09-30-19-49-57-720_com termux](https://user-images.githubusercontent.com/48711041/65886672-62a65180-e3ba-11e9-8c33-48d2412445c7.png)

**Comment by joelvenkatesh09** [comment]
What do to next???

**Comment by thewhiteh4t** [comment]
@joelvenkatesh09 learn to read README, it's there for a reason... :/

**Comment by yasha-pixel** [comment]
how to fix this error
usage: seeker.py [-h] [-s SUBDOMAIN] [-k KML] -t TUNNEL
seeker.py: error: the following arguments are required: -t/--tunnel

**Comment by thewhiteh4t** [comment]
@yasha-pixel READ THE README!
https://github.com/thewhiteh4t/seeker/blob/master/README.md

**Comment by yasha-pixel** [comment]
вт, 8 окт. 2019 г. в 13:53, thewhiteh4t <notifications@github.com>:

**Comment by joelvenkatesh09** [comment]
👍 it's works bro tnx....

**Comment by yasha-pixel** [comment]
but how to solve this error 
Traceback (most recent call last):
File "seeker.py", line 313, in <module>
wait()
File "seeker.py", line 145, in wait
main()
File "seeker.py", line 182, in main
print(G + '[+]' + C + ' CPU Cores : ' + W + var_cores)
TypeError: can only concatenate str (not "NoneType") to str

**Comment by yasha-pixel** [comment]
pls help

**Comment by thewhiteh4t** [comment]
@yasha-pixel please create a new issue and mention : 
1. Which is the target device
2. Target browser

**Comment by yasha-pixel** [comment]
and how to do it?

**Comment by yasha-pixel** [comment]
can you explain please

**Comment by Swethan73** [comment]
[+] checking dependencies... traceback (most recent call last): file "./seeker.py" line 32 in import requests modulenotfounderror: no module named 'requests

**Comment by thewhiteh4t** [comment]
@Swethan73 `pip3 install requests`

**Comment by tadakalarakesh** [comment]
Resolve this issue:

./install.sh: line 8: Python3 - Failed!: command not found
PHP - Failed!
Requests - Failed!
Packaging - Failed!

Log Saved : /home/master/seeker/logs/install.log
