### ISSUE TITLE
[!] Installing Dependencies...  Python3 - Installed PHP - Installed Requests - Failed! Packaging - Failed!  [+] Log Saved : /data/data/com.termux/files/home/seeker/logs/install.log

### ISSUE THREAD

**Issue by Chrischoy58** [thewhiteh4t/seeker#423]
[!] Installing Dependencies...

Python3 - Installed
PHP - Installed
Requests - Failed!
Packaging - Failed!

[+] Log Saved : /data/data/com.termux/files/home/seeker/logs/install.log

**Comment by Chrischoy58** [comment]
Requests failed

**Comment by thewhiteh4t** [comment]
@Chrischoy58 read log file and check for errors

**Comment by Chrischoy58** [comment]
I find the problem

**Comment by thewhiteh4t** [comment]
good work!

**Comment by sharma1312** [comment]
> I find the problem

Please help me bro!! I'm having this problem since many days. Help me out!!
