### ISSUE TITLE
Localhost server not working 

### ISSUE THREAD

**Issue by Emdad05** [thewhiteh4t/seeker#425]
[>] Created By   : thewhiteh4t
 |---> Twitter   : https://twitter.com/thewhiteh4t
 |---> Community : https://twc1rcle.com/
[>] Version      : 1.2.8

[!] Select a Template :

[0] NearYou
[1] Google Drive
[2] WhatsApp
[3] WhatsApp Redirect
[4] Telegram
[5] Zoom
[6] Google ReCaptcha
[7] Custom Link Preview
[>] 0

[+] Loading NearYou Template...

[+] Port : 8080

[+] Starting PHP Server...[ ✔ ]

[+] Waiting for Client...[ctrl+c to exit]

But localhost server is not starting

**Comment by thewhiteh4t** [comment]
@Emdad05 what do you mean ?

**Comment by Emdad05** [comment]
> @Emdad05 what do you mean ?

I have installed the tool properly, after running it my localhost host server is not starting
>
This site can’t be reached127.0.0.1 unexpectedly closed the connection.
Try:

Checking the connection
ERR_CONNECTION_CLOSED

**Comment by thewhiteh4t** [comment]
@Emdad05 are you trying to visit `127.0.0.1:8000` in the browser? if yes then that is not going to work, check the readme page on github and watch the video under `demo`

**Comment by Emdad05** [comment]
Not 8000 its 127.0.0.1:8080

**Comment by thewhiteh4t** [comment]
@Emdad05 yes, watch the demo video

**Comment by Emdad05** [comment]
> @Emdad05 yes, watch the demo video

Yes , i watched but its running on python3, 
My error didn't solved

**Comment by thewhiteh4t** [comment]
@Emdad05 page will not open directly if you visit `127.0.0.1:8080` you need to use something like ngrok which is why I asked you to watch the demo

**Comment by Emdad05** [comment]
> @Emdad05 page will not open directly if you visit `127.0.0.1:8080` you need to use something like ngrok which is why I asked you to watch the demo

Yaa i used cloudflared it's showing 502 err

**Comment by thewhiteh4t** [comment]
@Emdad05 share screenshots

**Comment by Emdad05** [comment]
![Screenshot_2023-01-22-20-49-03-53_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/99329205/213923716-8da4ed82-c02a-4e95-8c43-767002695373.jpg)
![Screenshot_2023-01-22-20-49-38-89_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/99329205/213923719-d033bbd0-3b4a-4dfa-b259-c82ebdb2c120.jpg)
![Screenshot_2023-01-22-20-49-48-05_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/99329205/213923720-9def00d7-2ad7-47a9-b57d-b99a72b7e7b2.jpg)
 Check these

**Comment by Emdad05** [comment]
I run `cloudflared -url 8080` to generate the cloudflared link

**Comment by Emdad05** [comment]
> @Emdad05 share screenshots
 Done

**Comment by thewhiteh4t** [comment]
> I run `cloudflared -url 8080` to generate the cloudflared link

I think this is the issue, try using : `cloudflared -url localhost:8080`

**Comment by Emdad05** [comment]
> > I run `cloudflared -url 8080` to generate the cloudflared link
> 
> I think this is the issue, try using : `cloudflared --url localhost:8080`

Thank you its worked, but why `https://127.0.0.1:8080` didn't work

**Comment by thewhiteh4t** [comment]
@Emdad05 geolocation needs HTTPS otherwise it does not work, closing.
