### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by AdryanMares** [thewhiteh4t/seeker#43]
Failed to execute process './install.sh'. Reason:
exec: Exec format error
The file './install.sh' is marked as an executable but could not be run by the operating system.

**Comment by LimerBoy** [comment]
Try sudo sh install.sh

**Comment by AdryanMares** [comment]
my phone is not rooted. could this be the issue for me. also I don't have sudo, can't install it

**Comment by thewhiteh4t** [comment]
@AdryanMares which terminal emulator are you using on your android phone?

**Comment by AdryanMares** [comment]
Termux

**Comment by thewhiteh4t** [comment]
@AdryanMares Please share a screenshot of this error, because i tested again with a fresh termux install and install script is executing without errors

**Comment by AdryanMares** [comment]
This is what I got


welcome to fish, the friendly interactive shell
u0_a462@localhost ~>
git clone https://github.com/thewhiteh4t/seeker
Cloning into 'seeker'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (7/7), done.
Receiving objects:  31% (129/410), 676.01 KiB | 647.00Receiving objects:  31% (129/410), 1.33 MiB | 537.00 KReceiving objects:  32% (132/410), 1.33 MiB | 537.00 KReceiving objects:  33% (136/410), 1.33 MiB | 537.00 KReceiving objects:  34% (140/410), 1.33 MiB | 537.00 KReceiving objects:  35% (144/410), 1.33 MiB | 537.00 KReceiving objects:  36% (148/410), 1.33 MiB | 537.00 KReceiving objects:  37% (152/410), 1.33 MiB | 537.00 KReceiving objects:  38% (156/410), 1.33 MiB | 537.00 KReceiving objects:  39% (160/410), 1.33 MiB | 537.00 KReceiving objects:  40% (164/410), 1.33 MiB | 537.00 KReceiving objects:  41% (169/410), 1.33 MiB | 537.00 KReceiving objects:  42% (173/410), 1.33 MiB | 537.00 KReceiving objects:  43% (177/410), 1.33 MiB | 537.00 KReceiving objects:  44% (181/410), 1.33 MiB | 537.00 KReceiving objects:  45% (185/410), 1.33 MiB | 537.00 KReceiving objects:  46% (189/410), 1.33 MiB | 537.00 KReceiving objects:  46% (190/410), 1.71 MiB | 576.00 KReceiving objects:  46% (190/410), 2.73 MiB | 690.00 KReceiving objects:  46% (190/410), 3.86 MiB | 781.00 KReceiving objects:  46% (190/410), 5.02 MiB | 890.00 KReceiving objects:  46% (190/410), 6.15 MiB | 1.06 MiBReceiving objects:  47% (193/410), 6.15 MiB | 1.06 MiBReceiving objects:  47% (196/410), 6.95 MiB | 1.04 MiBReceiving objects:  47% (196/410), 8.17 MiB | 1.08 MiBReceiving objects:  47% (196/410), 9.52 MiB | 1.12 MiBReceiving objects:  47% (196/410), 10.77 MiB | 1.14 MiReceiving objects:  48% (197/410), 10.77 MiB | 1.14 MiReceiving objects:  49% (201/410), 10.77 MiB | 1.14 MiReceiving objects:  50% (205/410), 10.77 MiB | 1.14 MiReceiving objects:  51% (210/410), 10.77 MiB | 1.14 MiReceiving objects:  52% (214/410), 10.77 MiB | 1.14 MiReceiving objects:  53% (218/410), 10.77 MiB | 1.14 MiReceiving objects:  54% (222/410), 10.77 MiB | 1.14 MiReceiving objects:  55% (226/410), 10.77 MiB | 1.14 MiReceiving objects:  56% (230/410), 10.77 MiB | 1.14 MiReceiving objects:  57% (234/410), 10.77 MiB | 1.14 MiReceiving objects:  58% (238/410), 10.77 MiB | 1.14 MiReceiving objects:  59% (242/410), 10.77 MiB | 1.14 MiReceiving objects:  60% (246/410), 10.77 MiB | 1.14 MiReceiving objects:  61% (251/410), 10.77 MiB | 1.14 MiReceiving objects:  62% (255/410), 10.77 MiB | 1.14 MiReceiving objects:  63% (259/410), 10.77 MiB | 1.14 MiReceiving objects:  64% (263/410), 10.77 MiB | 1.14 MiReceiving objects:  65% (267/410), 10.77 MiB | 1.14 MiReceiving objects:  66% (271/410), 10.77 MiB | 1.14 MiReceiving objects:  67% (275/410), 10.77 MiB | 1.14 MiReceiving objects:  68% (279/410), 10.77 MiB | 1.14 MiReceiving objects:  69% (283/410), 10.77 MiB | 1.14 MiReceiving objects:  70% (287/410), 10.77 MiB | 1.14 MiReceiving objects:  71% (292/410), 10.77 MiB | 1.14 MiReceiving objects:  72% (296/410), 10.77 MiB | 1.14 MiReceiving objects:  73% (300/410), 10.77 MiB | 1.14 MiReceiving objects:  74% (304/410), 10.77 MiB | 1.14 MiReceiving objects:  75% (308/410), 10.77 MiB | 1.14 MiReceiving objects:  76% (312/410), 10.77 MiB | 1.14 MiReceiving objects:  77% (316/410), 10.77 MiB | 1.14 MiReceiving objects:  78% (320/410), 10.77 MiB | 1.14 MiReceiving objects:  79% (324/410), 10.77 MiB | 1.14 MiReceiving objects:  80% (328/410), 10.77 MiB | 1.14 MiReceiving objects:  81% (333/410), 10.77 MiB | 1.14 MiReceiving objects:  82% (337/410), 10.77 MiB | 1.14 MiReceiving objects:  83% (341/410), 10.77 MiB | 1.14 MiReceiving objects:  84% (345/410), 10.77 MiB | 1.14 MiReceiving objects:  85% (349/410), 10.77 MiB | 1.14 MiReceiving objects:  86% (353/410), 10.77 MiB | 1.14 MiReceiving objects:  87% (357/410), 10.77 MiB | 1.14 MiReceiving objects:  88% (361/410), 10.77 MiB | 1.14 MiReceiving objects:  89% (365/410), 10.77 MiB | 1.14 Miremote: Total 410 (delta 3), reused 8 (delta 2), pack-reused 400
Receiving objects:  90% (369/410), 10.77 MiB | 1.14 MiReceiving objects:  91% (374/410), 10.77 MiB | 1.14 MiReceiving objects:  92% (378/410), 10.77 MiB | 1.14 MiReceiving objects:  93% (382/410), 10.77 MiB | 1.14 MiReceiving objects:  94% (386/410), 10.77 MiB | 1.14 MiReceiving objects:  95% (390/410), 10.77 MiB | 1.14 MiReceiving objects:  96% (394/410), 10.77 MiB | 1.14 MiReceiving objects:  97% (398/410), 10.77 MiB | 1.14 MiReceiving objects:  98% (402/410), 10.77 MiB | 1.14 MiReceiving objects:  99% (406/410), 10.77 MiB | 1.14 MiReceiving objects: 100% (410/410), 10.77 MiB | 1.14 MiReceiving objects: 100% (410/410), 11.31 MiB | 1003.00 KiB/s, done.
Resolving deltas: 100% (205/205), done.
u0_a462@localhost ~> ls
Lazymux/  metasploit-framework/  seeker/   weeman/
Report/   ngrok*                 storage/
u0_a462@localhost ~> cd seeker/
u0_a462@localhost ~/seeker> ls
CODE_OF_CONDUCT.md  README.md    template/
Dockerfile          install.sh*  termux/
LICENSE             seeker.py*   version.txt
u0_a462@localhost ~/seeker> chmod 777 install.sh
u0_a462@localhost ~/seeker> ./install.sh
Failed to execute process './install.sh'. Reason:
exec: Exec format error
The file './install.sh' is marked as an executable but could not be run by the operating system.
u0_a462@localhost ~/seeker>

**Comment by thewhiteh4t** [comment]
okay so you are using fish in termux, `./install.sh` is not working in fish for some reason but `sh install.sh` is working, please try.
Also you can install it without running fish

**Comment by AdryanMares** [comment]
Worked, but it stopped at Ngrok. now I have ngrok.. what should I do?  uninstall version of it and let it be installed by install.sh?

**Comment by AdryanMares** [comment]
》user☆termux ~> ls
Lazymux  Report  metasploit-framework  seeker  storage  weeman
》user☆termux ~> cd seeker
》user☆termux ~> ls
CODE_OF_CONDUCT.md  README.md    php.log    termux
Dockerfile          install.log  seeker.py  version.txt
LICENSE             install.sh   template
》user☆termux ~> ./install.sh
[!] Updating...

[!] Installing Dependencies...
    Python
    PHP
    wget
    unzip
    Requests

[!] Downloading Ngrok...
Error : Unable to get Architecture!

[!] Setting Permissions...

[!] Installed.
》user☆termux ~> python2 seeker.py



[>] Created By : thewhiteh4t
[>] Version    : 1.1.0

[+] Checking Internet Connection... Working

[+] Checking For Seeker Updates... Up-to-date

[+] Starting PHP Server...

[+] Starting Ngrok...

Traceback (most recent call last):
  File "seeker.py", line 205, in <module>
    ngrok()
  File "seeker.py", line 77, in ngrok
    subp.Popen(['./Ngrok/ngrok', 'http', '80'], stdin=subp.PIPE, stderr=subp.PIPE, stdout=subp.PIPE)
  File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
》user☆termux ~>

**Comment by thewhiteh4t** [comment]
shell script was not able to detect architecture, so it did not download ngrok, if you read install steps in README, for termux you have to `cd seeker/termux`, install script for termux is different

**Comment by AdryanMares** [comment]
Working fine now , thanks

**Comment by vactum0** [comment]
Wow, I was getting exec error in 2 different packages, but in this thread got an answer!
can't run exec in fish!

**Comment by Hitkarsh** [comment]
THERE IS AN ERROR WHILE INSTALLING SEEKER 
HOW CAN I SOLVE IT?

root@yoo:~/seeker# ./install.sh
[!] Updating...
W: Failed to fetch http://http.kali.org/kali/dists/kali-rolling/InRelease  Could not connect to 192.168.3.10:3128 (192.168.3.10), connection timed out
W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/InRelease  Could not connect to 192.168.3.10:3128 (192.168.3.10), connection timed out
W: Failed to fetch https://deb.opera.com/opera-stable/dists/stable/InRelease  Could not connect to 192.168.3.10:3128 (192.168.3.10), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.

[!] Installing Dependencies...
    Python3
    PHP
    ssh
    Requests

[!] Setting Permissions...

[!] Installed.

**Comment by thewhiteh4t** [comment]
@Hitkarsh apt is not able to contact repositories, fix your internet
