### ISSUE TITLE
The link is not getting generated.

### ISSUE THREAD

**Issue by khansaad1275** [thewhiteh4t/seeker#430]
**Describe the Error / Feature Request**

I run the tool and it works normally but is not giving link.
---

**To Reproduce**

just run the tool

---

**Expected behavior**

Get a link 

---

**Screenshots**

![image](https://user-images.githubusercontent.com/32749921/216754240-d422dde9-0bc9-40f5-a816-1d300e9228fd.png)

---

**Please complete the following information :**
 
 - OS: [Android]
 - OS Version [13]
- In Termux

**Comment by thewhiteh4t** [comment]
@khansaad1275 watch the demo video, same can be done in termux

**Comment by khansaad1275** [comment]
> @khansaad1275 watch the demo video, same can be done in termux

I can't use Ngrok and i prefer cloudflared instead. Can't you just paste the generated localhost link so i can make my own tunnel ? 😅

**Comment by thewhiteh4t** [comment]
@khansaad1275 yes I just used ngrok for demo, you can use anything with similar functionality. closing.

**Comment by khansaad1275** [comment]
> @khansaad1275 yes I just used ngrok for demo, you can use anything with similar functionality. closing.

![image](https://user-images.githubusercontent.com/32749921/216755068-0c43128f-5156-4d19-80af-219e15ff0e49.png)

Bro i know how to use termux and ngrok, in your video if you see closely you will see that the port number that your script is showing is 8080 but in ngrok you are using 4040. i think the port number that this scrip is showing is just not right.

**Comment by thewhiteh4t** [comment]
@khansaad1275 if you take a closer look at ngrok terminal you can see that ngrok is running its own interface on port 4040, its own web interface runs on port 4040 and seeker is running on 8080 which I used in the ngrok command, and if I had used 4040 it would not have worked in the first place

**Comment by khansaad1275** [comment]
> @khansaad1275 if you take a closer look at ngrok terminal you can see that ngrok is running its own interface on port 4040, its own web interface runs on port 4040 and seeker is running on 8080 which I used in the ngrok command, and if I had used 4040 it would not have worked in the first place

oh I am sorry, thanks for clarifying that, but it supposed to open the page if I try to run it directly in my chrome as local host. But it's not working for me. Thanks for your responses.

**Comment by thewhiteh4t** [comment]
@khansaad1275 seeker will not work if you try to browse `127.0.0.1:8080` that is due to missing SSL and to fetch geolocation ssl is required

**Comment by PaulTumusiime** [comment]
Check on your ngrok account on the dashboard.

**Comment by khansaad1275** [comment]
> @khansaad1275 seeker will not work if you try to browse `127.0.0.1:8080` that is due to missing SSL and to fetch geolocation ssl is required

Thanks, this solved everything. I just have to run a clouldflared session on 127.0.0.1:8080 and the cloudflared link will work fine. Thank you. @thewhiteh4t

**Comment by thewhiteh4t** [comment]
@khansaad1275 thanks for using the tool 🙌
