### ISSUE TITLE
ngrok 

### ISSUE THREAD

**Issue by G4k3r** [thewhiteh4t/seeker#436]
**Describe the Error / Feature Request**

A clear description of what the bug or feature request is
I'm not a fan at all of ngrok having to be the only tunneling option. i use python3 seeker.py -p 2023 and when i run telebit http 2023 it doesnt find anything  however when i run ngrok http 2023 it hosts as it should ngrok is really not my preferred method of training because in the field the people we're training wont receive a link saying you may be tricked or only accept from those that you trust. It doesn't add up. so how can this tool work in joint with other services????
---

**To Reproduce**

Steps to reproduce the behavior, we cannot fix the issue if we can't reproduce it

---

**Expected behavior**

A clear description of what you expected to happen.

---

**Screenshots**

Add screenshots to help explain your problem.

---

**Please complete the following information :**
 
 - OS: [e.g. Android or iOS]
 - OS Version [e.g. Android 11]
 - Full Browser Version [e.g. 90.04430.91]
 - Log files

**Comment by thewhiteh4t** [comment]
@G4k3r for clarity : 

1. `ngrok` is not the only tunneling option, actually there is no tunneling option integrated in seeker itself to avoid this specific issue you are having

2. I used ngrok for demonstration purpose just like you are using telebit, you can use any tunneling service

3. You can setup your own VPS with a domain and nginx proxy and host seeker on that server if you dont want to use any tunneling service

4. I tested telebit and its working fine for me, checkout the partial url in the screenshot below, **this is not an issue with seeker** check your setup and firewall to see what is causing the problem

![Screenshot_2023-04-04_11-20-06](https://user-images.githubusercontent.com/36354846/229700078-7e1e3fd4-2647-4f74-ab19-ac7cfb2ef996.png)
