### ISSUE TITLE
Template link is not generating 

### ISSUE THREAD

**Issue by kratos-is-alive** [thewhiteh4t/seeker#438]
**Describe the Error / Feature Request**

Hi, google drive template link is not generating after selecting the option.

**Comment by thewhiteh4t** [comment]
@kratos-is-alive in google drive template you need to provide a legitimate google drive link, when user clicks they are redirected to this actual drive link which you had provided

**Comment by thewhiteh4t** [comment]
@kratos-is-alive check php.log under logs directory

**Comment by kratos-is-alive** [comment]
Can not find php logs under /var/log/ also inside var/apache/ 

Getting this error , please refer to the screenshot below: 

![image](https://user-images.githubusercontent.com/66902812/235288953-bf16b444-74fe-4220-8982-af047ab07a44.png)

**Comment by thewhiteh4t** [comment]
@kratos-is-alive `php.log` file is under seeker directory, also in the screenshot it is a font issue, PHP server is working

**Comment by kratos-is-alive** [comment]
Got it, sorry for the trouble. 

this is the screenshot of the php.log under seeker dir. 

![image](https://user-images.githubusercontent.com/66902812/235292570-78f6d9e3-2478-4fd7-ad14-c78a044972aa.png)

Also, if everything is starting fine, when i send that link generated by ngrok to my self to test. 

Its not giving me the location, what can be the possible reason for this?
Below is the screenshot of the page appears when i click on the link generated by ngrok

![image](https://user-images.githubusercontent.com/66902812/235292638-f9eb8c24-ea68-411f-b69c-5a17bdf98276.png)

**Comment by thewhiteh4t** [comment]
@kratos-is-alive check output of `sudo netstat -plnt`

**Comment by kratos-is-alive** [comment]
@thewhiteh4t Here is the output: 
Seems like running fine, can you kindly check?

![image](https://user-images.githubusercontent.com/66902812/235294597-cd1e6773-ca61-4c87-808f-d377fa9860bd.png)

**Comment by thewhiteh4t** [comment]
@kratos-is-alive yes php is working on 8080, what happens if you `curl http://127.0.0.1:8080` ?

**Comment by kratos-is-alive** [comment]
Here is the curl output, this also seems fine I guess, can you please check? @thewhiteh4t 

![image](https://user-images.githubusercontent.com/66902812/235295198-1d170eb9-94ad-456a-a971-22e0f204e77f.png)

**Comment by thewhiteh4t** [comment]
@kratos-is-alive yes the server is working fine, seeker is working fine, this is a firewall issue I think, I am guessing you are using virtual box ?, you need to resolve this on your own

**Comment by kratos-is-alive** [comment]
@thewhiteh4t I am using wsl ubuntu on windows 10

**Comment by kratos-is-alive** [comment]
Sad, seems tough for me to figure out, but thanks a lot for all the replies man , and cheers this is a great tool @thewhiteh4t

**Comment by thewhiteh4t** [comment]
@kratos-is-alive it looks like your issue is related to this : https://stackoverflow.com/questions/61002681/connecting-to-wsl2-server-via-local-network

**Comment by kratos-is-alive** [comment]
Checking and trying to solve, please do not close the ticket.

**Comment by kratos-is-alive** [comment]
@thewhiteh4t I have solved this, we need need to login to dashboard.ngrok.com and copy the auth token, after that we need to configure it on our terminal first before starting the ngrok. We can close the ticket now . Thank you :D
