### ISSUE TITLE
Failed to complete tunnel connection

### ISSUE THREAD

**Issue by PIDGER** [thewhiteh4t/seeker#44]
hello, i'm having trouble with second user interaction. 
When i launch and try to open the site everything is ok(including device and location information), but when i refresh window  and try to do the same again ===>
Failed to complete tunnel connection
The connection to https://7961a49a.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:80.
Make sure that a web service is running on localhost:80 and that it is a valid address.
The error encountered was: dial tcp 127.0.0.1:80: getsockopt: connection refused

php logs file ===>
[Thu Feb  7 22:00:20 2019] Failed to listen on 0.0.0.0:80 (reason: Address already in use)

**Comment by thewhiteh4t** [comment]
@PIDGER make sure any other web server (apache, nginx, etc) is not running before executing seeker, you can check server status using commands like `service apache status` if its running stop it and then execute seeker

**Comment by PIDGER** [comment]
thx a lot! it helped
