### ISSUE TITLE
Waiting for client 

### ISSUE THREAD

**Issue by anonymouse-257** [thewhiteh4t/seeker#441]
Why didn't I got link?
![Screenshot_2023-05-23-16-26-12-89_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/thewhiteh4t/seeker/assets/111396477/fe82c52e-f6b8-4fac-a8f8-0327b4e72233)@thewhiteh4t 

A clear descrip@ `ion of what the bug or feature request is

---

**To Reproduce**

Steps to reproduce the behavior, we cannot fix the issue if we can't reproduce it

---

**Expected behavior**

A clear description of what you expected to happen.

---

**Screenshots**

Add screenshots to help explain your problem.

---

**Please complete the following information :**
 
 - OS: [e.g. Android or iOS]
 - OS Version [e.g. Android 11]
 - Full Browser Version [e.g. 90.04430.91]
 - Log files

**Comment by thewhiteh4t** [comment]
@anonymouse-257 watch demo video to know how it works, link is in README
