### ISSUE TITLE
Starting php server [×]

### ISSUE THREAD

**Issue by anonymouse-257** [thewhiteh4t/seeker#442]
A clear description of what the bug or feature request is

---

**To Reproduce**

Steps to reproduce the behavior, we cannot fix the issue if we can't reproduce it

---

**Expected behavior**

A clear description of what you expected to happen.

---

**Screensho![Screenshot_2023-05-24-13-44-14-80_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/thewhiteh4t/seeker/assets/111396477/aaef190f-d399-4f1b-964c-105fba945d24)

 What now @thewhiteh4t 
Add screenshots to help explain your problem.

---

**Please complete the following information :**
 
 - OS: [e.g. Android or iOS]
 - OS Version [e.g. Android 11]
 - Full Browser Version [e.g. 90.04430.91]
 - Log files

**Comment by thewhiteh4t** [comment]
@anonymouse-257 check php logs under seeker directory

**Comment by thewhiteh4t** [comment]
@anonymouse-257 read about logs, and their uses and then you will know the answer to `And then what?`

**Comment by animoskazyiers-oss** [comment]
im having same issue

**Comment by animoskazyiers-oss** [comment]
and idk how to check logs
