### ISSUE TITLE
Help 

Man listen I'm almost a year tryna use Seeker tool and I know that seeker is the best tool but I have to ask you one question



How do I running on tunnel mode I tried everything 

### ISSUE THREAD

**Issue by anonymouse-257** [thewhiteh4t/seeker#443]

**Comment by anonymouse-257** [comment]
@thewhiteh4t

**Comment by thewhiteh4t** [comment]
@anonymouse-257 thank you for your kind words about seeker, in the demo video (link in README) I have shown an example of using tunnel, other than that lot of other tutorials are available which you can follow.

This is not an issue regarding seeker, closing.

**Comment by anonymouse-257** [comment]
Thank you man you're the best devolper

Tnx
