### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by anonymouse-257** [thewhiteh4t/seeker#444]
Men listen I'm trying something like a year to use the seeker tool and I know that the seeker tool is the one of the best tools in termux but before I have one question @thewhiteh4t 

What did you mean when you said

Run something on tunnel I think that was ngrok or something and I didn't got it

Thank you dear

**Comment by thewhiteh4t** [comment]
@anonymouse-257 stop creating duplicate issues, you opened one for the same and I answered no need to create duplicate issues
