### ISSUE TITLE
I dont know

### ISSUE THREAD

**Issue by S1gmaxBl00d** [thewhiteh4t/seeker#448]
After entering the method for example [0], it loads and error me this.

https://github.com/thewhiteh4t/seeker/assets/135167887/c233e1da-8376-4b2d-8190-8c8de9a566cc

**Comment by Resousse** [comment]
What is the output of `pip3 freeze|grep request`?
You probably have the wrong requests version installed...

**Comment by thewhiteh4t** [comment]
@S1gmaxBl00d `pip3 install -U urllib3 requests`
