### ISSUE TITLE
Plz help (Ngrok)

### ISSUE THREAD

**Issue by LimerBoy** [thewhiteh4t/seeker#45]
error while im attempt to open ngrok url:
https://picua.org/image/xtcwAy

**Comment by LimerBoy** [comment]
All is ok, need run as root.

**Comment by alex-linux-seeker** [comment]
I have a problem with connecting to ngrok url, sometimes it works, but seldom

**Comment by thewhiteh4t** [comment]
@alex-linux-seeker the error shown in the image above means no webserver is running on port 80 on your machine, since i use port 80, seeker needs root, if you get this error again please share `php.log` file present in seeker directory, it's possible that php server is crashing
