### ISSUE TITLE
Send Result to Telegram bot

### ISSUE THREAD

**Issue by Sstgelow** [thewhiteh4t/seeker#454]
Hello Guys,

Its not error or bug. I want to send seeker result for every event to the Telegram bot. 
Kindly anyone can help for this.

Thanks

**Comment by thewhiteh4t** [comment]
@Sstgelow I think this is doable with a webhook or api, webhook should be easier, I will ping you after testing

**Comment by thewhiteh4t** [comment]
in the meantime you can write a simple program to redirect output (stdout) of seeker to the bot, you can also read result.txt file and forward that to the bot, that should be easier

**Comment by Sstgelow** [comment]
@thewhiteh4t so, put the API token in the path handle POST? Which file should i modify to insert the simple program?

**Comment by thewhiteh4t** [comment]
@Sstgelow dont modify seeker files, write a separate script which will redirect the output

**Comment by Resousse** [comment]
Can be achieved pretty easily, @thewhiteh4t , let me know if I can help on this
