### ISSUE TITLE
Error when launching Seeker

### ISSUE THREAD

**Issue by GordonCol** [thewhiteh4t/seeker#457]
[+] Loading NearYou Template...

[+] Port : 8080

[+] Starting PHP Server...Traceback (most recent call last):
  File "seeker.py", line 364, in <module>
    SERVER_PROC = server()
  File "seeker.py", line 191, in server
    utils.print(f'{C}[ {G}\u2714{C} ]{W}')
  File "/opt/seeker/utils.py", line 19, in print
    builtins.print (ftext, flush=True, **args)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2714' in position 12: ordinal not in range(128)

**Comment by Resousse** [comment]
What is your python version ?

**Comment by GordonCol** [comment]
Python 3.6.8

**Comment by Resousse** [comment]
Please update & retry : https://devguide.python.org/versions/

**Comment by muddy-blunts** [comment]
Python 3.8.10 
same error

**Comment by thewhiteh4t** [comment]
@muddy-blunts please check which python version is being used, it is possible that when you type `python3`  it is using old version instead of the 8, also upgrade to 3.10 atleast

**Comment by muddy-blunts** [comment]
@thewhiteh4t 
![image](https://github.com/thewhiteh4t/seeker/assets/55998224/6e96762c-93d2-4c1a-893c-8850a9d728fa)
python 3.10.12

**Comment by thewhiteh4t** [comment]
@muddy-blunts cool will look into it by reproducing the error

**Comment by Resousse** [comment]
@muddy-blunts , unsure it would work but could you try the following before running seeker?
`export PYTHONIOENCODING=UTF-8`

**Comment by muddy-blunts** [comment]
@Resousse Thanks it works
