### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dj22908** [thewhiteh4t/seeker#459]
Im using termux.
Whenever i tru using install.sh, it installs everything but Requests and Packaging so i cant run the script.  I tried installing the modules with pip and it still wont work, pls help

**Comment by Resousse** [comment]
Could you please put here the output of the install.sh command?

**Comment by dj22908** [comment]
Python3 - Installed
PHP - Installed
Requests - Failed!
Packaging - Failed!
Heres the log output:
./install.log: line 1: =====================: command not found
./install.log: line 2: INSTALLING: command not found
./install.log: line 3: =====================: command not found
./install.log: line 6: WARNING:: command not found
./install.log: line 8: Reading: command not found
./install.log: line 9: Building: command not found
./install.log: line 10: Reading: command not found
./install.log: line 11: syntax error near unexpected token `('
./install.log: line 11: `python is already the newest version (3.11.4-2).'

**Comment by dj22908** [comment]
Sure thing, heres the logs:

./install.log: line 1: =====================: command not found
./install.log: line 2: INSTALLING: command not found
./install.log: line 3: =====================: command not found
./install.log: line 6: WARNING:: command not found
./install.log: line 8: Reading: command not found
./install.log: line 9: Building: command not found
./install.log: line 10: Reading: command not found
./install.log: line 11: syntax error near unexpected token `('
./install.log: line 11: `python is already the newest version (3.11.4-2).'

**Comment by dj22908** [comment]
Python3 - Installed
PHP - Installed
Requests - Failed!
Packaging - Failed!

**Comment by thewhiteh4t** [comment]
@dj22908 which OS are you running?

**Comment by dj22908** [comment]
Termux

**Comment by thewhiteh4t** [comment]
@dj22908 are you using some other shell like fish etc?

**Comment by dj22908** [comment]
I dont think so?

**Comment by thewhiteh4t** [comment]
@dj22908 ok, please share a screenshot when you run `install.sh`

**Comment by dj22908** [comment]
![Screenshot_20230816_145336_Termux](https://github.com/thewhiteh4t/seeker/assets/39467712/e9c6d840-4223-4c6d-8445-47acfc831455)

**Comment by thewhiteh4t** [comment]
@dj22908 share screenshot of `install.log` file also

**Comment by dj22908** [comment]
![Uploading Screenshot_20230816_161700_Termux.jpg…]()

**Comment by dj22908** [comment]
![Screenshot_20230816_161700_Termux](https://github.com/thewhiteh4t/seeker/assets/39467712/35906164-7dcb-43c0-838a-1ed4c6940cdc)

**Comment by thewhiteh4t** [comment]
@dj22908 this is not the full log

**Comment by thewhiteh4t** [comment]
@Sjitnag pip3 install psutil

**Comment by Sjitnag** [comment]
> 

Thank you so much dear.…. Love you ❤️❤️
