### ISSUE TITLE
My error in psutill library it gave me this screen when i opened seeker script 

### ISSUE THREAD

**Issue by Tiracrack** [thewhiteh4t/seeker#462]
**Describe the Error / Feature Request**

A clear description of what the bug or feature request is

---

**To Reproduce**

Steps to reproduce the behavior, we cannot fix the issue if we can't reproduce it

---

**Expected behavior**

A clear description of what you expected to happen.

---

**Screenshots**

Add screenshots to help explain your problem.

---

**Please complete the following information :**
 
 - OS: [e.g. Android or iOS]
 - OS Version [e.g. Android 11]
 - Full Browser Version [e.g. 90.04430.91]
 - Log files

**Comment by Tiracrack** [comment]
![Screenshot_٢٠٢٣-٠٨-٢٢-١٩-٢٧-٠٣-٥٧_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/thewhiteh4t/seeker/assets/119737859/2518f605-4e7e-4fe0-8de4-705b708686dd)

**Comment by thewhiteh4t** [comment]
@Tiracrack thanks for reporting, looking into alternate solutions

**Comment by thewhiteh4t** [comment]
https://github.com/giampaolo/psutil/issues/2195

**Comment by Mpineda199** [comment]
![Screenshot_20230822_233552.jpg](https://github.com/thewhiteh4t/seeker/assets/66117885/9551fb5f-1a1a-4a9b-af69-0bd50169da09)

Psutil error

**Comment by papacorrect** [comment]
sudo pip install --upgrade psutil

**Comment by bagas354** [comment]
![Image](https://github.com/user-attachments/assets/da7c2216-86b0-4471-81d5-de47bd36eac6)

Psutil failed sir

**Comment by vamshibhaiyt07-code** [comment]
My error is psutil not installing 
Failure
