### ISSUE TITLE
Telegram Bot issue (Problem solved)

### ISSUE THREAD

**Issue by juniardoss** [thewhiteh4t/seeker#464]
**Screenshots**
![Screenshot 2023-08-26 080725](https://github.com/thewhiteh4t/seeker/assets/92383482/5f0f4762-7097-416b-9069-cf647540e7e2)

"Unable send to Telegram bot"
I already input "token:chatID"

**Comment by Resousse** [comment]
@juniardoss , Could you test this URL in your browser : https://api.telegram.org/bot{token}/getMe
{token} should be replaced by the same token:chatId
Example : https://api.telegram.org/bot12312312:xabcdbsfdlj/getMe

Do you retrieve your informations or is it an "unauthorized error"?

There was a bug in the way the error was displayed, I proposed a fix.

**Comment by juniardoss** [comment]
i retrieved my information and not showing "unauthorized error"

**Comment by juniardoss** [comment]
> @juniardoss , Could you test this URL in your browser : [https://api.telegram.org/bot{token}/getMe](https://api.telegram.org/bot%7Btoken%7D/getMe) {token} should be replaced by the same token:chatId Example : https://api.telegram.org/bot12312312:xabcdbsfdlj/getMe
> 
> Do you retrieve your informations or is it an "unauthorized error"?
> 
> There was a bug in the way the error was displayed, I proposed a fix.

i retrieved my information and not showing "unauthorized error"

**Comment by Resousse** [comment]
ok, the token should be ok.
The seeker parameters or envvariable is supposed to have 3 : column sign
Have you appended the chatId ?

My last message was a bit wrong, the token is already something like 12312312:xabcdbsfdlj but the chatId (see detail here : https://sean-bradley.medium.com/get-telegram-chat-id-80b575520659) must be appended to the token.
So the token:chatId should be something like : 12312312:xabcdbsfdlj:088998888

**Comment by juniardoss** [comment]
> ok, the token should be ok. The seeker parameters or envvariable is supposed to have 3 : column sign Have you appended the chatId ?
> 
> My last message was a bit wrong, the token is already something like 12312312:xabcdbsfdlj but the chatId (see detail here : https://sean-bradley.medium.com/get-telegram-chat-id-80b575520659) must be appended to the token. So the token:chatId should be something like : 12312312:xabcdbsfdlj:088998888

Ok, thanks it worked 
![Screenshot 2023-08-26 202614](https://github.com/thewhiteh4t/seeker/assets/92383482/5656ca76-2d03-48cb-9a5e-f6f905161965)
![Screenshot 2023-08-26 202705](https://github.com/thewhiteh4t/seeker/assets/92383482/388cbe59-ca1c-4cf6-a045-31b578026dd5)
