### ISSUE TITLE
Python3 seeker.py not running 

### ISSUE THREAD

**Issue by ghostjoyprokash** [thewhiteh4t/seeker#466]
![Screenshot_2023-08-27-09-54-19-29_84d3000e3f4017145260f7618db1d683](https://github.com/thewhiteh4t/seeker/assets/143306862/15856219-51c5-48fc-a044-80b429c3b219)

**Comment by juniardoss** [comment]
sudo pip install --upgrade psutil

**Comment by ghostjoyprokash** [comment]
Tha

> To install psutil, you can use the following steps:
> 
> 1. Using pip:
>    Open your command-line interface (terminal) and enter the following command:
>    `pip install psutil`
>    Make sure you have Python and pip installed on your system before running this command.
> 2. Using pip3 (for Python 3):
>    If you have multiple versions of Python installed, you might need to use pip3 to ensure the package is installed for Python 3:
>    `pip3 install psutil`

Thanks bro ❤️

**Comment by ghostjoyprokash** [comment]
Thanks bro my issue is solved ❤️❤️
