### ISSUE TITLE
TBomb not working 

### ISSUE THREAD

**Issue by ghostjoyprokash** [thewhiteh4t/seeker#467]
![Screenshot_2023-08-27-12-11-02-71_84d3000e3f4017145260f7618db1d683](https://github.com/thewhiteh4t/seeker/assets/143306862/756fdaee-b825-49aa-8f3f-f0241923c144)
**Describe the Error / Feature Request**

A clear description of what the bug or feature request is

---

**To Reproduce**

Steps to reproduce the behavior, we cannot fix the issue if we can't reproduce it

---

**Expected behavior**

A clear description of what you expected to happen.

---

**Screenshots**

Add screenshots to help explain your problem.

---

**Please complete the following information :**
 
 - OS: [e.g. Android or iOS]
 - OS Version [e.g. Android 11]
 - Full Browser Version [e.g. 90.04430.91]
 - Log files

**Comment by thewhiteh4t** [comment]
@Resousse see, this is not even for seeker XD

**Comment by thewhiteh4t** [comment]
@ghostjoyprokash this issue section is for `seeker` tool only, please visit issue section of this `tbomb` tool and create your issue over there
