### ISSUE TITLE
Add seeker

### ISSUE THREAD

**Issue by rooted-cyber** [thewhiteh4t/seeker#472]
Add seeker [https://graph.org/seeker-09-19-2](url)

**Comment by thewhiteh4t** [comment]
@rooted-cyber describe your issue in detail

**Comment by zhanysch** [comment]
![seeker](https://github.com/thewhiteh4t/seeker/assets/67700712/e902e26b-7351-45fd-a75c-7e671d487922)

**Comment by zhanysch** [comment]
[!] Installing Dependencies is stuck is it  normal over 2 hr nothing happen

**Comment by thewhiteh4t** [comment]
@zhanysch its not normal, check contents of `install.log` file under `seeker/logs` directory and look for any errors

**Comment by rooted-cyber** [comment]
i want serveo link

**Comment by thewhiteh4t** [comment]
@rooted-cyber i am not the developer of serveo, visit their website for getting info and links, dont ask here
