### ISSUE TITLE
[7] Custom link preview not working properly

### ISSUE THREAD

**Issue by masshuvo** [thewhiteh4t/seeker#474]
**Describe the Error 

[7] Custom link preview not working properly: 

**Screenshots**
![Screenshot_2023-09-22-23-20-26-656_com offsec nhterm](https://github.com/thewhiteh4t/seeker/assets/108648096/fb31bbdd-2b11-429c-b53f-7e4e9de18077)

![Screenshot_2023-09-22-23-22-27-527_com android chrome](https://github.com/thewhiteh4t/seeker/assets/108648096/cd2d8617-a7de-4138-9cd0-8b00a14312db)

After selecting the option number seven, the web page is not able to present properly even after giving everything correctly. Only a plain page is displayed.

**Please complete the following information :**

I setup everything using Kali Nethunter 
 
 - OS: Android 
 - OS Version Android 12
 - Browser : chrome
 - Full Browser Version : 107.0.5304.141
 - Log files

**Comment by thewhiteh4t** [comment]
@masshuvo watch demo video, link is in README

**Comment by masshuvo** [comment]
> @masshuvo watch demo video, link is in README

The specific template is working as shown in the video you provided as an demo. 

![IMG_20230923_085847](https://github.com/thewhiteh4t/seeker/assets/108648096/512b7c3a-16af-401b-92ef-741d3e0f4638)

But I said option number 7 is not working properly.It should be checked once. 

When I select my own template from option number seven, it only shows a white blank page when a victim clicks on it.

**Comment by thewhiteh4t** [comment]
@masshuvo I asked you to watch the demo because you were trying to load it in your localhost, you need a tunnel like ngrok or some other server with HTTPS, it will not load without HTTPS, if you did use a tunnel and its still not working I can test it

**Comment by thewhiteh4t** [comment]
![Screenshot_20230923-085918.png](https://github.com/thewhiteh4t/seeker/assets/36354846/d6a7d973-a548-4318-ba9c-5bf9bb78b89c)

![Screenshot_20230923-090026.png](https://github.com/thewhiteh4t/seeker/assets/36354846/545c5bdb-e0f5-4050-b242-7720fa48fec8)

**Comment by thewhiteh4t** [comment]
@masshuvo check the screenshots, that's how it's supposed to work
