### ISSUE TITLE
Starting PHP Server Error

### ISSUE THREAD

**Issue by naimurhossain** [thewhiteh4t/seeker#475]
Please help me to fix this.
![Screenshot_2023-09-26_16_47_08](https://github.com/thewhiteh4t/seeker/assets/143959186/04ec4541-2f11-4aec-8fa9-5ef8da03b1c1)

**Comment by thewhiteh4t** [comment]
@naimurhossain update both urllib3 and requests packages

**Comment by Sadegh-bj** [comment]
> @naimurhossain update both urllib3 and requests packages

**Comment by afsalhack** [comment]
I'am getting a problem like this 👇any one can solve this![Screenshot_20231118-192203.png](https://github.com/thewhiteh4t/seeker/assets/142145848/82ef72e8-a20c-4b11-88ae-3e19c57520a8)
