### ISSUE TITLE
Code 501, message Unsupported method ('POST')

### ISSUE THREAD

**Issue by msimon36** [thewhiteh4t/seeker#48]
When visiting the ngrok generated link, all looks good on the victim side, but in the terminal window I get ONLY the following (after [+] Waiting for User Interaction...):

127.0.0.1 - - [-----PRIVATE-----] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [-----PRIVATE-----] "GET /css/main.css HTTP/1.1" 200 -
127.0.0.1 - - [-----PRIVATE-----] "GET /js/main.js HTTP/1.1" 200 -
127.0.0.1 - - [-----PRIVATE-----] "GET /js/location.js HTTP/1.1" 200 -
127.0.0.1 - - [-----PRIVATE-----] "GET /js/warpspeed.min.js HTTP/1.1" 200 -
127.0.0.1 - - [-----PRIVATE-----] "GET /js/info.js HTTP/1.1" 200 -
127.0.0.1 - - [-----PRIVATE-----] code 501, message Unsupported method ('POST')
127.0.0.1 - - [-----PRIVATE-----] "POST /php/info.php HTTP/1.1" 501 -

With no location information at all.

(*Sensitive information has been removed*)

**Comment by thewhiteh4t** [comment]
@msimon36 how can i reproduce this issue? Also this PHP Log is looking different from what i have...

**Comment by msimon36** [comment]
Well actually, when I was trying to trying to install seeker using the provided script, I got some sort of error message... In the end I just opened the script and manually entered each necessary command.

**Comment by thewhiteh4t** [comment]
Which server are you using? Your output looks like apache

**Comment by msimon36** [comment]
I used python3 -m http.server 80 &

**Comment by msimon36** [comment]
Hmm it seems after I ran the install script again normally, when I try python seeker.py, I get the following error:

[+] Starting PHP Server...

[+] Starting Ngrok...

Traceback (most recent call last):
  File "seeker.py", line 205, in <module>
    ngrok()
  File "seeker.py", line 77, in ngrok
    subp.Popen(['./Ngrok/ngrok', 'http', '80'], stdin=subp.PIPE, stderr=subp.PIPE, stdout=subp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by thewhiteh4t** [comment]
Create a php file and enter this code
```
<?php 
phpinfo(); 
?>
```
Then execute this command
`php -S 0.0.0.0:80`

And if you are using ubuntu etc, seeker and the above command needs root privileges.

**Comment by msimon36** [comment]
Ok what am I looking for?

**Comment by thewhiteh4t** [comment]
Basically if you load this php code in your browser and php info shows up then you are good to go as seeker uses php server, python server won't work

**Comment by msimon36** [comment]
Gotcha. It works perfectly fine.
I was just using the python server for "debugging"/monitoring purposes to see what files seeker was calling and what errors were happening behind the scenes.

**Comment by msimon36** [comment]
Did you take a look at the error I posted above as well?

**Comment by thewhiteh4t** [comment]
When you execute seeker a php log file will be generated in seeker directory `php.log` you can see all requests there.

**Comment by msimon36** [comment]
Oh ok

**Comment by thewhiteh4t** [comment]
Share `install.log` file, and which os are you using, execute `uname -m` what arch are you getting?

**Comment by msimon36** [comment]
How do I share files?
OS: Kali Linux (Linux KaliLinux 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64 GNU/Linux)

**Comment by msimon36** [comment]
[install.log](https://github.com/thewhiteh4t/seeker/files/2877758/install.log)

**Comment by thewhiteh4t** [comment]
Your install.log contains only apt-get update,
Let install script finish and then share the log file

**Comment by msimon36** [comment]
It just freezes at that point.

**Comment by thewhiteh4t** [comment]
Manually run apt-get update, check if it's getting stuck

**Comment by msimon36** [comment]
I get this error: 
Ign:1 https://download.docker.com/linux/debian kali-rolling InRelease
Err:2 https://download.docker.com/linux/debian kali-rolling Release
  404  Not Found [IP: 99.84.181.14 443]
Hit:3 http://archive.linux.duke.edu/kalilinux/kali kali-rolling InRelease
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/debian kali-rolling Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by thewhiteh4t** [comment]
Please take a look at this
https://docs.kali.org/general-use/kali-linux-sources-list-repositories

**Comment by msimon36** [comment]
It wasn't working even before I was getting errors so idk

**Comment by thewhiteh4t** [comment]
Your sources.list needs a single repo which is listed in the page above, your apt is not working properly

**Comment by msimon36** [comment]
Hmm, I already have that rep in sources.list...

**Comment by thewhiteh4t** [comment]
Then you should comment out extra ones and try again

**Comment by msimon36** [comment]
That's the only one uncommented

**Comment by thewhiteh4t** [comment]
So now your apt-get update command should complete properly

**Comment by msimon36** [comment]
It isn't :(
This isn't the main problem, though.
I can manually copy and paste the individual commands from the install script and seeker launches perfectly but when I visit the generated ngrok URL (on my PC, for testing) nothing happens and it just says: [+] Waiting for User Interaction...

**Comment by thewhiteh4t** [comment]
After you visit the page you have to click on Continue, for reference you can see the demo video, link is in the README

**Comment by msimon36** [comment]
I clicked continue

**Comment by thewhiteh4t** [comment]
And did you get the same message like i get in the video?

**Comment by msimon36** [comment]
Yes, I got the alert.
Btw I'm using an Azure VM so maybe their are some ports that need to be opened initially?
idk

**Comment by thewhiteh4t** [comment]
I have not tested this on azure vm

**Comment by msimon36** [comment]
It should be the same as any other Kali machine just maybe there are some ports that need to be allowed/opened?

**Comment by msimon36** [comment]
Any thoughts?

**Comment by msimon36** [comment]
Well, it looks like everything started magically working! I just completely removed seeker and tried again from scratch and everything seems to be working fine! Thank you for your help.

**Comment by ntung** [comment]
> Create a php file and enter this code
> 
> ```
> <?php 
> phpinfo(); 
> ?>
> ```
> 
> Then execute this command `php -S 0.0.0.0:80`
> 
> And if you are using ubuntu etc, seeker and the above command needs root privileges.

Thank you for sharing your solution. I have ever never known we can start a web server with the php command.
