### ISSUE TITLE
Trying to install seeker on a Raspi 4 Model B

### ISSUE THREAD

**Issue by enricozz** [thewhiteh4t/seeker#481]
I am able to install Python3, pip, and php, but fails on requests, packaging, and psutil

Using Raspberry Pi 4 Model B to install seeker on Debian 12 Bookworm (Raspbian). Followed all readme steps.

I tried running it and it also gives me an error (seen below).

Installing:
```
sudo ./install.sh
[!] Installing Dependencies...

Python3 - Installed
Pip - Installed
PHP - Installed
Requests - Failed!
Packaging - Failed!
Psutil - Failed!

[+] Log Saved : /home/user/seeker/logs/install.log
```

Running:
```
sudo python3 seeker/seeker.py -h
Traceback (most recent call last):
  File "/home/user/seeker/seeker.py", line 20, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```
 
 - OS: Debian GNU/Linux 12 (bookworm) aarch64
 - Browser: Firefox
 - Full Browser Version: Mozilla Firefox 118.0.2

**Comment by thewhiteh4t** [comment]
@enricozz read `install.log` and look for any errors

**Comment by enricozz** [comment]
The mistake is on my side. I apologize. This is a fresh install of Debian bookworm and I just had to `sudo rm /usr/lib/python3.11/EXTERNALLY-MANAGED` and now it works. Thank you.
