### ISSUE TITLE
Error when installing dependencies

### ISSUE THREAD

**Issue by Voranto** [thewhiteh4t/seeker#482]
└─$ ./install.sh
[!] Installing Dependencies...

Python3 - Failed!
Pip - Failed!
PHP - Installed
Requests - Failed!
Packaging - Failed!
Psutil - Failed!

Anyone know the solution?

**Comment by thewhiteh4t** [comment]
@Voranto check install.log file for any errors, fix them and run script again

**Comment by afsalhack** [comment]
I'am getting a problem like this 👇![Screenshot_20231118-192203.png](https://github.com/thewhiteh4t/seeker/assets/142145848/45c810ed-93b0-4513-b1c2-9c73356d7990)

**Comment by thewhiteh4t** [comment]
@afsalhack check `ps aux | grep php`

**Comment by afsalhack** [comment]
> @afsalhack check `ps aux | grep php`

Can you please tell me how to do that

**Comment by afsalhack** [comment]
> @afsalhack check `ps aux | grep php`

Ok i cleared that problem and
Now web page is not displaying

**Comment by thewhiteh4t** [comment]
@afsalhack watch demo, link is in readme
