### ISSUE TITLE
git clone https://github.com/thewhiteh4t/seeker.git

### ISSUE THREAD

**Issue by Dolkarphyang** [thewhiteh4t/seeker#486]
**Describe the Error / Feature Request**

---

**To Reproduce**

---

**Expected behavior**

---

**Screenshots**

---

**Please complete the following information :**
 
 - OS:
 - OS Version:
 - Browser:
 - Full Browser Version:

**Comment by sjbwe** [comment]
Kali Linux

fatal: Authentication failed for 'https://github.com/thewhite4t/seeker/'

zsh: no such file or directory: https://github.com/thewhiteh4t/seeker.git
