### ISSUE TITLE
Not connection with link.

### ISSUE THREAD

**Issue by XaruStar** [thewhiteh4t/seeker#49]
When i start seeker i got url and it's url not working.
In php.log : 127.0.0.1:40816 [404]: /favicon.ico - No suck file or directory

**Comment by thewhiteh4t** [comment]
Operating System?
Browser?
Attach `php.log` file

**Comment by XaruStar** [comment]
On Virtual Box i install Kali Linux. Browsers Firefox and Chrome.
[php.log](https://github.com/thewhiteh4t/seeker/files/2890595/php.log)
And I tried to use termux. Me and others couldn't go to the site.

**Comment by thewhiteh4t** [comment]
url should be like this : https://8290a78f.ngrok.io/nearyou/
are you getting a similar url?

**Comment by XaruStar** [comment]
Yes, I will try to enable the server and i got https:/d843b3ef.ngrok.io/nearyou

**Comment by thewhiteh4t** [comment]
okay you missed a `/` after nearyou in your url, if you open it without / you will get a blank page, please double check and report

**Comment by XaruStar** [comment]
I entered the url manually. My mistake

**Comment by thewhiteh4t** [comment]
so are you able to access the page after using full url?

**Comment by XaruStar** [comment]
No. I can record a video.

**Comment by thewhiteh4t** [comment]
sure that would help

**Comment by XaruStar** [comment]
https://youtu.be/zMebSOhW4TM

**Comment by thewhiteh4t** [comment]
This is looks like a problem with Ngrok, try this : 
`cd seeker/template/nearyou`
`php -S 0.0.0.0:80`

# open a new terminal

`cd seeker/Ngrok`
`./ngrok http 80`

now you should get two urls in Ngrok try visiting https url, also in this case just open ngrok url without `/nearyou/` since in first terminal you are already inside nearyou folder, see if the page loads this time, also you can try visiting `0.0.0.0` or `127.0.0.1` and it should display nearyou page

If Ngrok url does not open then i can't do much about it

**Comment by thewhiteh4t** [comment]
![kali linux-2019-02-22-00-46-38](https://user-images.githubusercontent.com/36354846/53195317-6cedb980-363b-11e9-860c-a18cc3060e8e.png)

**Comment by XaruStar** [comment]
![image](https://user-images.githubusercontent.com/47824429/53196177-6ace2f80-3628-11e9-8767-97bd0dfdc520.png)
![image](https://user-images.githubusercontent.com/47824429/53196190-7ae60f00-3628-11e9-9750-eec0f65a04f2.png)
It doesn't want to load(

**Comment by XaruStar** [comment]
Maybe my ports are closed?

**Comment by thewhiteh4t** [comment]
sorry my bad, i force nearyou to load as https so it will not open on localhost, but Ngrok is the problem in your case and i can't do anything about it unfortunately, but we can try one more thing,

`cd seeker/template/nearyou`
`touch test.php`
`nano test.php`
#add this code
```<?php
phpinfo();
?>```
`php -S 0.0.0.0:80`

#in new terminal

`cd seeker/Ngrok`
`./ngrok http 80`

#open ngrok url

`something.ngrok.io/test.php`

if php is working properly you will get phpinfo, please test
Also if your ports were closed you will get errors in php server

**Comment by XaruStar** [comment]
![image](https://user-images.githubusercontent.com/47824429/53197398-2d1ed600-362b-11e9-8ca0-de6a4f37c120.png)
Don't work, but thank you)

**Comment by XaruStar** [comment]
![image](https://user-images.githubusercontent.com/47824429/53197539-7f5ff700-362b-11e9-98d8-c1b8d70151e8.png)
php/info.txt - clean

**Comment by thewhiteh4t** [comment]
You have to add only 
<?php
phpinfo();
?>
In test.php

**Comment by XaruStar** [comment]
Don't work(

**Comment by thewhiteh4t** [comment]
Okay try visiting 0.0.0.0/test.php

**Comment by damibran** [comment]
i faced with this problem too. But i find that if i delete line with redirect to httpS in index.html, 0.0.0.0 working,but ngrok still doesnt

**Comment by damibran** [comment]
also all http sites works nice at 0.0.0.0, but https doesnt.

**Comment by damibran** [comment]
Test.php works, but as i move to index.html it doesn't work. I hope you can understand me)

**Comment by damibran** [comment]
I faced with similar problem. And as i think problem with Ngrok because 0.0.0.0/test.php works fine, but ngrok urls doesnt work at all. Maybe you can give me advice how to fix it?

**Comment by thewhiteh4t** [comment]
@damibran so your php is working fine and pages are working on localhost, problem is with Ngrok, if test.php worked with ngrok, the problem would have been with seeker but that is not the case, i will look for some solution but otherwise i can't do much in this case.

**Comment by damibran** [comment]
That's pity. Just for reference i have kali linux persistence. Thanks for your reply.

**Comment by thewhiteh4t** [comment]
@damibran 
Read this...
https://github.com/inconshreveable/ngrok/issues/557#issue-413688858

**Comment by damibran** [comment]
Yes, thanks. It helps a lot. I just connected vpn on dives where i wanted to open nearyou. But it killing conspiration)

**Comment by thewhiteh4t** [comment]
Since it's not a script / code related issue i am closing this. For further assistance please contact Ngrok devs.
