### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by GHOST21186** [thewhiteh4t/seeker#490]
**Describe the Error / Feature Request**

---Installing Dependencies...                                                                                                                                python3 - Failed!                                                              python3-pip - Failed!                                                          python3-requests - Failed!                                                     python3-packaging - Failed!                                                    python3-psutil - Failed!                                                       php - Failed!                                                                                                                                                 [+] Log Saved : /data/data/com.termux/files/home/seeker/logs/install.log

**To Reproduce**

---install

**Expected behavior**

---install smoothly 

**Screenshots**

---![Screenshot_20231226-192246.png](https://github.com/thewhiteh4t/seeker/assets/151578662/58ee1676-cf0d-4624-93b5-f1702e0902a1)

![Screenshot_20231226-191536.png](https://github.com/thewhiteh4t/seeker/assets/151578662/2ef4f4ff-0788-4f74-b342-fa63c72db463)

**Please complete the following information :**
 
 - OS:android 
 - OS Version:8.1.0
 - Browser: TERMUX 
 - Full Browser Version:0.118.0

**Comment by thewhiteh4t** [comment]
fixed in https://github.com/thewhiteh4t/seeker/commit/692e5313a143efcf1df0589f2a9cb2d4de011953
