### ISSUE TITLE
 Module not found 

### ISSUE THREAD

**Issue by vvatermelon-dev** [thewhiteh4t/seeker#494]
**Describe the Error / Feature Request**

---~/storage/seeker $ python3 seeker.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/storage/seeker/seeker.py", line 12, in <module>
    import utils
  File "/data/data/com.termux/files/home/storage/seeker/utils.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**To Reproduce**

---

**Expected behavior**

---

**Screenshots**

---

**Please complete the following information :**
 
 - OS:
 - OS Version:
 - Browser:
 - Full Browser Version:

**Comment by thewhiteh4t** [comment]
@vvatermelon-dev go through README and follow install instructions and google about the error

**Comment by vvatermelon-dev** [comment]
thanks bro
