### ISSUE TITLE
any way to shorten ngrok url or to disguise it for social enginnering 

### ISSUE THREAD

**Issue by getsecnow** [thewhiteh4t/seeker#5]
please do you know anyway to shorten ngrok url ? i tried google url shorter and doesn't work

**Comment by thewhiteh4t** [comment]
Many other services exist for this and the best way is to host these pages on a server so in that case you don't need a url shortner and ngrok

[https://bitly.com](url)
[https://www.textmagic.com/free-tools/url-shortener](url)
[https://bit.do/](url)
[https://www.lifewire.com/shortening-long-links-3486603](url)

**Comment by thewhiteh4t** [comment]
Closing this issue as this not a problem or bug in Seeker
