### ISSUE TITLE
NGROK Failed

### ISSUE THREAD

**Issue by DumisaniMathabathe** [thewhiteh4t/seeker#500]
How can I install ngrok? It says "-bash: ./ngrok: No such file or directory"
![Screenshot 2024-05-15 203959](https://github.com/thewhiteh4t/seeker/assets/162010657/31facc7e-8144-48ee-a07d-e751a87e175d)

**Comment by thewhiteh4t** [comment]
@DumisaniMathabathe lot of guides are available for using ngrok, for more issues contact ngrok developers, this issue section is for seeker only.
