### ISSUE TITLE
unable to install seeker

### ISSUE THREAD

**Issue by Daany-ish** [thewhiteh4t/seeker#515]
**Describe the Error / Feature Request**
┌──(mummy㉿mummy)-[/opt/seeker]
└─$ ./seeker.py         
Traceback (most recent call last):
  File "/opt/seeker/./seeker.py", line 12, in <module>
    import utils
  File "/opt/seeker/utils.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**To Reproduce**

---

**Expected behavior**

---

**Screenshots**

---

**Please complete the following information :**
 
 - OS: kali linux
 - OS Version:
 - Browser:
 - Full Browser Version:

**Comment by thewhiteh4t** [comment]
@Daany-ish follow instructions in README
