### ISSUE TITLE
seeker unable to Access because that link github clone link is expired

### ISSUE THREAD

**Issue by Kli-hack** [thewhiteh4t/seeker#519]
**Describe the Error / Feature Request**

---

**To Reproduce**

---

**Expected behavior**

---

**Screenshots**

---

**Please complete the following information :**
 
 - OS:
 - OS Version:
 - Browser:
 - Full Browser Version:

**Comment by Kli-hack** [comment]
![Screenshot (32)](https://github.com/user-attachments/assets/1cac24be-71d0-45cb-b326-920d9e2bc9e3)
![Uploading Screenshot (16).png…]()

**Comment by thewhiteh4t** [comment]
@Kli-hack describe your issue in detail, clone link is fine
