### ISSUE TITLE
Seeker stopped working about one week ago

### ISSUE THREAD

**Issue by broadski** [thewhiteh4t/seeker#52]
Hello, dear whiteh4t. I really like your tool, but it didn't work in my Termux for a week. At all. I've reinstall
Termux API and the seeker itself, but nothing helps. Neither with Wi-Fi, nor with Mobile Data :(
![Screenshot_2019-03-11-00-06-31](https://user-images.githubusercontent.com/44879921/54091486-9d4e8b00-4391-11e9-9d27-ad39e77b6522.png)
That's how it looks  Nothing more happend. 
Waiting with patience, 
your fan :D

**Comment by thewhiteh4t** [comment]
This is an Ngrok issue, sometimes it fails to get an address on termux, anyways i have removed Ngrok and replaced it with Serveo in latest version v1.1.1, please update and give it a go, it should work now.
Also Thankyou for your kind words :)

**Comment by broadski** [comment]
O'k, thank you very much for your support! But how can I update it? git clone is not help :(

**Comment by thewhiteh4t** [comment]
@broadski execute : 
git pull

**Comment by broadski** [comment]
Regardless, looks like the problem is on my side. 
Updating Seeker and reinstalling Termux don't helps :(
But thx for trying to help

**Comment by thewhiteh4t** [comment]
@broadski where do you live?

**Comment by broadski** [comment]
In the Russian Federation

**Comment by thewhiteh4t** [comment]
@broadski alright, Ngrok is blocked but i did not know about serveo, i cannot help you with this because this is not a script based issue, closing.
