### ISSUE TITLE
No Link Generated 

### ISSUE THREAD

**Issue by ChickenWithACrown** [thewhiteh4t/seeker#523]
When I enter the URL I want to use it doesn't give me the new URL to send. I am using Kali Linux

![image_2024-12-15_131431596](https://github.com/user-attachments/assets/017df410-ff2f-43a7-9aca-77331cc66e13)

**Comment by Olayinkaayodeji05** [comment]
Contact the programmmer @thewhite4t/seeker

**Comment by thewhiteh4t** [comment]
@ChickenWithACrown checkout some tutorials of ngrok usage, closing since this is not an issue related to seeker
