### ISSUE TITLE
Don't get Serveo URL

### ISSUE THREAD

**Issue by newhaum0** [thewhiteh4t/seeker#53]
I launch seeker and it stopping on "Getting Serveo URL..."
![Снимок экрана от 2019-03-16 14-35-27](https://user-images.githubusercontent.com/48620246/54474706-36016280-47f9-11e9-8da4-0b1325698b58.png)

**Comment by thewhiteh4t** [comment]
Are you from russia?

**Comment by newhaum0** [comment]
yes

**Comment by thewhiteh4t** [comment]
Serveo is blocked in Russia

**Comment by newhaum0** [comment]
ok, thanks

**Comment by MonaKillah** [comment]
no advance of getting serveo url, I'm from Spain

**Comment by Hawkkkkk** [comment]
is it unavailable in india too?

**Comment by thewhiteh4t** [comment]
@Hawkkkkk share output of /tmp/serveo.txt or if you are using termux seeker/termux/serveo.txt

**Comment by shivgori** [comment]
same problem i am facing. i am from india

**Comment by Hawkkkkk** [comment]
Try running it on a mobile network rather than wifi network... It worked
for me.

**Comment by thewhiteh4t** [comment]
@shivgori @Hawkkkkk serveo is down, checked on twitter, many serveo users are having problems, we will have to wait unfortunately
