### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by k1n0F** [thewhiteh4t/seeker#54]
Can you give that version 1.1.0 plz

**Comment by thewhiteh4t** [comment]
What happened?

**Comment by k1n0F** [comment]
The new version of seeker creates https://operis.serveo.net/nearyou/ just such a link, checked on a friend said that the site is not working. (my English is very bad) but I used to create a random link and it worked (I use google translator)

**Comment by thewhiteh4t** [comment]
People were having problems with Ngrok so i replaced it with Serveo, but there is one more issue and that is, serveo and ngrok both are blocked in Russia and you will have to use a vpn, if you take a look in closed issues you will find some with this same issue and i really can't do much

**Comment by k1n0F** [comment]
Thank you for explaining, without you I would not understand
