### ISSUE TITLE
Python exception on Docker

### ISSUE THREAD

**Issue by guigo2k** [thewhiteh4t/seeker#57]
[>] Created By : thewhiteh4t
[>] Version    : 1.1.1

[+] Checking Internet Connection... Working
[+] Checking For Seeker Updates... Up-to-date
[+] Starting PHP Server...
[+] Getting Serveo URL...

Traceback (most recent call last):
  File "./seeker.py", line 197, in <module>
    serveo()
  File "./seeker.py", line 79, in serveo
    proc = subp.Popen(['ssh', '-oStrictHostKeyChecking=no', '-R', '80:localhost:8080', 'serveo.net'], stdout = tmpfile, stderr = tmpfile, stdin = subp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by thewhiteh4t** [comment]
Dockerfile is not up to date, i will update soon, meanwhile you need openssh package to resolve this error, if you want to try manually execute apt-get install openssh

**Comment by thewhiteh4t** [comment]
@guigo2k Updated Dockerfile, README and added DockerHub command, should work now.
