### ISSUE TITLE
rename url 

### ISSUE THREAD

**Issue by Amirhf1** [thewhiteh4t/seeker#58]
how to change Default URL - https://cupio.serveo.net/nearyou/

**Comment by Pepepy** [comment]
In seeker.py look for the following line: proc =
subp.Popen (['ssh', '-oStrictHostKeyChecking = no', '-R', '80: localhost: 8080 ',' serveo.net '],

and modify the host local with the name you want: Ex .: 'Myhost: 80: localhost: 8080'

That will change the first part of your url

If you want to change the "NearYOU" too, you have to change the name of the folder and the redirections to the code itself

**Comment by tommboy1377** [comment]
Where can I get this

**Comment by thewhiteh4t** [comment]
@Amirhf1 @Pepepy @tommboy1377 just released v1.1.3, added argument for your choice of subdomain

Example - `python3 seeker.py --subdomain google`

your url will become : `https://google.serveo.net`

**Comment by pretech86** [comment]
Thanks for your interest .. hope for more useful tools like this from your side

**Comment by thewhiteh4t** [comment]
@pretech86 thankyou for using my tool and feedback, I am working on new stuff and updating previous tools!

**Comment by prabachandar1989** [comment]
python3 seeker.py --subdomain google 

subdomain feature is not working
