### ISSUE TITLE
add other support

### ISSUE THREAD

**Issue by zief** [thewhiteh4t/seeker#6]
i think you must add another command in install.sh for other linux distro. 
Here for antergos

sudo pacman -Syu 

pacman -S unzip wget or yaourt -S unzip wget
pacman -S apache2 php 

actually it's better to add xampp/lampp support in the script, since the script is in php

**Comment by zief** [comment]
yupz, database support is better

**Comment by thewhiteh4t** [comment]
Added support for Docker, you can now run Seeker on Arch Linux based distro using docker.
