### ISSUE TITLE
Blocked serveo in Russia

### ISSUE THREAD

**Issue by diggi543** [thewhiteh4t/seeker#60]
Hello. Why are you now use serveo instead ngrok? It's blocked and it delivers great inconvenience. Please, use another hoster or add some in-built vpn or something similar.
P.S. Sorry for my English :(

**Comment by thewhiteh4t** [comment]
@diggi543 serveo is much better because it does not need its own client it uses ssh which is available on all platforms, in ngrok people were having issues with architecture mismatch also both ngrok and serveo are blocked in russia, you will have to use a vpn of your own
