### ISSUE TITLE
Windows Install

### ISSUE THREAD

**Issue by grisuno** [thewhiteh4t/seeker#65]
y change some lines to run in windows 10

`with open('c:\\tmp\\serveo.txt','w') as tmpfile: /*line78*/
	with open('c:\\tmp\\serveo.txt', 'r') as tmpfile:` /*line 83*/

Saludos,

**Comment by thewhiteh4t** [comment]
@grisuno sorry i won't be supporting windows, if you want to run seeker on windows please use `ubuntu-wsl` or `kali linux wsl`, both are available in windows store. Closing.
