### ISSUE TITLE
In ngrok not changes site

### ISSUE THREAD

**Issue by hipp0gryph** [thewhiteh4t/seeker#68]
What me do? I write my site and replace your, but I can start Seeker, on url I see standart site NearYou. Please help me.

**Comment by thewhiteh4t** [comment]
you will have to create a separate folder for your site inside `template` folder, then you will send the link like : `https://xyz.serveo.net/<your custom site's folder name>/`

**Comment by hipp0gryph** [comment]
I take your scripts js and php, changed them, write my site and use hosting. Thanks!!!)))
