### ISSUE TITLE
Impossibility to install seeker

### ISSUE THREAD

**Issue by mortim59** [thewhiteh4t/seeker#69]
- OS: Ubuntu 18.04.2 LTS x86_64
- Kernel: 4.18.0-20-generic
- Shell: fish

Hello, I tried to install seeker but it doesn't work at all. Yet I followed all the instructions correctly.
First of all when I do'./install.sh' I have to put sudo just before to be able to execute it even with the chmod 777
And when I put sudo I get this mistake.

`E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
Reading package lists... Done
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?`

I tried it with Docker but I also have to add sudo just before, and when I put sudo it gets stuck in step 8. 
`Step 8/13 : RUN apt-get -y install python3 python3-pip php ssh >> install.log
 ---> Running in 555661b2d3f9
debconf: delaying package configuration, since apt-utils is not installed
`

**Comment by Peskoo** [comment]
Tried too.
Even if I delete the following files:
```bash
sudo rm /var/lib/apt/lists/lock
sudo rm /var/cache/apt/archives/lock
sudo rm /var/lib/dpkg/lock*
```
conf: Ubuntu 16, venv python3.4

**Comment by mortim59** [comment]
> Tried too.
> It didn't work even if I delete the following files:
> 
> ```shell
> sudo rm /var/lib/apt/lists/lock
> sudo rm /var/cache/apt/archives/lock
> sudo rm /var/lib/dpkg/lock*
> ```
> 
> conf: Ubuntu 16, venv python3.4
> 
> Edit:
> With docker
> `docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"./seeker.py\": permission denied": unknown.`

I did same on Kali Linux but not working. :(

**Comment by thewhiteh4t** [comment]
@mortim59 i see, your dpkg got interrupted, try this and report:

`sudo -s`
`rm /var/lib/dpkg/lock-frontend`

then again run install script, if it fails again with a similar lock error, remove the `lock` file, sometimes its just `lock` or in your case `lock-frontend`

also if you want to use docker, give it some time to install, its not stuck

i have not tested with fish shell, i will also test on ubuntu with fish

@Peskoo you are also using fish shell?

**Comment by thewhiteh4t** [comment]
@mortim59 @Peskoo Tested on Ubuntu 19.04 with a working `apt` and `fish`, successfully installed and executing, i will test docker now, also i have made changes to `install.sh` so please do this first :
`cd seeker`
`git pull`
`bash install.sh`

**Comment by mortim59** [comment]
> @mortim59 @Peskoo Tested on Ubuntu 19.04 with a working `apt` and `fish`, successfully installed and executing, i will test docker now, also i have made changes to `install.sh` so please do this first :
> `cd seeker`
> `git pull`
> `bash install.sh`
Thank you! It works... At first by following your solution I had another problem
``
E:Failed to fetch http://ppa.launchpad.net/noobslab/deepin-sc/ubuntu/dists/xenial/main/source/Sources 404  Not Found, E:Some index files failed to download. They have been ignored, or old ones used instead.
But I followed this topic and solved the problem
https://askubuntu.com/questions/934544/i-get-the-error-failed-to-download-repository-information-check-your-internet/934558#934558
``
