### ISSUE TITLE
can I move the template on my website

### ISSUE THREAD

**Issue by capucine19** [thewhiteh4t/seeker#71]
can I move the template on my server for personalized the link and put the website online.
it's possible ?

thanks u.
sorry for for the faults i speak french.

**Comment by thewhiteh4t** [comment]
yes it is possible

**Comment by capucine19** [comment]
how? you just have to move everything on a host where i need a vps ?

**Comment by thewhiteh4t** [comment]
yes you need a vps where you can install seeker, in the coming days i will be adding support for custom templates which you can pass as arguments

**Comment by capucine19** [comment]
Thanks u ❤️

**Comment by thewhiteh4t** [comment]
Closing.
