### ISSUE TITLE
The generated url displays JSON data

### ISSUE THREAD

**Issue by mortim59** [thewhiteh4t/seeker#73]
Hello, when the serveo url are generate, there displays JSON datas but not the website
<img src="http://imgur.com/Ry4LCAcl.png" alt="screenshot json data serveo">
I've installed correctly php, python3, ssh , requests and ngrok. 
The strange thing is that I don't have any errors when I run ```python3 seeker.py```

**Comment by thewhiteh4t** [comment]
@mortim59 which seeker version are you using? latest version is 1.1.3 and it does not use Ngrok

**Comment by mortim59** [comment]
> @mortim59 which seeker version are you using? latest version is 1.1.3 and it does not use Ngrok
Yes, it's the latest version , I verified this with: ``git pull``

**Comment by thewhiteh4t** [comment]
@mortim59 so when you open this link provided by seeker you get json output instead of NearYou page? Which browser are you using to test? And did you test on your phone? Same result?

**Comment by mortim59** [comment]
First question: yes
Second question: I use firefox (the latest version) 
Third question: In my phone it's the same result

**Comment by thewhiteh4t** [comment]
@mortim59 this is very strange, i tested again with both firefox quantum and firefox-esr, google chrome, both on desktop and phone but i am unable to reproduce this

**Comment by mortim59** [comment]
No problem , thanks anyway
