### ISSUE TITLE
Seeker

### ISSUE THREAD

**Issue by principios1** [thewhiteh4t/seeker#74]
Hi. Can ngrok version?

**Comment by thewhiteh4t** [comment]
No sorry, ngrok was causing a lot of problems for a lot of users and it also needs a separate client, serveo is much more efficient and fast for this project and it uses ssh which is included in all linux os.

**Comment by principios1** [comment]
in Russia blocks.

**Comment by thewhiteh4t** [comment]
@principios1 if you look at previous closed issues, ngrok is also blocked in russia
