### ISSUE TITLE
How long does the link take effect after I start it?

### ISSUE THREAD

**Issue by bit4lifeonline** [thewhiteh4t/seeker#80]
How long does the link take effect after I start it?

**Comment by thewhiteh4t** [comment]
@bit4lifeonline URL is generated within few seconds, but serveo.net was down yesterday, its up and running now so try again, i will add detection in the script soon, if its down the script will tell us instead of getting stuck

**Comment by bit4lifeonline** [comment]
how long can it last if it worked? 15min? 30min? or always effective until I close?

**Comment by thewhiteh4t** [comment]
@bit4lifeonline Good Question! Serveo did not mention any time limit on their website, i guess we will have to test this

**Comment by bit4lifeonline** [comment]
Waiting for your test results...
