### ISSUE TITLE
Errno 2 when i run Seeker

### ISSUE THREAD

**Issue by Julianinho** [thewhiteh4t/seeker#82]
Hi,
When i run Seeker in Kali Linux i have this message error:

![snip_20190629200229](https://user-images.githubusercontent.com/32013395/60388408-6b347680-9ab1-11e9-88bc-cb4d54f3d690.png)

Do you know what is the problem?

Thanks
Best regards

**Comment by thewhiteh4t** [comment]
@Julianinho this is strange, change directory, git clone again and test, it should work...

**Comment by Julianinho** [comment]
@thewhiteh4t 
I have change directory to put in document folder but i have the same error.

![snip_20190630104505](https://user-images.githubusercontent.com/32013395/60394419-5644fb00-9b24-11e9-8b9f-59bb6109251f.png)


If i write "python seeker.py" to run it, nothing is happening.
I use kali linux in VirtualBox (virtual machine), maybe kali linux is not update ? Do you think it comes from there?

**Comment by thewhiteh4t** [comment]
It looks like you are executing seeker from outside its directory

README clearly mentions these steps :
```bash
cd seeker
python3 seeker.py
```

**Comment by Julianinho** [comment]
For it to be simpler I removed everything and everything started again, so I followed the README

```
git clone https://github.com/thewhiteh4t/seeker.git
cd seeker/
chmod 777 install.sh
./install.sh
```
![1](https://user-images.githubusercontent.com/32013395/60398195-e0f21e00-9b55-11e9-9ac0-74ff962ef8ca.png)

but what should I do next ?
In the README it's talking about this : python3 seeker.py --subdomain google

**Comment by thewhiteh4t** [comment]
@Julianinho 
now do this...
```bash
cd seeker
python3 seeker.py
```
its important that you run seeker from its directory otherwise it will fail

**Comment by Julianinho** [comment]
Thank you that's progressing well !

Now i have this, what should I do ?

![snip_20190630223251](https://user-images.githubusercontent.com/32013395/60401826-401c5680-9b87-11e9-8a71-f53be21253cc.png)

**Comment by itsmehacker** [comment]
@Julianinho  I Request you to follow the video for more information and instructions.

[](https://www.youtube.com/watch?v=ggUGPq4cjSMl)

**Comment by thewhiteh4t** [comment]
Thankyou! @itsmehacker Closing.

**Comment by Julianinho** [comment]
Ok thanks, i I will watch the video.

**Comment by Julianinho** [comment]
I have see the video.

On the video when we see enter "seeker" at the end the command "Ngrok" starts with a custom URL, I do not have that I just have an url "optimus.serveo ... with writing" waiting for user "

What should I do next?
There is no file to transfer before on a site for it to work, everything happens on the command line?

Thank you

**Comment by thewhiteh4t** [comment]
@Julianinho if you saw the demo video, I open that link in a mobile browser, did you try that? Open that serveo url in a mobile browser and watch that video again, also no file has to be transferred.

**Comment by Julianinho** [comment]
@thewhiteh4t 
I have open link in my mobile browser and now i have an another error message:

> can not read http://optimus.... in 20 seconds, check if the site is available and in this case consider setting the read delay in the zap connection options panel.

![Screenshot_2019-07-03-20-22-43](https://user-images.githubusercontent.com/32013395/60616046-e14a1d80-9dd0-11e9-98e5-5f6eed14ea07.png)

I hope I'm going to get there ^^
Thanks for help !

**Comment by thewhiteh4t** [comment]
@Julianinho i see two problems here : 
1. You have skipped a `/` after `nearyou` , so the link you get in the terminal is like : 
`https://optimus.serveo.net/nearyou/`
2. looks like you are using zap proxy, i have not tested seeker with zap proxy so please try to use it without proxy to check if its working properly.

**Comment by Julianinho** [comment]
@thewhiteh4t 
Thank you that advance thanks to your help ;)
It was actually zap that was blocking, but now when I restart seeker it remains stuck on"getting serveo url"
So I went to see the file "serveo.txt" and I got this error message:

> Pseudo-terminal will not be allocated because stdin is not a terminal.

So I looked for someone who had posted the same problem here and I came across another topic in which you said to go see the solution on the website "thomas-cokelaer.info"

Here is the solution:
On the host, add those lines in the file ~/.ssh/config in your home directory
```
Host *  
ServerAliveInterval 30  
ServerAliveCountMax 5
```

The problem is that I do not understand what I have to do, could you tell me what should I do next?
Thank you

**Comment by thewhiteh4t** [comment]
@Julianinho the solution you found is for another problem, your config is fine and you don't have to do anything, actually serveo is down today for some unknown reason, it will be up soon, hopefully.

**Comment by Julianinho** [comment]
@thewhiteh4t 
Ah ok ^^
I'm out of luck, I'll try again later and I'll tell you if it works
Thank you

**Comment by thewhiteh4t** [comment]
@Julianinho serveo is working again, try and report

**Comment by Julianinho** [comment]
@thewhiteh4t 
Thanks for info, i try it and i tell you if is ok
Best regards

**Comment by Julianinho** [comment]
@thewhiteh4t 
It wotks well thanks for your help ;)

**Comment by ugur342** [comment]
I can not view the video it seems to be a private video. I am stuck on the screen where it displays seeker in green outlining.

**Comment by ugur342** [comment]
@thewhiteh4t

**Comment by Idhamm15** [comment]
do you know what is the problem?

![image](https://user-images.githubusercontent.com/92642482/162419032-6b449f43-3ea9-41f4-aeef-0f74a3a2d493.png)

**Comment by thewhiteh4t** [comment]
@Idhamm15 install php server

**Comment by Idhamm15** [comment]
> 

oke thanks for information @thewhiteh4t

**Comment by SKM1998** [comment]
python: can't open file '/data/data/com.termux/files/home/Gallery-Seeker/Gallery-Seeker.py': [Errno 2] No such file or directory

**Comment by Oleg123volk** [comment]
![IMG_20231126_161653_edit_1845643276564169](https://github.com/thewhiteh4t/seeker/assets/98273797/49b08937-4345-4418-aa7c-3cd80f330447)
Guys, please help me, why does it write this to me when I select other templates?
