### ISSUE TITLE
Can I download the ngrok version?

### ISSUE THREAD

**Issue by AndrijCat** [thewhiteh4t/seeker#84]

**Comment by thewhiteh4t** [comment]
`cd seeker` 
`git checkout 0570e41`
`./install.sh`
`python3 seeker.py`

**Comment by AndrijCat** [comment]
![](https://i.imgur.com/RtKobVM.jpg)

**Comment by AndrijCat** [comment]
Thanks, can i change the subdomain in this version?

**Comment by thepinkh4t** [comment]
how do i change subdomain without auto generate

**Comment by thepinkh4t** [comment]
how can i custom subdomain using ngrok version?

**Comment by thewhiteh4t** [comment]
@AndrijCat @thepinkh4t you will have to purchase ngrok premium to get subdomain functionality, it's not free unfortunately. If you will purchase then further instructions are available on ngrok website.

**Comment by AndrijCat** [comment]
Thanks you. Good luck
