### ISSUE TITLE
How can i customize geolocation method?

### ISSUE THREAD

**Issue by amadeus-8** [thewhiteh4t/seeker#86]
Hello! Thank you for this tool
I have a question, how can i customize it, to use with another maps, for example 2gis? Is it works only with google maps? I want to make a test with another map services, maybe it will work more stable, cause sometimes location works good, sometimes it have a big truncation error for a 2-3 streets.
And i am very interested of how does it works, and how can i change serveo for another website

**Comment by amadeus-8** [comment]
I mean how change geolocation api, which one is more accurate?

**Comment by thewhiteh4t** [comment]
@amadeus-8 I am not using google maps API to get the location, it requires creating an auth key first, so I dropped the idea of using gmaps API before creating this tool, instead I am using html geolocation api which does not require any 3rd party support, to be honest accuracy depends from device to device, on some devices I get location accurate to 16m, on others not so much, if you want to use 2gis for viewing the location you can enter the given longitude and latitude into it, also I guess gmaps API is most accurate as they are using multiple methods at once to get the location, you can change serveo for another website, by uploading tool to a vps and running it from there, you can ignore serveo in that case and send the url of your vps server instead

**Comment by amadeus-8** [comment]
> @amadeus-8 I am not using google maps API to get the location, it requires creating an auth key first, so I dropped the idea of using gmaps API before creating this tool, instead I am using html geolocation api which does not require any 3rd party support, to be honest accuracy depends from device to device, on some devices I get location accurate to 16m, on others not so much, if you want to use 2gis for viewing the location you can enter the given longitude and latitude into it, also I guess gmaps API is most accurate as they are using multiple methods at once to get the location, you can change serveo for another website, by uploading tool to a vps and running it from there, you can ignore serveo in that case and send the url of your vps server instead

the program is very interesting, is it possible to get geolocation without users agreement?
Where in code should i change to use another api geolocation method?

**Comment by thewhiteh4t** [comment]
@amadeus-8 right now it's not possible to get the location without permission, that's why it has to be a social engineering attempt, you need a browser 0day for that, you will have to replace the javascript in order to change the api, which means it will break php variables, so i would suggest you to write fresh php and js codes instead of modifying this one or it will become a mess maybe unstable too

**Comment by amadeus-8** [comment]
> @amadeus-8 right now it's not possible to get the location without permission, that's why it has to be a social engineering attempt, you need a browser 0day for that, you will have to replace the javascript in order to change the api, which means it will break php variables, so i would suggest you to write fresh php and js codes instead of modifying this one or it will become a mess maybe unstable too

Oh i am not super coder, that's why i am asking for where the logic of getting location, is it in the file location.js?

**Comment by thewhiteh4t** [comment]
@amadeus-8 yes its in location.js

**Comment by amadeus-8** [comment]
> @amadeus-8 yes its in location.js

Thanks, i will try to customize it with geolocation api's. I think it must work, cause i am not going to change variable names

**Comment by thewhiteh4t** [comment]
@amadeus-8 All the best! closing issue now.
