### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by mooonly** [thewhiteh4t/seeker#9]
# cd seeker/
# ./install.sh
# python seeker.py
  ______  ____   ____  |  | __  ____ _______
 /  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/
/____  > \___  >\___  >|__|_ \ \___  >|__|
	 \/      \/     \/      \/     \/        

[>] Created By : thewhiteh4t
[>] Version    : 1.0.4

[+] Checking Internet Connection... Working

[+] Checking For Seeker Updates... Up-to-date

[!] Starting Apache Server...

[+] Starting Ngrok...

Traceback (most recent call last):
  File "seeker.py", line 209, in <module>
    ngrok()
  File "seeker.py", line 103, in ngrok
    geturl()
  File "seeker.py", line 90, in geturl
    json1 = json.loads(page)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by thewhiteh4t** [comment]
operating system?

**Comment by mooonly** [comment]
system is kali linux 2018.03
 every time 。and Line 88 is 
r1= requests.get('{}'.format(api))
print (r1)   Return result is  <Response [502]>

**Comment by thewhiteh4t** [comment]
please share contents of install.log file present in seeker directory

**Comment by mooonly** [comment]
[install.log](https://github.com/thewhiteh4t/seeker/files/2285470/install.log)
This is not the first time the log is installed. The first log has been lost.

**Comment by thewhiteh4t** [comment]
goto line 83 i.e.
`time.sleep(2)`
change it to 
`time.sleep(10)`
it looks like ngrok is taking time to start

**Comment by mooonly** [comment]
Yes, thank you very much for your reply.
