### ISSUE TITLE
Termux on android 9 samsung s8+

### ISSUE THREAD

**Issue by fiercestfall417** [thewhiteh4t/seeker#90]
Hi,

Been playing around with termux for a while and discovered seeker..

Soon as I try to run seeker I get the following error:

$ls
fluxion  seeker
$ cd seeker
$ python seeker.py
$ ls
Dockerfile       install.log  template
LICENSE          install.sh   termux
README.md        seeker       termux_install.sh
arch_install.sh  seeker.py
$ python2 seeker.py
Traceback (most recent call last):
  File "seeker.py", line 9, in <module>
    import requests
ImportError: No module named requests
$

Any idea what could be wrong? I have googled and searched all over but still none the wiser....

**Comment by thewhiteh4t** [comment]
@fiercestfall417 Termux uses Python 3 by default, and seeker also uses python 3, and if you read the README, I have clearly mentioned the command as : `python3 seeker.py` but you are executing `python2` , in termux use either `python` or `python3` to execute seeker.py or use `./seeker.py`

**Comment by fiercestfall417** [comment]
Thanks mate.. 

Tried it but still the same...

$ ls
cd1  fluxion  seeker
$ python3 ./seeker.py
python3: can't open file './seeker.py': [Errno 2] No such file or directory
$ cd seeker
$ python3 ./seeker.py
Traceback (most recent call last):
  File "./seeker.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
$ python3 seeker.py
Traceback (most recent call last):
  File "seeker.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
$ ./seeker.py
Traceback (most recent call last):
  File "./seeker.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
$ python ./seeker.py
Traceback (most recent call last):
  File "./seeker.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
$

**Comment by thewhiteh4t** [comment]
@fiercestfall417 inside seeker directory, you will find a file named `install.log` , share it, if you don't find this file, execute `termux_install.sh`

**Comment by thewhiteh4t** [comment]
Closing, due to inactivity.
