### ISSUE TITLE
Might just be me. But page isn't loading

### ISSUE THREAD

**Issue by CharlesTheGreat77** [thewhiteh4t/seeker#91]
I have a 19th century macbook, and after downloading all that's necessary I simply can't load the page. The page loads all the way supposedly, but it's just a blank page. Not sure if it's my php or something. Any solutions, please let me know. Other than that, on my PC it works like a charm, absolutely neat program, just flawless, no lie.

**Comment by thewhiteh4t** [comment]
@CharlesTheGreat77 19th century seriously? anyways looks like a safari issue, also make sure you include `/` at the end of URL like this : `https://test.serveo.com/nearyou/`

**Comment by CharlesTheGreat77** [comment]
Lmaoo it's a dinosaur alright.. I'm actually using google chrome but it's alright I'll figure it out. Thanks!!
