### ISSUE TITLE
Serveo Status Down

### ISSUE THREAD

**Issue by raytafarhan** [thewhiteh4t/seeker#95]
______  ____   ____  |  | __  ____ _______
 /  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/
/____  > \___  >\___  >|__|_ \ \___  >|__|
         \/      \/     \/      \/     \/        

[>] Created By : thewhiteh4t
[>] Version    : 1.1.6

[+] Checking for Updates.....[ Up-To-Date ]

[+] Checking Serveo Status...[ DOWN ]

can we change service?

**Comment by dansailorsav1** [comment]
It seems Serveo is totally down all together :( I wonder if we could change the Serveo to ngrok? @thewhiteh4t

**Comment by zertaizer** [comment]
the same error, tried to go to serveo.net does not go

**Comment by thewhiteh4t** [comment]
@raytafarhan @dansailorsav1 @zertaizer I removed ngrok from seeker because it was getting complicated and a lot of users were having problems with it, ngrok uses its own client, each client is different for different architectures, so I had to make an install script which would first detect the architecture and then download ngrok accordingly, half of the time architecture was not getting chosen correctly and in case of android there are dns problems, for example it does not work on my WiFi but works on 4G...

Serveo on the other hand uses ssh for connection, ssh is already present in all distributions of linux and hence I dont have to install it or download it, that leaves me with the comfort of executing a single command and getting a URL, but when its down its a huge issue I understand, if there is an * client less * alternative we can try that or I can make the code proceed and users can use their choice of client such as ngrok * manually * .

**Comment by flexifi** [comment]
Can you please release a Ngrok setup

**Comment by zertaizer** [comment]
what do i need to do to make the seeker work
![Screenshot_2019-08-29-05-48-02-211_com termux](https://user-images.githubusercontent.com/54549612/63906534-cab2f200-ca20-11e9-8f94-fe3750cf8072.png)

**Comment by thewhiteh4t** [comment]
@zertaizer you cannot do anything, wait until serveo is UP again

**Comment by MrDmitry1107** [comment]
А через VPN будет работать?

**Comment by thewhiteh4t** [comment]
Pushed a new update, v1.1.7, please test...

**Comment by flexifi** [comment]
Ok

**Comment by MrDmitry1107** [comment]
Отлично работает

**Comment by MrDmitry1107** [comment]
Написано UP,но ссылка не генерируется.

**Comment by thewhiteh4t** [comment]
@raytafarhan @dansailorsav1 @zertaizer @flexifi v1.1.8 released, serveo is up now and I have added a manual mode for tunnels, you can execute your choice of tunnel manually (Example : start ngrok in a second terminal), closing.

**Comment by yogeshkil3r** [comment]
Still Server Down Any Help
![Screenshot_Termux_20191115-232437](https://user-images.githubusercontent.com/57810351/68965654-578c7100-0802-11ea-8916-e9189fdf7652.png)

**Comment by putinpe** [comment]
![image](https://user-images.githubusercontent.com/58068256/69414805-7cae4180-0d24-11ea-8cda-988441f16417.png)

**Comment by thewhiteh4t** [comment]
@putinpe please watch my latest video for solution to this issue https://youtu.be/FEyAPjkJFrk

**Comment by putinpe** [comment]
> @putinpe, пожалуйста, посмотрите мое последнее видео для решения этой проблемы https://youtu.be/FEyAPjkJFrk

Thank you so much. Everything worked out

**Comment by TheConficker** [comment]
Hi friend I did not work the page [url=https://radikal.ru][img]https://c.radikal.ru/c11/1911/56/ecadc9fa643b.png[/img][/url] please help me

**Comment by thewhiteh4t** [comment]
@TheConficker if you watch the video carefully and see what seeker is telling carefully you will see there is a `/` after `nearyou` which you missed

**Comment by putinpe** [comment]
Все отлично работает 12:09, 27 ноября 2019 г., thewhiteh4t <notifications@github.com>:@TheConficker if you watch the video carefully and see what seeker is telling carefully you will see there is a / after nearyou which you missed

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by BaDRabbiT404** [comment]
Hi friend) I have a problem. When I write the ngrok http 8080 command in the second terminal, it says to me that there is no ngrok command

**Comment by thewhiteh4t** [comment]
@BaDRabbiT404 you need to download ngrok first then you can use it, google it or check on youtube many guides are available for ngrok

**Comment by tchakshu** [comment]
after watching your uploaded video I am still unable to do it can you please help me @thewhiteh4t
![Screenshot_2020-04-17-05-07-32-460_tech ula](https://user-images.githubusercontent.com/55215888/79553184-1840a580-806a-11ea-8979-69f00806de74.jpg)

**Comment by thewhiteh4t** [comment]
@tchakshu you did not read usage in README properly and you clearly don't know the difference between python and python3, I suggest you learn some basics first then use tools, no offense

**Comment by tchakshu** [comment]
ok thanks but one more thing can you suggest me from where i can learn these basic differences of python and python3 and how to open readme please tell me

**Comment by thewhiteh4t** [comment]
@tchakshu there is another very popular tool, its a search engine, called google, give it a try

**Comment by Vishnudancer21** [comment]
Try  `./seeker.py -t manual -k testkml`  then see waht happens nxt.. enjoy..

**Comment by darkevilzzz** [comment]
U can try to add both serveo and ngrok 
Like option 1 as serveo and option 2 as ngrok so that the user can choose which one they can use

**Comment by thewhiteh4t** [comment]
@darkevilzzz use -t option to use ngrok, checkout my demo : What's new in seeker v1.1.9 for reference, link is in the readme

**Comment by SudoCrypted** [comment]
Who are you?

**Comment by tekmehta** [comment]
![WhatsApp Image 2021-05-16 at 4 42 29 PM](https://user-images.githubusercontent.com/71179275/118394710-01ea8c00-b666-11eb-86b8-c6c1771d1c0b.jpeg)
please help me

**Comment by Bruno-tech997** [comment]
> ![WhatsApp Image 2021-05-16 at 4 42 29 PM](https://user-images.githubusercontent.com/71179275/118394710-01ea8c00-b666-11eb-86b8-c6c1771d1c0b.jpeg)
> please help me

if serveo don't work try manual

**Comment by luispitt16** [comment]
> > ![Imagem WhatsApp 2021-05-16 às 4 42 29 PM](https://user-images.githubusercontent.com/71179275/118394710-01ea8c00-b666-11eb-86b8-c6c1771d1c0b.jpeg)
> > por favor me ajude
> 
> se o servo não funcionar, tente o manual


> > ![Imagem WhatsApp 2021-05-16 às 04 42 29 PM](https://user-images.githubusercontent.com/71179275/118394710-01ea8c00-b666-11eb-86b8-c6c1771d1c0b.jpeg)
> > por favor me ajude
> 
> se o servo não funcionar, tente o manual

tive o mesmo problema, fiz do jeito manual e não obtive sucesso..

**Comment by inconshreveable70369** [comment]
./seeker.py -t manual

**Comment by nitish131021** [comment]
Bro serve is offline. What to do?

**Comment by thewhiteh4t** [comment]
@nitish131021 read README and follow the instructions

**Comment by zefir-deferend** [comment]
@thewhiteh4t please help, it does not generate a link 
                        __
  ______  ____   ____  |  | __  ____ _______
 /  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/
/____  > \___  >\___  >|__|_ \ \___  >|__|
     \/      \/     \/      \/     \/

[>] Created By   : thewhiteh4t
 |---> Twitter   : https://twitter.com/thewhiteh4t
 |---> Community : https://twc1rcle.com/
[>] Version      : 1.2.8

[!] Select a Template :

[0] NearYou
[1] Google Drive
[2] WhatsApp
[3] WhatsApp Redirect
[4] Telegram
[5] Zoom
[6] Google ReCaptcha
[>] 2
                                                                                                
[+] Loading WhatsApp Template...                                                                
[+] Group Title :

**Comment by thewhiteh4t** [comment]
@zefir-deferend watch demo video in readme

**Comment by zefir-deferend** [comment]
thanks
