### ISSUE TITLE
Imie,connected Port,privet IP

### ISSUE THREAD

**Issue by drshell60** [thewhiteh4t/seeker#96]
Hello 

i just test your code and its work perfect ! 
i got some question if we or you can add it to the code , anyway to collect info im title , Imie , Privet IP of the client and connected port , since i got clients connected to my network using VPN so i need to know what port they connect ?

**Comment by thewhiteh4t** [comment]
@drshell60 getting imei is not possible through browsers but I am working on adding private IP and Port.

**Comment by Cyb3rG0D7** [comment]
https://github.com/rrohaill/IMSI-IMEI
