### ISSUE TITLE
Serveo Status (1.1.3 vs 1.1.6)

### ISSUE THREAD

**Issue by wacs** [thewhiteh4t/seeker#98]
@thewhiteh4t 

I tried running the version 1.1.3 and serveo status was ok. When tried running the version 1.1.6 after a minute, serveo status down. (Also tried again with 1.1.3 and status ok)

I think the issue is not in the serveo service. Maybe is something in the update.

![Screenshot_20190831-163011__01](https://user-images.githubusercontent.com/4405212/64069345-75880380-cc0d-11e9-88cc-9d732daa4195.jpg)

![Screenshot_20190831-163046__01](https://user-images.githubusercontent.com/4405212/64069346-7de03e80-cc0d-11e9-817c-bfbe172f7c27.jpg)

**Comment by thewhiteh4t** [comment]
That's strange, because if I visit https://serveo.net , its down @wacs

**Comment by thewhiteh4t** [comment]
Pushed an update v 1.1.7 please verify if its working now without any errors...

**Comment by wacs** [comment]
Just downloaded the update. Serveo not responding.

**Comment by thewhiteh4t** [comment]
@wacs just tested again, its working for me, are you able to ping serveo.net? And if you are in Russia, serveo is blocked

**Comment by xsecwizard** [comment]
@thewhiteh4t It's working for me after the update. It doesn't return a server status as "down" but it is still useless since the website doesn't work. There will be no prompt for location permission.

**Comment by thewhiteh4t** [comment]
@xsecwizard yeah, there is no other client less service like serveo :(

**Comment by thewhiteh4t** [comment]
@wacs @xsecwizard v1.1.8 released, serveo is up now and I have added a manual mode for tunnels, you can execute your choice of tunnel manually (in a second terminal), closing.
